### ISSUE TITLE
Scrollbars still disappear sometimes

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1020]
Issue #823 still occurs sometimes.
Steps to reproduce:
* Have a fresh privacyIDEA without subscription file and without a hide_welcome policy
* Login as admin, click through welcome dialogs
* Logout
* Login as admin, no welcome dialogs this time
* Click "Enroll Token" -- it's impossible to scroll.

This may be related to https://github.com/valor-software/ngx-bootstrap/issues/2137 -- indeed, when the scrollbars are invisible, the ``<body>`` tag has the ``modal-open`` class!

**Comment by cornelinux** [comment]
Interesting side effect: if you wait for the screen to be locked and unlock again, the scrollbars are back!

**Comment by cornelinux** [comment]
The problem is, that during the relogin we indeed run through the welcome dialog code - but due to some strangeness the dialog is not displayed. But the modal-open class is set on the body. here
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/controllers/tokenControllers.js#L91

**Comment by cornelinux** [comment]
Au.

            $('#dialogWelcome').modal().hide();

did actually hide the html element of the dialogWelcome from the DOM. So the dialog would not be displayed again after a relogin!
