### ISSUE TITLE
make the backend honor the browser language settings

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#1065]
Currently, if the server runs in a different locale environment (i.e. LANG=de_DE.UTF-8) than the browsers language setting, you'll get mixed language output, depending if the text comes from the frontend (javascript) oder the backend (python).
This can be seen when creating a new policy. The action description is retrieved from the backend and thus delivered in the current backend language.
it would be more consistent if the backend could switch the language on each request based on the browser settings.

**Comment by cornelinux** [comment]
The browser passes the accepted languages in the header:

    Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7

we could catch this in the ``before_after.py`` and pass this down to the libraries.
We could add the paramter ``languages`` here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/__init__.py#L22

The question is, if a language change in the browser (since another user issues a request with another browser langauge) has the desired effect or if we run into caching issues.
