### ISSUE TITLE
Recover HSM not ready

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1069]
If an HSM with the AESHSM module goes to the state *hsm not ready*, it usually will not recover without any admin interaction.
This could happen if the network connection is lost for a longer time and the retry loop in the aeshsm.py module is exhausted.

We should add a way to be able to recover the hsm state and reinitialize the hsm if necessary.

Or check: is it necessary to go to the hsm_not_ready state?

If we need to recover the state, we could do this via a decorator for the encrypt and decrypt and random function. We might also think about adding some timeout for recovery?

**Comment by fredreichbier** [comment]
The linked commit looks like a good start for me!

In addition, I was thinking about building a small mock PKCS11 module so that we could test these retry/recovery situations in the unit tests.

**Comment by cornelinux** [comment]
This would be great.We could simulate the absence of the HSM, observe the is_ready=False , reconnect the HSM and do a successful encryption.





null

**Comment by fredreichbier** [comment]
I think so too! I'll look into using mocks to simulate the HSM absence tomorrow.

**Comment by fredreichbier** [comment]
I added a simple mock module in 4c7ce28d63032df6. I also inspected the HSM code more closely and I think the cause why we don't have proper recovery is something different and I now think the decorator wouldn't have much effect: Assume we don't have the decorator, the HSM is in a defunct state (and ``self.is_ready`` is False) and we call ``encrypt``. Then, the security module will try to encrypt the given data. But as the HSM is in a defunct state, ``self.session.encrypt(k, bytes(data), m)`` will fail, in which case the retry loop will call ``initialize_hsm()`` anyway. The decorator would only help to make this call earlier, without trying to encrypt first. What do you think?

I think the issue is rather in the handling of security modules in general. Assume we have a defunct HSM security module with ``is_ready`` set to False. If privacyIDEA now attempts an encryption, it will call ``_get_hsm()`` in lib/crypto.py. But this line:
https://github.com/privacyidea/privacyidea/blob/beeb9f159ffdc8e7b01aa90dec222a87ebf3765a/privacyidea/lib/crypto.py#L336
will then bail out because ``is_ready`` is False. So even with the decorator, privacyIDEA would never try to re-initialize the HSM again.

**Comment by cornelinux** [comment]
I think you are totally right.

We might change the member attribute ``self.is_ready`` to a method (with a property decorator). This way we could within the HSM module (each module could handle it differently) try to re-initialize the hsm, if it is not ready.

~~~~python
@property
def is_ready():
    if not self._is_ready:
        # put this in a retry loop
        self.initialize_hsm()
    return self._is_ready
~~~~
(and change the attribute self.is_ready to self._is_ready)

If the crypto lib wants to know, if the HSM is_ready, the hsm could just try to check, if it can get ready, if it was not.

**Comment by fredreichbier** [comment]
I opened #1073 which should fix the issue above.

We could also re-think our retry loop. Currently (the PR does not change this), the behavior is as follows: Consider encrypting fails with a PKCS11 error. Then, the retry loop is entered and ``initialize_hsm`` is called, which tries to acquire a new session via ``_login``. But if this fails now, another PKCS11 error is raised, and the retry loop is exited! Should we maybe also have a retry loop in ``_login``?
