### ISSUE TITLE
Allow using objectGUID as login name

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1076]
Especially when using the ownCloud app, it would be useful to be able to specify ``objectGUID`` as the login name attribute. Right now, this does not work because
* for ldap3 2.5, all login names are considered to be ``{``
* for ldap3 2.1.1, we get the first character of the objectGUID as the login name

**Comment by cornelinux** [comment]
What does  are considered to be ``{`` mean?

I also think we need to enhance the search string here, to be able to also find objectGUIDs:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/LDAPIdResolver.py#L532

Interesting thing, which I totally forgot: The ldap resolver supports several login attributes comma separated. I.e. you can setup

    sAMAccountName, email

And the user can either login with his sAMAccountName or with his email address. Since logging in with once objectGUID is really wired, we could also only allow this in such a list.
