### ISSUE TITLE
SMS token does not store the phone number

### ISSUE THREAD

**Issue by mhemrg** [privacyidea/privacyidea#1095]
I've created an SMS token and tried to send an OTP but I didn't receive the message. Then I manually updated the phone field in database and it worked.

Logs:
```
[2018-06-10 14:27:24,387][8582][140291328751424][INFO][privacyidea.lib.user:230] user u'boom' found in resolver u'deflocal'
[2018-06-10 14:27:24,387][8582][140291328751424][INFO][privacyidea.lib.user:231] userid resolved to u'1002' 
[2018-06-10 14:27:24,572][8582][140291328751424][WARNING][privacyidea.lib.tokens.smstoken:354] Token PISM000018E5 does not have a phone number!
```

**Comment by mhemrg** [comment]
@cornelinux Thanks for your quick response.

I'm typing the phone number during enrollment for a user within the dashboard, as an admin. And my user resolver is `/etc/passwd`.

**Comment by cornelinux** [comment]
The ``etc/passwd`` would need to look like this, so that you actually can use a phone number from the file:

  
 cornelius:IX7BdMthIBUvI:1000:1000:Cornelius,field2,+491111111,+491234566,user@localhost.localdomain::

Nevertheless, if the admin enters a phone number manually, it is/should be stored with the token anyways. Do not check the "dynamic" checkbox - otherwise it will not store the phone number.

**Comment by mhemrg** [comment]
I didn't check the "dynamic" checkbox. I'm pretty sure that's a bug.
Does it validate the phone number?

**Comment by cornelinux** [comment]
With your limited information I can not see (reproduce) this behaviour in the current development version.
Please provide all information (that is requested in the initial issue creation) including the debug log.
It might also be useful to activate the developer mode in your browser and check which request data is actualy sent, when you hit the button "create token".
