### ISSUE TITLE
HTTPSMSProvider implement retries

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1097]
hi,
it would be great if there would be retries for sending SMS, because there might be several components between us and SMS provider where interruptions might happen e.g. our network/Internet/Provider HA etc...

**Comment by cornelinux** [comment]
On what kind of retries are you thinking? Send within 30 seconds again? 3 times each minute?

Currently this is not possible to add, since we do not detach the sending of the SMS, i.e. the SMS is send within the first HTTP request. There is no task or cron job, that issues the new SMS sending. 

However, we plan to add a cron runner (#992) and maybe this would also be an additional way to use the cron runner.

**Comment by splashx** [comment]
@cornelinux not at this level, really at the http request level. More precisely somewhere here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/smsprovider/HttpSMSProvider.py#L133

Something like a retry using the `r.status_code` as a control to be a bit more persistent on the HTTP request.

**Comment by cornelinux** [comment]
Still. This is the library that triggers the request to the SMS Gateway. And this actually happens within the _first_ request to the privacyIDEA server. Thus, the originial request (with the static password) would only return after ``n`` minutes, till all retries have failed.

**Comment by splashx** [comment]
@cornelinux I meant on that _first request_ (atomic) level. Not a retry per user login request, but a retry after the request, at the library level.

**Comment by splashx** [comment]
@fredreichbier I dont think #1101 closes this 🤔

**Comment by fredreichbier** [comment]
Whoops, you're right, we had a wrong issue reference there. Thanks for noticing!
