### ISSUE TITLE
Increase binding of privacyIDEA Authenticator App to the privacyIDEA Server

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#1103]
Create an endpoint for further communication with the authenticator app.
Possible uses:
- automate the 2-step rollout
- retrieve further information about the smartphone for better management in privacyidea
- check that tokens are enrolled successfully (without 2-step)
- delete (or notify) when a token is deleted on the smartphone
- delete the token on the smartphone, when it was deleted on the server
- the smartphone could pass the OS language, thus text messages to this smartphone sent by privacyIDEA (for Push tokens) could be in the language
- add non deletable tokens (see #1024)

**Comment by cornelinux** [comment]
# How the phone authenticates

The challenge for such endpoint is, that we do not have an authorization header. While a user or admin triggers the first step of the enrollment process, the phone, that scans the QR Code in the first step, initially has no authentication credetials to communicate to privacyIDEA like the endpoint ``/token/init``.

We need to pass credential data in the initial QR code. 

This could be:

* Some passphrase/token/code that is valid for a certain amount of time and kept in the database of privacyIDEA
* A JWT token, which has a short runtime of maybe max 5 minutes, since it is only used by the automated smartphone processes. This token would contain: 
  1. the serial number of the token (To identity the token when communicating to privacyIDEA)
  2. expiration time

Then the smartphone could use the JWT to:
1. send the phone part of the two step enrollment
2. send further device information to be stored with the token in privacyIDEA like
   * Phone model
   * phone name
   * OS Type
3. Confirmation, that the QR code was scanned successfully.
4. Notify privacyIDEA; if the user deletes the token. In this case we would need a JWT that is not short living (5 minutes), but that would be long living like a few years.

**Comment by nilsbehlen** [comment]
merge with https://github.com/privacyidea/privacyidea/issues/1291
