### ISSUE TITLE
Wrong password hash for sqlresolver

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1114]
When creating a SQLresolver with ssha512 the passwords are still hashed with ssha256.

see:
Is it the correct hash?
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SQLIdResolver.py#L509

Bummer, we still hash ssha256?
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/resolvers/SQLIdResolver.py#L532

**Comment by fredreichbier** [comment]
It seems like adding new users is broken if *any* Password Hash Type is selected in the UI because we actually double-hash the password then:

First, we use the specified Password Hash Type to hash the password here:
https://github.com/privacyidea/privacyidea/blob/f9c2fbb1138d73e05da0c48f75b99d1e734659e0/privacyidea/lib/resolvers/SQLIdResolver.py#L509
and then, we hash the resulting hash *again* with SSHA256:
https://github.com/privacyidea/privacyidea/blob/f9c2fbb1138d73e05da0c48f75b99d1e734659e0/privacyidea/lib/resolvers/SQLIdResolver.py#L536

In case the Password Hash Type field in the UI is left blank, it works because the password is only hashed with SSHA256.

**Comment by cornelinux** [comment]
If I understand correctly we need to fallback to SSHA256 if no hash is specified, otherwise use the specidied hash.

...and drop the second SSHA256 in any case.
