### ISSUE TITLE
Health check API endpoint

### ISSUE THREAD

**Issue by stojmir** [privacyidea/privacyidea#1115]
How about an unauthenticated API endpoint that will return the health status of various components on which a successful authentication is dependent?
For example:

GET /system/health

Token database : OK
Audit database: OK
LDAP resolver: OK
HSM connection: OK

**Comment by cornelinux** [comment]
This could be connected to some other issues like #957.
We could also gather the health data with a new stats module. See #1027 #902 
We could define a new *Cron Runner module* (like 1028), which gather no actual values but simply stores the OK-State as 1/0. The API could be based on the REST API in #1027.

But @stojmir , how would we define that the "status of the token database" is "OK"?

**Comment by direvus** [comment]
The status report ideas are nice, but it seems like there is some complexity there, holding the idea back.

What I need from a healthcheck is a lot simpler; a URL that I can hit, without authenticating, and just get back a 200 OK if the server is running and able to respond to requests.  This is used by load balancers to direct traffic.  I think it would pretty trivial to add a route that does this.  Should that be raised as a separate feature request, or will this ticket do?

**Comment by cornelinux** [comment]
You could simple fetch the login page at https://yourserver.net/

**Comment by direvus** [comment]
If the root URL returns a success code while you're unauthed, then yes, that will work fine, thanks.  A lot of web apps (LinOTP included) will redirect you to a separate login URL if you try to visit the root URL unauthed.

**Comment by nilsbehlen** [comment]
should be `/healthz`, not only because of convention but also the route `/system` is authenticated and therefore not suited for this.
We can check if we also need `/readyz` and `/livez`, or if something specific to our system would be better like `/resolverz` to check resolver availability.

**Comment by henrik-falk** [comment]
Some details to discuss about the implementation:
Considering Kubernetes, livez and readyz should be implemented, since healthz is deprecated.
A healthz endpoint can still exist as a single manual or external endpoint.

The readyz (and healthz) endpoint will check for the APP_READY flag in the app.config context. For now this flag toggles at the beginning and end of the create_app process. Further dependencies should toggle the flag if the app is not ready to receive data.

/healthz/resolversz/ will provide an overview similar to the example above. For now all LDAP and SQL resolvers will be tested and individually included in the response message with the status "OK" or "fail". The top-level status will be "OK" or "fail" if all resolvers have status "OK" or one fails.
