### ISSUE TITLE
Misleading "Wrong Credentials" in Audit log when a challenge is triggered

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1192]
# Configuration

* privacyIDEA Version:
2.22
* Installation method:
virtualenv

When logging in with WebUI and SMS token, after entering username and password (with passthrough enabled and otppin=userstore) we see in audit log message Wrong credentials (also when you inspect network logs through browser), log in process continues correctly with prompt for SMS token and when correct SMS token entered is successfull. That audit log is quite confusing when troubleshooting user problems

**Comment by p53** [comment]
Problem is here:
https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/api/auth.py#L259
user_auth is false even when password entered was good
user_auth comes from above line
https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/api/auth.py#L250
in our case in this method is executed this line
https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/lib/auth.py#L127
and continues with check_user_pass method in which we are entering method
https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/lib/token.py#L1955 and this method executes if branch on line:
https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/lib/token.py#L2158

i would suggest either set res = True in lib/token.py in challenge_request_token_list if branch or
based on details, set another if clause with different message at https://github.com/privacyidea/privacyidea/blob/37950535324cc18fe4e8585bfd1a2716f243c3ab/privacyidea/api/auth.py#L259

**Comment by cornelinux** [comment]
``passthrough`` is not relevant here, since the user has a token, and so the token checking rules apply.

The credentials are wrong. This was not a successful authentication, so all we could do here is check the info-field in the audit log. Isn't there a hint, that an SMS was triggered?

**Comment by cornelinux** [comment]
I renamed the topic and I hope it matches the issue nicely.

**Comment by p53** [comment]
i checked right now, there is only wrong credentials message
```

626785 | 8/20/18 13:22:25 | POST /auth | 0 |   |   |   |   | someuser |   |   | 10.10.20.50 | Wrong credentials | OK | FAIL |   |   | otp.some-domain.com
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
```
```

**Comment by cornelinux** [comment]
So I suggest, we adapt the info-field in the audit log to add a note like "SMS triggered" or "Email triggered" or "Challenge triggered".
The authentication itself (``result value``) will still be ``False``.

**Comment by cornelinux** [comment]
Here we return with a ``details->message`` set to "wrong otp value"

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/auth.py#L250

The thing is, that this message is not passed to the audit log.

Here (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/auth.py#L260) we raise an exeception with "Authentication failure. Wrong credentials", which is good, since this text is displayed in the UI. And we do not want to disclose more information at the UI.

However, this is also the text, that is written to the audit log here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L269

The solution would be, that the  ``AuthError`` has two texts, one to be displayed in the UI and on to be written to the audit log.

**Comment by nilsbehlen** [comment]
this has been improved.
