### ISSUE TITLE
UserNotification for validate_check event with LOGGED_IN_USER doesn't work

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1215]
# What did you try to do?
set event handler
event: validate_check
HandlerModule: UserNotification
Options:
  To: logged_in_user

i also tried with tokenowner option and this works

and same thing with scripthandler and validate_check

# What outcome did you expect?
sent notification

i checked here https://github.com/privacyidea/privacyidea/blob/f87a744e6a2026980aa8827682871490f162ff3e/privacyidea/lib/eventhandler/usernotification.py#L249

and logged_in_user is here empty dict

also checked that serial is empty also with validate_check and script handler, due to that in serial is gathered from request data, but in request with validate_check there is no serial, just in response

**Comment by cornelinux** [comment]
``logged_in_user`` only exists, if a user logged in to the webui.
``validate_check`` is an authentication event with no login to the webui.

Of course in the request there is no serial, since the request does not contain a serial.

Naturally all data is contained at every step of the processing of the request. Some data will never be contained. There will be not "tokenowner" in the event of an administrator creating a resolver.
There is a bit of last logic, that needs to be added by the administrator. But after all, this it what makes the system so flexible.

So you already realized, that you need to use ``tokenowner``.

Works as designed. If you have configuration questions, please turn to https://community.privacyidea.org
