### ISSUE TITLE
Event handler script fails but error is not logged

### ISSUE THREAD

**Issue by p53** [privacyidea/privacyidea#1222]
using script handler for event

script fails but there is nothing in log

problem is here

https://github.com/privacyidea/privacyidea/blob/f87a744e6a2026980aa8827682871490f162ff3e/privacyidea/lib/eventhandler/scripthandler.py#L168

Popen doesn't throw exception when script fails, it just returns error code

check_call should be used or check_output, this method throws CalledProcessError exception

**Comment by cornelinux** [comment]
I removed the bug label, since this is by design.
``Popen`` does not wait for the process to finish. As this is an event handler, the HTTP Request can return. In many cases it will make sense, that the script is started but also the HTTP Request returns, without the script blocking the HTTP request.

I think there should be two possibilities:
* Start the script, do not wait for completion
* Wait for the script to return and:
  * Fail the http request if the script fails
  * Simply log, that the script has failed.

@p53 What is your scenario - why and how do you need to know, that the script failed?
