### ISSUE TITLE
LDAP resolver clear text password in UI and REST

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#1271]
# What did you try to do?

Manage proper information access

# What outcome did you expect?

LDAP resolver password should not be accessible through the UI/REST

# What outcome did you experience?

LDAP resolver password is retrievable in clear text in REST and UI network tabs

# Configuration

* privacyIDEA Version: latest

* Installation method: source

====

Hi @cornelinux,

Currently, the LDAP resolver password is accessible in clear text through the REST API and the UI network tab. Also, when a admin user click on a user details, a call to the resolver API to get resolver info also always called, and received a cleartext bindpw in there.

We think it is a risk to have access to clear text LDAP bindpw through the UI and REST call, and would like to create a ticket to able to disable the retrievable of LDAP password through the UI and REST. The password field can still be displayed and hold placeholder value in case admin want to save a different LDAP password.

We hope that this sounds like a common interest for you too!

Thank you.

**Comment by cornelinux** [comment]
So you are talking of the bindpw of the resolver?

The current design is, that the resolver configuration is loaded, could be modified and sent to the server again. We also need the bindpw, to be able to run the resolver test, since in this case the current values are used and not the server values (this has the background to avoid misconfiguration).

So if we would not load the bindpw in the rest ui, we would not be able to run the resolver test, *after* the  resolver was saved and loaded again.

We could somehow return a placeholder, and have the UI *not* set the bindpw if it is still the placeholder.
This would have to be confiugrable. 
In the resolver?

**Comment by quynh-axiadids** [comment]
@cornelinux I think the most popular practice is:
- Not reveal the bindpw in the the API response
- Still support current resolver connection check
- Still support on the fly resolver connection check.

And example of a product is Keycloak by RedHat. When Keycloak API return the LDAP config, the bindpw is masked (even in the json response, not just masked in the UI). However, the LDAP connection test for the current config as well as on the fly config (when changing bindpw on the fly in the UI) work correctly.

Looking at the Privacyidea code, I think the challenge is to be able to test the current LDAP resolver if the bindpw is not returned in the API, because as you mentioned, the testConnection lib use all the params that passed back from the UI, and not from the DB.

Please let us know if this vulnerability can be fixed in future released.

Thank you.

**Comment by cornelinux** [comment]
@quynh-axiadids thank for coming back to this.
How would you recommend to "mask" the password in the response?

Currently we do not distinguish between save and update in the API. So the password, that is sent on a SAVE request will be stored in the configuration. We could use a password "MASKED" to tell the privacyIDEA Server that the password should not be changed in the config.
In this case the configuration will fail, if the bindpw is really "MASKED".

We could send an empty password. And tell the request that this is an update request. But then the difficulty is to know, whether the update request contains an empty password (like set the password to null) or if the password was not changed.

This is problem that has been solved before, but probably not always to the best outcome, so I am curious for your input here.

**Comment by cornelinux** [comment]
@fredreichbier @plettich how would you indicate, that a resolver would be updated, but not the password?

**Comment by fredreichbier** [comment]
I agree that checking for a special value like "MASKED" or the empty string when saving resolvers is not optimal. Maybe we could
* modify the ``get_resolvers`` endpoint such that it *returns* a special value for the password
* modify the ``set_resolver`` API call such that it takes a dictionary/JSON object as the ``password`` parameter like
```
{"change": false, "value": ""}
```
which would signal that the password value should not be changed, and
```
{"change": true, "value": "secure123"}
```
to indicate that the new password is "secure123". Then, we could also have
```
{"change": true, "value": ""}
```
for the empty password and
```
{"change": true, "value": "MASKED"}
```
for the password "MASKED".

**Comment by cornelinux** [comment]
So the GET /resolver would return an empty password. (Or a "Masked" password).

The webui would realize, that the password was changed or entered. How would it realize that? That the password field was touched or changed?

An then set the ``"change": true``.

The annoying thing is, that an administrator can not visit an existing resolver, change the search filter and test the resolver. Because he would not know the password.  :-/

**Comment by fredreichbier** [comment]
> The webui would realize, that the password was changed or entered. How would it realize that? That the password field was touched or changed?

Either that, or we actually make the action explicit:
* the password field is disabled
* but there is a checkbox next to it that says "change password", which enables the field

> The annoying thing is, that an administrator can not visit an existing resolver, change the search filter and test the resolver. Because he would not know the password. :-/

Hm, true. Also, we have a problem if the user renames an existing resolver "res1" to "res2" without changing the password: This currently creates a new resolver "res2". But the server can't properly set the password of "res2" because it doesn't know it's a copy of "res1" :-/

This may get too complicated, but we could add an invisible ``reference`` to the resolver config which holds the name of the resolver the current configuration is based on. The server could use this field in "test resolver" and when copying resolvers to retrieve the actual password.

**Comment by plettich** [comment]
Could we avoid sending the password parameter if the password is empty or hasn't changed?
We could then check if the parameter exists and use it or get the original value from the db.

**Comment by fredreichbier** [comment]
Maybe this would also be a possibility, though I guess we would also need to keep the option to set an empty password.

With regards to my second point above that renaming resolvers would be complicated: I guess it would also be okay to require that the password is re-entered when an existing resolver is renamed -- what do you think?

**Comment by cornelinux** [comment]
> With regards to my second point above that renaming resolvers would be complicated: I guess it would also be okay to require that the password is re-entered when an existing resolver is renamed -- what do you think?

@fredreichbier I think this is totally fine!

**Comment by fredreichbier** [comment]
As it turns out: just leaving out the ``BINDPW`` parameter in the ``POST /resolver/name`` request as suggested by @plettich already works :) If an existing resolver is updated, ``save_resolver`` in ``privacyidea.lib.resolver`` just updates its config with the given parameters, but keeps all the old values. The resolver config can be updated with an empty password by passing ``BINDPW=""``.

So I think we just need:
* a way to censor the BINDPW in the ``GET /resolver/`` response. Do we want to do this for all config values with the "password" type? This would probably affect other parts of the frontend too.
* a way for the frontend to detect changes to the password field, so it can decide whether to send the ``BINDPW`` parameter or not.

**Comment by cornelinux** [comment]
> a way to censor the BINDPW in the GET /resolver/ response. Do we want to do this for all config values with the "password" type? This would probably affect other parts of the frontend too.

If we censor the password, we simply know, that if the password is not the censored anymore (like censored would be empty or "CENSORED") then we see that it has changed. The UI could send the "CENSORED" password, but the Server would only update the password, if it is NOT CENSORED anymore. This would also help with testing. Then we could simply use the *old* password.

> a way for the frontend to detect changes to the password field, so it can decide whether to send the BINDPW parameter or not.

If we would use "CENSORED", then the frontend does not provide any logic!

But looks like we are turning in circles.
