### ISSUE TITLE
Bug: Enrolled token message showed for both admin content and user content.

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#1293]
# What did you try to do?

As an operator, navigate to:
Users > (Select a user) > Enroll New Token > HOTP > Enroll Token

# What outcome did you expect?

The enrolled message to be showed as:

The token was successfully enrolled with serial number <SN> for user <user> in realm portal.

# What outcome did you experience?

The actual enrolled message showed as:

The token was successfully enrolled with serial number <SN> for user <user> in realm portal. The token was successfully enrolled with serial number <SN>.

# Configuration

* privacyIDEA Version: 2.21.4

* Installation method: from source

## more details: 

* OS: Amazon Linux

* Webserver: nginx

* Tokendatabase: postgresql

===

Seems like there is a bug in privacyidea/static/components/token/views/token.enroll.html that cause the message for both admin case and user case to be showed.

It works correctly for enrollment as user, or enroll a token from Tokens menu instead of Users menu.

<img width="843" alt="screen shot 2018-10-29 at 4 13 10 pm" src="https://user-images.githubusercontent.com/23221438/47686033-5f955680-db96-11e8-8e2b-505a64b8c605.png">

**Comment by cornelinux** [comment]
Hi @quynh-axiadids 

This is the html part that gets doubled and should not be displayed:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.html#L135

I think the ``newUser.user`` is wrongly empty. I observed this before, that when enrolling a token from the userview, the UI lost the user information. Then ``newUser`` would be empty and also the second html part would be displayed.
But we also had this fixed in the meantime - this does not occur in the current version 2.23 anymore.

Could you please confirm this?
