### ISSUE TITLE
The Serverpool in LDAP resolver is not persistent

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1396]
The serverpool in the ldap resolver is not persistent but rather created on each ``checkPass``.

As far as normal quering is concerned, it is persistent if the bind is still active. Nevertheless we should move the serverpool into a member ``self.serverpool``.

**Comment by fredreichbier** [comment]
First idea was to make the serverpool global per-process. However, this doesn't really help, because ldap3 stores the server pool *state* separately for *each connection object*! So with two servers A and B we have the following problem: Even if connection 1 learns that server A is down and uses B instead, connection 2 does not have this information and might even try A again!

We *could* use the ldap3 REUSABLE strategy ([see here](https://ldap3.readthedocs.io/connection.html)), which keeps a connection pool, but it isn't well-documented and it is asynchronous, which means we would have to restructure the LDAP resolver code.

We could maybe write our own ServerPool implementation?

**Comment by fredreichbier** [comment]
Some ideas for an alternate ServerPool implementation:
* We could have a per-process server pool that holds the information which servers are online and which are offline. We would have to implement the server pool in a thread-safe manner.
* In order to check if a pool server is available, the ``ldap3.ServerPool`` opens and closes a TCP socket. This is often enough, but doesn't cover the case that a pool server accepts connections, but does not answer LDAP requests. Our alternate pool implementation could attempt a LDAP Bind with the service account credentials to also cover this case.

**Comment by fredreichbier** [comment]
Starting with ldap3 2.6, the ``ServerPool`` class now uses a single state instead of one state per connection connection (see https://github.com/cannatag/ldap3/issues/649). This enables us to implement a proper *per-process* server pool. So I'm reopening this and assigning it to 3.1

**Comment by fredreichbier** [comment]
I started working on a real per-process persistent server pool here: [1396/persistent-serverpool](https://github.com/privacyidea/privacyidea/tree/1396/persistent-serverpool).

With these changes, we now actually have one per-process server pool for each LDAP server pool configuration. This means that all threads of a process share the information on active and inactive servers. And the poll actually remembers now :) So if a server is inactive, it is not checked again until the number of seconds in the "skip timeout" is reached.

I configured a LDAP resolver that defines two servers of which one is not available. I then did a quick test with 100 requests (4 threads doing 25 requests):
* On current master, they take 78 seconds
* With the changes, they take 41 seconds

... which is quite nice :)
*
