### ISSUE TITLE
TOTP token time sync issues

### ISSUE THREAD

**Issue by mail2hemant** [privacyidea/privacyidea#1408]
Scenario:
1. Enrolled a TOTP token using 2-Step feature by scanning QR code using privacyIDEA authenticator app.
2. Validated 1st OTP generated by app successfully.
3. Collected 2nd and 3rd OTP, but didn't validate.
4. Validated 4th OTP successfully.
5. Tried validating 2nd and 3rd OTP - return false, as expected.
6. Collected 5th, 6th and 7th OTPs, but didn't validate.
7. Tried validating 5th OTP after 20 minutes- **it returns TRUE !! - This seems an issue,** because TOTP being time based token shouldn't validate after the time window.

Tested using SHA1, SHA-256 and SHA-512 algorithm, also played around with the TOTP token settings and sync settings by reducing or increasing the values.

**Comment by mail2hemant** [comment]
We have tested this scenario several times. 
Noted down 3 OTPs and found them to be valid after 3 minutes. 
Then noted down 3 more OTPs and found them valid after 20 minutes. 
Then the OTP generated at correct time also found to be valid. 

So in our experience, the time drift doesn't seem to be functioning either. Ideally the user would expect privacyIDEA to not validate old/unused OTP values for security reasons.

**Comment by cornelinux** [comment]
This sounds different than your original concern.

All this depends on your timedrift and the otpwindow, which defines, how long the system tries to look into the past and the future.

So it is totally normal, that an OTP value will be valid after three minutes, if it is not used before.
The timedrift will be set back.
Then these three noted OTP values will work.

Now you write down 3 OTP values. Which, after 20 minutes only have an offset of 17 minutes, since your token is already three minutes off. 

it very much depends on the otpwindow, if the otp value with the correct time will be validated (offset of 20 minutes in the opposite direction).

So to me this sounds it works as designed, as specified in the [RFC](https://tools.ietf.org/html/rfc6238#section-6). The only thing that might look odd, is, that the otpwindow seems a bit big with 20 minutes. Please note, that you can configure this one!

**Comment by plettich** [comment]
i tried to reproduce this behavior. In my case every first OTP failed, the time-shift was adjusted and the following two OTPs were accepted. After 20 minutes no OTP was accepted. Entering the first current OTP failed and the time-shift was adjusted again. After that, the current OTP value worked again.
This was tested with the default settings.

**Comment by cornelinux** [comment]
It is not clear to us, what the settings of the OP were. It seems he used different settings.
This can not be reproduced with default settings.
It is the expecated bahaviour with long time windows.
