### ISSUE TITLE
Policies could be dependent on any user attribute

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1436]
The conditions for a policy and event handler to apply could depend on any arbitrary user attribute (like a group membership)

See https://community.privacyidea.org/t/resolver-and-user-token-relation/941

**Comment by cornelinux** [comment]
Also the event handler conditions should be triggered via such user attributes.
The interesting thing is, that then there is no need to be depent on the resolver, since the resolver can very well also be such an attribute.

**Comment by cornelinux** [comment]
To be more flexible in policies we would need to untangle the policy-table, which currently contains

* The policy skeleton
   * the name
   * the scope
* all the conditions
  * user
  * time
  * client IP
  * active
* the action ("action")

We should probably split it up like the eventhandler.
THis way it would be much easier, to add new conditions for policies.
Split into the DB tables:

* Policy
* PolicyCondition
* PolicyAction (Already now a policy can contain several actions, comma separated - how nasty is that!)

**Comment by fredreichbier** [comment]
I think, conceptually, wouldn't it be cool if policy conditions and event handler conditions could have the same logic? In the end, they both match on some properties of the current request.

In terms of DB tables, I agree with your thoughts above: I think it would be more sensible to store the policy conditions and actions in their own tables.

... but this could potentially make policy queries a bit slower. I don't know :-)

**Comment by cornelinux** [comment]
As far as the speed is concerned: Currently the policies are fetched at the beginning of the request. This problably would not be changed. We then have a request wide policy object. (We can even keep the policy-object without rereading it from the database too often - I think we already do this)

Condition Handling: At the first glance it might look the same. But at a second it is rather different since the logic of how events are triggered and how policies are fetched (think of get_action_value) are different. So we need to take a third look! ;-)

**Comment by Marc-Axiad** [comment]
Hi Cornelinux, I think I am partly at the origin of the request, a customer wants to apply different policies to end users based on group membership (which can be translated indeed as a user attribute if looking at "memberof"). Currently we implemented this using resolvers but the problem comes when the customer move users from one group to another, users lose their device assignment. Anyway, if you have any questions about the customer use case please let me know!

**Comment by fredreichbier** [comment]
I still suspect that policy matching and event handler matching are very close to one another -- maybe we should try to unify the two concepts. This could help with several issues, e.g. #1102, #1645.

As a first step, I think it may be useful to split the policy table as @cornelinux suggested above (especially because performance isn't really a concern here, as you said).

**Comment by cornelinux** [comment]
Alt least as far as the conditions are concerned they are rather similar. So the definition and storing of conditions could be unified.

**Comment by fredreichbier** [comment]
I agree. We could split this in the following manageable steps:
1) Split off conditions from the policy table and create a new table ``PolicyCondition``. The migration script should be relatively easy. We don't need to change any higher-level policy code, we only need to adjust ``privacyidea.models``.
2) Split off actions from the policy table and create a new table ``PolicyAction``. Here, designing the table schema and writing the migration might be a bit messy because we have several different shapes of action values: we have action values which carry a list of values (e.g. ``tokentype=totp hotp motp``) and action values which carry a string (e.g. smstext=``your otp is <otp>``).
3) Implement matching of arbitrary attributes for policies. In fact, I think we don't really have to implement step 2 to do that.

**Comment by fredreichbier** [comment]
I experimented with splitting the policy conditions to a separate table a bit and pushed #1662 -- not sure if that's a good way :)

**Comment by fredreichbier** [comment]
Idea: We could keep the original Policy table as it is (with existing fields ``user``, ``realm``, ...), and only *add* a new PolicyCondition table for more complex conditions (analogously to the Token/TokenInfo tables).

**Comment by fredreichbier** [comment]
I changed this issue, which now only speaks of policies, and opened #1673 for the event handlers.

**Comment by fredreichbier** [comment]
With #1672, #1715, #1731 and #1742 merged, we finally have (nearly) everything we need to support policy conditions on arbitrary user attributes :)

There are still some things to do:
* User attributes can only be taken into account if the policy decorator function passes a user object to ``match_policies``/``get_action_values``. We do so at a lot of places now (see #1672), but there are some places missing. I'm working on that.
* We should have another look at the comparators:
  * Do we need anything else in addition to ``==`` and ``contains`` right now? @Mipronimo suggested negations in #1742. We could easily add them in a generic way (e.g. ``!X`` is the negated result of the comparator ``X``). Also, do we need something like ``in`` or ``matches regex``?
  * Should we rename ``==`` to ``equals``, as suggested by @Mipronimo  in #1742?

**Comment by fredreichbier** [comment]
Hi @Marc-Axiad, we are now nearly done with implementing this feature. However, the user attributes are only taken into account for a subset of policy actions. In order to ensure that the feature will work for your usecase, it would be helpful if you could tell us the policy actions for which you'd like to use this feature :)

**Comment by Marc-Axiad** [comment]
Thanks @fredreichbier ! Absolutely, in our specific case the scope of the policy is "user" the actions we want to filter are part of the action group "enrollment". The idea is that based on the group the user belongs to they will only be able to enroll certain types of tokens. This simplifies the user experience by only providing the applicable types of tokens based on the type of user.

**Comment by fredreichbier** [comment]
Thanks! That's good to know, because matching of user attributes doesn't work for the ``enrollX`` policy actions yet :-)
https://github.com/privacyidea/privacyidea/blob/680771497a1aceb8b56956d3bb808e661e972d52/privacyidea/api/lib/prepolicy.py#L1161
I'll check it this can be implemented.

**Comment by fredreichbier** [comment]
Hi @Marc-Axiad, with #1758 merged, I think the next release privacyIDEA 3.1 should support your usecase. Thank you for your input!

**Comment by cornelinux** [comment]
Code and Documentation is merged, so we close it.

**Comment by Marc-Axiad** [comment]
Thanks @fredreichbier and @cornelinux . Looking forward to testing this new feature!
