### ISSUE TITLE
multiple token types in detail

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea#1456]
If I do validate check, I get a token type (see #1370), but if I have multiple tokens, only the last added one appears there.
Wouldn't it be better to get an array of tokens?
Or maybe both, a string with all tokens and an array, like you've done it for the messages?

```JSON
"message": "Please confirm with your U2F token (U2F Device), Enter the OTP from the Email:",
"messages": [
      "Please confirm with your U2F token (U2F Device)",
      "Enter the OTP from the Email:"
 ],
```

**Comment by fredreichbier** [comment]
Hmm, what version are you on? For my privacyIDEA instance, this kind of works:
```json
{
    "detail": {
        "attributes": {
            "state": "15690046706553188632",
            "valid_until": "2019-02-20 11:55:13.433944"
        },
        "message": "please enter otp: , please enter otp: , Enter the OTP from the Email:",
        "messages": [
            "please enter otp: ",
            "please enter otp: ",
            "Enter the OTP from the Email:"
        ],
        "multi_challenge": [
            {
                "attributes": null,
                "message": "please enter otp: ",
                "serial": "OATH0002DB34",
                "transaction_id": "15690046706553188632",
                "type": "hotp"
            },
            {
                "attributes": null,
                "message": "please enter otp: ",
                "serial": "OATH00041727",
                "transaction_id": "15690046706553188632",
                "type": "hotp"
            },
            {
                "attributes": {
                    "state": "15690046706553188632",
                    "valid_until": "2019-02-20 11:55:13.433944"
                },
                "message": "Enter the OTP from the Email:",
                "serial": "PIEM000074D0",
                "transaction_id": "15690046706553188632",
                "type": "email"
            }
        ],
        "serial": "PIEM000074D0",
        "threadid": 140197544613248,
        "transaction_id": "15690046706553188632",
        "transaction_ids": [
            "15690046706553188632",
            "15690046706553188632",
            "15690046706553188632"
        ],
        "type": "email"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": false
    },
    "signature": "...",
    "time": 1550659993.434876,
    "version": "privacyIDEA 2.23.2",
    "versionnumber": "2.23.2"
}
```

... but then again, that's on master :-)

**Comment by Mipronimo** [comment]
> ```json
>         "type": "email"
> ```

This is also not an array, I think it could be useful, if you do it like it is done below.
I don't know, if it is necessary, but it is done for the messages in the same way, so we could it do for the tokens as well.


```JSON
{
    "detail": {
        "attributes": {
            "state": "15690046706553188632",
            "valid_until": "2019-02-20 11:55:13.433944"
        },
        "message": "please enter otp: , please enter otp: , Enter the OTP from the Email:",
        "messages": [
            "please enter otp: ",
            "please enter otp: ",
            "Enter the OTP from the Email:"
        ],
        "multi_challenge": [
            {
                "attributes": null,
                "message": "please enter otp: ",
                "serial": "OATH0002DB34",
                "transaction_id": "15690046706553188632",
                "type": "hotp"
            },
            {
                "attributes": null,
                "message": "please enter otp: ",
                "serial": "OATH00041727",
                "transaction_id": "15690046706553188632",
                "type": "hotp"
            },
            {
                "attributes": {
                    "state": "15690046706553188632",
                    "valid_until": "2019-02-20 11:55:13.433944"
                },
                "message": "Enter the OTP from the Email:",
                "serial": "PIEM000074D0",
                "transaction_id": "15690046706553188632",
                "type": "email"
            }
        ],
        "serial": "PIEM000074D0",
        "threadid": 140197544613248,
        "transaction_id": "15690046706553188632",
        "transaction_ids": [
            "15690046706553188632",
            "15690046706553188632",
            "15690046706553188632"
        ],
        "type": "hotp, hotp, email",
        "types": [
                "hotp",
                "hotp",
                "email"
        ]
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": false
    },
    "signature": "...",
    "time": 1550659993.434876,
    "version": "privacyIDEA 2.23.2",
    "versionnumber": "2.23.2"
}
```

**Comment by cornelinux** [comment]
The thing is the "types" would only be relevant in case of a challenge response. In all other cases it makes sense, that there is only 

    "type": "email"

since this would be the token, that actually successfully authenticated.

Also from the location in the json object. 

I very much would refrain from doing a 

    "type": "hotp, hotp, email"

Well, we could do in additiona a

    "types": ["hotp", "hotp", "email"]

but this information is already contained in the multichallenge!

So should we simply add a "detail"->"types" for easier parsing?

**Comment by fredreichbier** [comment]
Ah, I get it now :) I agree that ``"type": "hotp, hotp, email"`` would not be very nice, but I'm wondering: If multiple token match (like in the snippet @Mipronimo posted above), isn't the value of ``"type"`` currently just the type of the last token that was processed? This would not be optimal, because the order of tokens isn't really well-defined.

We could add a ``"types"`` key, similarly to ``"messages"``, but I'm not sure if we should do that, considering that the information is already contained in the ``multi_challenge`` part of the response, as @cornelinux said?

**Comment by cornelinux** [comment]
@fredreichbier You are right, the information is available. But I think it is just a matter of readability --- @Mipronimo correct me, if I am wrong.

In the case of multiple challenge response the ``"type"`` contains the last tokentype. right. But I am hesitant to change this
1. The information is not used in challenge/response anyways
2. I would like to keep the code simple, so this would be simply a side effect.

**Comment by Mipronimo** [comment]
We can leave it as it is, I just wonder, why we list the attributes in different ways.
Why do we have the message and transaction id twice but the type only once?

But for me it doesn't matter anymore. I started to use the values from multi_challenge (;

**Comment by fredreichbier** [comment]
Haha, good point, this is quite inconsistent :-) I think the reasons are just historical -- I guess using multi_challenge is more future-proof anyway.

... so I guess we can close this? @cornelinux what do you think?

**Comment by cornelinux** [comment]
It is historical.
In theory the "type" could even be removed from the top level, since it contains the type of the token, that was used for authentication.
So you could argue, that the challenge response is no successful authentication and thus should contain no type. (while it may contain a type in the multi_challenges).

The original idea of the type was, that an application could decide based on the type, if a user should get certain rights (like authorization).
"Ok, the user successfully authentication, but since he only authenticated with an SMS token, he gets the right to read the data, but not to wipe the whole harddisk".

It has no other technical meaning.
I close it. THanks for bringing up the discussion. Maybe we even might need to refactor the responses one day, but not without change the API version number.
