### ISSUE TITLE
WebAuthN Token (a.k.a. FIDO2)

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1468]
Support the enrollment of WebAuthN tokens.

The concept is rather similar to U2F - maybe we can inherit it.
The Enrollment works via Javascript in the browser.
It is an assymmetric key pair and challenge response token.

Enrollment is via:

~~~~javascript
    navigator.credentials.create({ publickkey: { ...options... });
~~~~

Currently it is not clear, how authentication would work, since there does not seem be a concet of trusted facets. Thus authentication would only make sense e.g. against a simpleSAMLphp running on the same machine.

**Comment by restena-sw** [comment]
I volunteer for testing a possible simpleSAMLphp plugin in combination with the backend that is to be developed in privacyIDEA's main code.

**Comment by cornelinux** [comment]
> I volunteer for testing a possible simpleSAMLphp plugin in combination with the backend that is to be developed in privacyIDEA's main code.

@restena-sw  In the first step we will add the enrollment to privacyidea and probably the authentication at the privacyIDEA UI. So it would be great if you would also test this (or even participate), since simpleSAML will only come in a later step.

**Comment by mrvanes** [comment]
I have a proof of concept ssphp authproc that forces webauthn in the auth flow, maybe it helps getting inspiration from? https://github.com/mrvanes/authWebauthn

**Comment by restena-sw** [comment]
simpleSAMLphp meanwhile has its own module for FIDO2 (also as authprocfilter): https://github.com/simplesamlphp/simplesamlphp-module-webauthn/ (of which I am the main author)
This works independently of a privacyidea server, so this entire issue here is somewhat OBE.

**Comment by mrvanes** [comment]
Ah, that's what's been worked on during the Nordic hackathon last week? :)

**Comment by restena-sw** [comment]
Yes, that was integration and code cleanup work to make my code fit for wider usage, by the good "core" simpleSAMLphp people.

**Comment by cornelinux** [comment]
> This works independently of a privacyidea server, so this entire issue here is somewhat OBE.

This is not true. The issue is ment for adding FIDO2 management to privacyIDEA not only to support it with simpleSAMLphp, as privacyIDEA has a much wider scope than SAML and ssphp. But thanks a lot for the information on this.

**Comment by cornelinux** [comment]
We still need to check, where the functionality of "trusted facets (U2F)" in FIDO2 is.
This might be called "Manifest"?

**Comment by mrvanes** [comment]
OpenSSH made the first steps into supporting U2F token on the commandline using libfido2 as the middleware layer for registration of private/public keypair.

https://lists.mindrot.org/pipermail/openssh-unix-dev/2019-November/037999.html

Beware that in this scenario, ssh-keygen has the liberty to _choose_ the application identifier (default is ```ssh:```) but in Javascript WebAuthn API you don't. The application identifier will be forced to the domain of the URL requesting the registration call, in order to prevent fishing attacks. It is extremely important to realise this if the 2nd factor is to be used on domains other than where it's registered (e.g. PrivacyIDEA portal vs custom user webinterface).

**Comment by mrvanes** [comment]
Serving a privacyIDEA portal served iframe for the token registration won't work. cross-domain webauthn registration calls are forbidden: https://webauthn.bin.coffee/

**Comment by NuvandaPV** [comment]
There is an extension to allow using AppIDs. This is however just meant to provide backwards compatibility for credentials created with the legacy api: https://w3c.github.io/webauthn/#sctn-appid-extension

Here is the FIDO2 draft for AppIDs: https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-appid-and-facets-v2.0-id-20180227.html

However it turns out we will not need this, as the RP ID is allowed to be a “registerable domain suffix [...] of the caller's origin's effective domain”, which is flexible enough for our use-case.

Since WebAuthN is significantly more complex than the original standard, we will rely on a third-party library to implement some of the server-side functionality for now. To maximize security and reliability, we may replace this with an in-house solution down the road.
