### ISSUE TITLE
Allow push token to delay the response

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1583]
When authenticating with a push token, the response of the API request to ``validate/check`` is directly returned - for good reasons.
Applications then should [poll for the confirmation of the push token](https://github.com/privacyidea/privacyidea/wiki/concept%3A-PushToken#polling-endpoint-for-application).
Although this is a cleaner design, we can offer an alternative.

The response of the ``validate/check`` request is held back until the push token was confirmed.

Some problems: If the user has several tokens, how should we react:
1. another token successfully authenticated: return directly?
2. all other tokens failed to authenticate: wait?

We need at least the following settings:
1. activate this behaviour
2. timeout, how long privacyIDEA should wait for an answer of the push token

**Comment by fredreichbier** [comment]
Sounds handy! However, we should keep in mind that simply delaying the response will block a worker thread, which won't be able to handle other requests in the meantime. In a productive environment, it could happen that privacyIDEA becomes unresponsive for some time because all worker threads are waiting for a push token response.

**Comment by cornelinux** [comment]
Friedrich suggests an implementation with a polling twisted proxy server.
