### ISSUE TITLE
Registration token validity not working

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#1587]
# What did you try to do?

Using Registration token with validity period

# What outcome did you expect?

Registration token that is outside of validity period should not work.

# What outcome did you experience?

Registration token that is outside of validity period is still successfully authenticated.

# Configuration

* privacyIDEA Version: 2.23.5

* Installation method:
 from source

## more details: 

* OS: Amazon Linux

* Webserver: Nginx

* Tokendatabase: PostgreSQL

# Note:
I suspect that because in privacyidea/lib/token.py method `check_token_list` we delete the token during the `inc_count_auth_success()` before the `check_all()`, resulting in the incorrect behavior mentioned in this ticket.

```
        # One ore more successfully authenticating tokens found
        # We need to return success
        message_list = ["matching {0:d} tokens".format(len(valid_token_list))]
        # write serial numbers or something to audit log
        for token_obj in valid_token_list:
            if increase_auth_counters:
                token_obj.inc_count_auth_success()
            # Check if the max auth is succeeded
            if token_obj.check_all(message_list):
```

I think this will be a security issue, and would like to ask if we can enhance the logic? If not maybe I can use event handler to handle this issue?

Best regards,

Quynh Nguyen

**Comment by fredreichbier** [comment]
Hi Quynh, thank you for the bug report! I reproduced this issue locally, and your analysis is correct: 

In order to check if a token is still valid, ``check_all()`` fetches the token's token info from the database and looks for the ``validity_period_end`` info. But because ``inc_count_auth_success()`` has already deleted the registration token, the resulting token info is empty, so the validity period is not checked. 

I would consider this a bug, but I'm not yet sure what would be the cleanest way to fix it.

I think this issue affects the validity period checks and the ``count_auth_max`` check. As far as I can see, authentication does fail for inactive tokens and for tokens whose failcounter has been exceeded, because both information are cached locally even though the database object has been deleted in the meantime. 

Since WebUI logins are handled by the ``/auth`` endpoint which currently misses an event handler (this will be fixed by #1567), I don't think we can mitigate this issue with an event handler. :-/

But it can be partially mitigated using the token janitor: One could periodically disable all active registration tokens whose ``validity_period_end`` lies in the past:

```shell
privacyidea-token-janitor find --tokentype registration --tokeninfo-key validity_period_end --tokeninfo-value-before $(date -Isecond) --active True --action disable
```

... or even delete them by changing ``--action disable`` to ``--action delete``.

**Comment by cornelinux** [comment]
The problem is that we have a conflicting logic.

The current implementation works this way:

1. The token is checked if it authenticates successfully.
2. The inc_count_auth_success() is called.
3. Then the validity of the token is checked.

This makes absoluetly sense e.g. for HOTP tokens. Imaginge an HOTP token, that is currently invalid. But a valid OTP value was used for authentication. Then this very used OTP value needs to be invalidated, which is done by the *authentication* and the *inc_count_auth_success*.
Otherwise an attacker could reuse this OTP value *later*, when the token is activated again.
THis is the reason, the disablement and the validity period is checked at the end! We should not change this.

However, I think the registration token is deleted "to early". So maybe an alternative would be to delete the registration token later.
So we should not delete the token here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2164
but somewhere here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2175

**Comment by quynh-axiadids** [comment]
@cornelinux @fredreichbier Thank you for fixing the bug!
Since we are still not upgraded to 3.0. Here is my quick fix locally:
```
--- a/privacyidea/lib/tokens/registrationtoken.py
+++ b/privacyidea/lib/tokens/registrationtoken.py
@@ -157,7 +157,8 @@ class RegistrationTokenClass(PasswordTokenClass):
         Increase the counter, that counts successful authentications
         In case of successful authentication the token does needs to be deleted.
         """
-        self.delete_token()
+        if self.check_all([]):
+            self.delete_token()
         return 1

     @log_with(log)
```

This work around is working fine for me:
```
[...]
"detail": {
  "message": "matching 1 tokens, Outside validity period",
  "otplen": 24,
  "serial": "REG0000A94C",
  "threadid": 140209335916672,
  "type": "registration"
},
[...]
```

Just want to let you guys know!

**Comment by cornelinux** [comment]
Give us a note, when you plan to upgrade. Upgrade will probably a bit challenging, since we migrate the user assignment. This can take a few minutes with a large user number. I also recommend testing it on a cloned test system. We did not experience any problems, but we can not rule out, that there could be corner cases where the migration of a user might fail.
We will release the enterprise edition shortly.
