### ISSUE TITLE
Email notification for token_delete is not filling in details 

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea#1590]
# What did you try to do?

Created pre-Event Handler for token_delete to be emailed.

Subject:  
>Token {serial} deleted!

Body: 
>Token Realm: {userrealm}
>Token Type: {tokentype}
>Token Serial: {serial}
>Admin User: {admin}
>Admin IP: {client_ip}
>Time of Action: {date} {time}

# What outcome did you expect?

**Email notification with the following:**

Subject:
> Token PIPU00001234 deleted!

Body:
>Token Realm: pirealm
>Token Type: push
>Token Serial: PIPU00001234
>Admin User: admin
>Admin IP: 127.0.0.1
>Time of Action: 2019-04-23 20:14:00

# What outcome did you experience?

**Email notification with the following:**

Subject:
> (blank)

Body:
>Token Realm: 
>Token Type: None
>Token Serial: (list of every token in the system)
>Admin User: admin
>Admin IP: 127.0.0.1
>Time of Action: 2019-04-23 20:14:00

# Configuration

* privacyIDEA Version: 3.0
* Installation method: ubuntu packages

## more details: 

* OS: Ubuntu 16.04LTS
* Webserver: Apache
* Tokendatabase: MySQL

**Comment by fredreichbier** [comment]
Thanks for the bug report! I reproduced the issue locally. It occurs because the event handler tries to obtain the token serial from the request data:
https://github.com/privacyidea/privacyidea/blob/5e43b23f40cbf304a6246d05589fe3f4d1b280b7/privacyidea/lib/eventhandler/base.py#L324
However, for ``token_delete`` actions, the serial is not contained in ``request.all_data`` because it is part of the URL (e.g. ``DELETE /token/OATH000201D6``).
I'm not yet sure about the best way to fix this in a generic fashion.

**Comment by droobah** [comment]
Would it be a good or bad idea to inject the serial into the request from within api/token.py?

**Comment by cornelinux** [comment]
Thanks a lot for the suggestion.
This could only work for post-handlers.
A pre handler would not be executed _before_ the code in api/token.py.

**Comment by cornelinux** [comment]
We reworked the handling of the serial numbers in a lot of requests.
Latest tests (version 3.5) show, that this works now.
