### ISSUE TITLE
Check callers of match_policies and get_action_values

### ISSUE THREAD

**Issue by fredreichbier** [privacyidea/privacyidea#1691]
In #1672 (last comment), we clarified and documented the meaning of parameters for ``match_policies`` and ``get_action_values``. We should now ensure that all calling locations of these methods actually pass the parameters correctly (i.e. if they pass ``resolver=None``, they really don't care about the resolver).

**Comment by cornelinux** [comment]
Hi @fredreichbier I guess you know what to do? ;-)

**Comment by fredreichbier** [comment]
I think in the medium run, we should refactor our policy matching routines a bit. #1757 contains a first idea. However, as this is quite a big change, I would suggest we do this after 3.1?

**Comment by fredreichbier** [comment]
Refactoring policy matching sounds nice, but we'll do it in 3.2 at the earliest.

**Comment by cornelinux** [comment]
We should also consider the following in this issue:

In certain cases we only have a serial number in the request but we would also have to match for realm and resolver. Imagine an administrator who has a policy that allows the admin to unassign tokens in ``realmA`` in ``resolver2``. We can define such an admin policy.

But the endpoint ``/token/unassign?serial=<serial>`` is called from the webui.
The check_base_action decorator (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L438) thus only received the serial number, since the [request.User](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py#L450) is None.

So we either need to add the tokenowner in such cases or we should add the ``request.User`` in general if an API endpoint only contains  the serial.

**Comment by fredreichbier** [comment]
This is an interesting point! I think in case of unassigning a token, i.e. when the ``check_base_action`` function only receives a serial and no realm or resolver, the function actually fetches the first token realm and uses it for policy matching:

https://github.com/privacyidea/privacyidea/blob/f1543ced95df9dd7214dbd2499e3f57bd3990f98/privacyidea/api/lib/prepolicy.py#L1092

... but ``resolver`` is still None.

I'm currently not sure how this should behave. Should we set ``resolver`` to the tokenowner's resolver? Or should we also account for the future in which one token might have multiple tokenowners?

**Comment by cornelinux** [comment]
Also take into consideration the changes in PR #1870
