### ISSUE TITLE
Allow additional checks while answering challenge response

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1695]
During a challenge response the user can sends possible responses to privacyIDEA. 
These get checked against the challenge table.

The tokentype should define, which checks are performed in addition to checking if the challenge matches and is still valid.

The tokenclass can define a method ``check_challenge_response()`` which would be added in this if-statement.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2213

Within this method a tokenclass could call the existing check_failcount or run additional checks depending on the tokentype. The challenge table also counts the response tries, so this could be checked as well.

A certificate or smartcard token in the future could also use this hook to pull CRLs...

**Comment by fredreichbier** [comment]
Turns out we already a ``check_challenge_response()`` in TokenClass, it's used a few lines above :)
https://github.com/privacyidea/privacyidea/blob/ead5e1fda80ceee55cf1cbdcfe72d8b8e61949a3/privacyidea/lib/token.py#L2209
... but this method checks if the given response matches *any* valid challenge for the token. We could add a method ``check_challenge_response_appropriate`` which implements tokenclass-specific checks if a given challenge response should be considered "appropriate", with regard to the criteria you mentioned above?

**Comment by cornelinux** [comment]
``check_challenge_response`` simply checks the answer to the challenge on a cryptographic basis and challenge-basis. It does not yet check any token-object-specific things.

I do not understand your comment. It does need to check *any* challenge with the correct transaction_id (which is passed in the options). And it does this right ????
