### ISSUE TITLE
Disabled failcounter increases

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea#1711]
The failcounter of disabled tokens increases, if the user tries to login.
I think we should check if the token is enabled or disabled.

**Comment by cornelinux** [comment]
I think this is a good idea and this is probalby by design.

You can already distinguish between increasing failcounters on false pin or not. I.e. there is an intention (on false pin) to increase all failcounters of a user.

What is the fail counter for? It is for avoiding brute force attacks on the user or the users token.
If the admin decides to increase_fail_counter_on_false_pin, then he is eager to block all tokens, if an attack occurs.
Why exclude disabled tokens? This makes not sense to me.
