### ISSUE TITLE
Setting "auth_max_fail" policy param for /auth authentication 

### ISSUE THREAD

**Issue by Voyrx** [privacyidea/privacyidea#1722]
Hello,

I am using privacyIDEA to do TOTP authentication through "/auth" URI (to get authentication token). 

I would like to benefit from "auth_max_fail" policy parameter (scope authorization) to limit maximum fail authentication per time period. 
Thing is, this policy parameter is triggered while using "/validate" URI. 

Is there a way to force privacyIDEA to use this paramater with "/auth" URI? 
Or perhaps, could I use "/validate" and configure privacyIDEA to get the authentication token with URI? 

Thank you.

Regards,

**Comment by cornelinux** [comment]
This is obviously a special case of the issue #1537 
We are aware of this but haven't start working on it.

How and why do you need the authorization token?

**Comment by Voyrx** [comment]
Hello,

Thank you for your quick answer.

I need it because after that I use /token/init to enroll a new token.

Regards,

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by fredreichbier** [comment]
The action "auth_max_fail" is implemented on the lib level by the policy decorator function ``auth_user_timelimit``. As it turns out, this function is already called for the ``/auth`` endpoint!

But in order to check the number of failed authentications during the specified timeframe, the function searches the audit log for ``/validate/check`` entries:

https://github.com/privacyidea/privacyidea/blob/8f5f09ffc62349e64ca960bdef261a2c3423fc54/privacyidea/lib/policydecorators.py#L416

... which of course does not include the failed authentication attempts for the ``/auth`` endpoint.

I'm not entirely sure how to fix this:
* Maybe we should *always* search for ``/validate/check`` *and* ``/auth`` entries and sum them up? But then, users would be denied at the ``/auth`` endpoint if they reached the maximum number of fails at the ``/validate/check`` endpoint, even if ``login_mode=privacyidea`` is *not* set
* Maybe we should search only for the respective endpoint? i.e. ``/validate/check`` searches for ``/validate/check``, ``/auth`` searches for ``/auth``. But then, users may be granted a greater number of fails if they try at both endpoints
* Maybe we should only search for ``/auth`` if ``login_mode=privacyIDEA`` is set?

**Comment by fredreichbier** [comment]
I started implementing option 2) above, and it works pretty well for logins with role ``user``.

However, if we also want ``auth_max_fail`` to take effect for external admins, it gets a bit tricky:
Currently, in order to figure out the number of failed authentication attempts, ``auth_user_timelimit`` searches the audit log for entries with ``user``/``realm`` being the current user object's username and realm. But if an external admin tries to authenticate, the admin's username is not written to the ``user`` field, but to the ``administrator`` field! So if an external admin tries to authenticate, we need to take a look at the ``administrator`` field instead of the ``user`` field -- otherwise, we will miss unsuccessful authentication attempts.

**Comment by fredreichbier** [comment]
We'll need to work on the feature specification a bit before implementing this: Should this policy only take effect in case of ``loginmode=privacyIDEA``? Should the policy take effect for both ``/auth`` and ``/validate/check``, or should there be a way to differentiate the two endpoints in the policy definition? (possibly using a policy condition?)

Hence, moving this to 3.2.

**Comment by fredreichbier** [comment]
If we define an ``auth_max_fail`` policy, it should take effect for both ``/validate/check``, and also for ``/auth`` if ``loginmode=privacyIDEA`` is defined.

**Comment by cornelinux** [comment]
the login mode could have changed over time. Or the loginmode could be different for differetn users.
So it could be the we somehow need to save additional information to the auditlog in case of ``/auth`` like the *loginmode* or more sensible the *tokentype* if the loginmode was set to privacyidea.

**Comment by fredreichbier** [comment]
I think when using ``loginmode=privacyIDEA``, ``/auth`` already writes the ``serial`` to the audit log. Maybe this information would already suffice to determine if the user authenticated against privacyIDEA?

**Comment by cornelinux** [comment]
But if the authentication fails, no serial is written to the audit log!
So we are missing the information, if this /auth request should count for auth_max_fail, right?

**Comment by fredreichbier** [comment]
Heh. :) It seems we get the serial *sometimes* for failing auth requests, e.g. if the user has exactly one HOTP token, provides the correct OTP PIN but an incorrect OTP value. But you're right, if the user provides an incorrect OTP PIN, no serial is written to the audit log. But such authentication attempts should count for auth_max_fail, so the serial entry in the audit log is not sufficient for counting authentications.

**Comment by cornelinux** [comment]
A failed auth request provides the serial if the user either only has one token or if the user specifies the correct OTP PIN for a token but a wrong OTP value. But we can not know this. If a user fails with everything and the user has several tokens, then there is no serial in the audit log, right.
So I would really like some additional info, if this /auth request was issued against privacyIDEA. And this then would be crystal clear ;-)

**Comment by cornelinux** [comment]
This will be fixed with #1537

**Comment by Voyrx** [comment]
Thank you for your great work ! :)
