### ISSUE TITLE
TiQR token fails if user has multiple tokens

### ISSUE THREAD

**Issue by Mipronimo** [privacyidea/privacyidea#1739]
If a user has multiple challenge response token (e.g. TiQR and PUSH) he gets a QR-Code to scan. After entering the PIN in the TiQR app, a message like "Challenge not valid" appears.
If the user does not have other tokens, everything works as expected. The user will be successfully authenticated.

**Comment by fredreichbier** [comment]
I haven't tested this, but I believe the culprit is this check here:
https://github.com/privacyidea/privacyidea/blob/b7fe9ae20cdba41d8c4de1259f204fe4c3ae839d/privacyidea/lib/tokens/tiqrtoken.py#L325

This assumes that the transaction ID is unique, i.e. for any transaction ID, there is at most one challenge with this transaction ID. But is assumption isn't true (see #1355): If we have multiple challenge response tokens, we get several challenges with the same transaction ID.

As a fix, we should check each challenge with the given transaction ID.

**Comment by skug67** [comment]
I think there may be a similar issue still lurking in the push token code, although I'm not sure.  When using Keycloak and the Keycloak-PrivacyIdea connector (https://github.com/privacyidea/keycloak-provider) I can successfully validate a user with multiple push tokens by confirming on only one device.  But if when accessing via the ldap-proxy mechanism, it requires both push tokens (always in the sequence in which they were added to the user account) in order for the login to be successful.
