### ISSUE TITLE
User TIQR enroll page

### ISSUE THREAD

**Issue by basvandervlies** [privacyidea/privacyidea#1789]
**Is your feature request related to a problem? Please describe.**
Not to bother the user with this message:
```
For TiQR tokens to work properly you need to set the:
TIQR Token Config (URL)
```
The user can not click on URL link and it is confusing the user.

**Describe the solution you'd like**
Only the help message nothing about how to config TIQR

**Describe alternatives you've considered**
Tried to delete the lines, but then I can not enroll the ticket anymore

**Additional context**
See screenshot
![tiqr](https://user-images.githubusercontent.com/431367/63081474-fb385d80-bf43-11e9-989b-8d6bca584234.png)

**Comment by fredreichbier** [comment]
I was wondering why the message is displayed even if the TiQR token is configured. The reason is that the ``GET /system/`` endpoint only returns the ``tiqr.regServer`` config option for admins, not for users. So if a user is logged in, the view does not see the ``tiqr.regServer`` option and assumes the TiQR config is incomplete.
We could either make the ``tiqr.regServer`` setting public (its value is contained in the QR code anyway), or modify the view such that it only displays the warning for admins.

**Comment by basvandervlies** [comment]
@fredreichbier I also found it strange that the mesage was displayed for the User.   The solution to only enable it for admin is the best one.  I do not know if you want to publish your `tiqr.regServer` for all users or is this only accessible for authenticated users?

**Comment by cornelinux** [comment]
I think these messages should not be displayed to the normal user in the first place!
A normal user could not configure the system anyways. So we should not bother them, that the admins have messed up! ;-)

So: Lets remove all those messages during token enrollment.

**Comment by basvandervlies** [comment]
@cornelinux I totally agree ;-) 

I have removed the message but we need somehow execute the code to enroll the token:
 * `<div ng-hide="config.tokens({tokentype:'tiqr'})" class="ng-hide"> </div>` 

If I am correct, but I am not am expert in this area.

**Comment by cornelinux** [comment]
> @cornelinux I totally agree ;-)
> 
> I have removed the message but we need somehow execute the code to enroll the token:
> 
> * `<div ng-hide="config.tokens({tokentype:'tiqr'})" class="ng-hide"> </div>`
> 
> If I am correct, but I am not am expert in this area.

This has to be user-role-dependent.
