### ISSUE TITLE
Make splitAtSign consistent

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1808]
The behaviour of ``splitAtSign`` is not consistent between the endpoint /validate/check and /auth.
We should adapt the endpoint /auth this way, that it behaves in the same was as the endpoint /validate/check.

**Comment by plettich** [comment]
So this is a tricky one since the `/auth` and `/validate/check` endpoints handle the user information differently. While the `/auth` endpoint handles the user information [in one point](https://github.com/privacyidea/privacyidea/blob/a2bac9b3089a3a78be71b60430730870a0c3a211/privacyidea/api/auth.py#L188), the `/validate/check` uses several policies to set and mangle realms.
In this issue we concentrate on the differences between `/auth` and `/validate/check` regarding the `splitAtSign` configuration. In the long run we should define more strictly how we handle certain situations.

Currently the `/auth` endpoint does not respect the `splitAtSign` configuration and tries to resolve the user in a wrong realm in certain situations.

**Comment by plettich** [comment]
The difference between the `/auth` and the `/validate/check` endpoint are shown here:
![auth_vs_validate](https://user-images.githubusercontent.com/37443810/67573982-ddecf000-f739-11e9-83c7-998a5b445456.png)
