### ISSUE TITLE
Better destinction between username and admin-username in policies

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1867]
In the policy implementation for version 3.2 is a logical error in the method get_action_values.

It does not allow to pass "user_object" and "user" at the same time. And this is wrong for admin policies.
Admin policies can contain the username of the administrator in the "user" field.
So with ``scope=admin`` we need to be able to pass the username of the admin!

We might also add a new parameter like "adminuser".

@fredreichbier we need to discuss and clarify.

**Comment by fredreichbier** [comment]
Yes, it's currently not possible to pass both ``user`` and ``user_object``, which e.g. means it's not possible to specify userinfo policy conditions for scope=admin policies.

But I'd say this is rather "not implemented" than a logical error :-) Because like you wrote, we'll first need to clarify which policy attributes should matched against which information:

For a scope=admin policy, should we match the policy attribute ``user`` against the administrator name, and ``resolver`` and ``realm`` and the userinfo conditions against the actual user object?

Maybe #1757 could help to implement a uniform behavior.

**Comment by cornelinux** [comment]
> For a scope=admin policy, should we match the policy attribute user against the administrator name, and resolver and realm and the userinfo conditions against the actual user object?

This is the way it currently works

**Comment by fredreichbier** [comment]
> > For a scope=admin policy, should we match the policy attribute user against the administrator name, and resolver and realm and the userinfo conditions against the actual user object?
> 
> This is the way it currently works

This is the way it currently works for administrator name, resolver and realm. The userinfo conditions currently cannot be matched for scope=ADMIN policies.

Thinking about it: Instead of conflating the admin name and username into one policy attribute, I think it would make more sense to have two distinct policy attributes ``adminuser`` and ``user``. This way, it would be no problem to pass a ``adminuser`` as well as a ``user_object`` for scope=ADMIN policies. Is this what you meant with _We might also add a new parameter like "adminuser"._ above?

IMO this should be relatively easy, we would just need to add a ``adminuser`` field to the ``Policy`` table and write a migration script that handles the migration of existing admin policie.s What do you think?

**Comment by cornelinux** [comment]
*easy*?

Is it as easy as fetching all policy of ``scope=admin``  and moving the entry from ``user`` to ``adminuser``.

The result would be very destinct. But if it fails, it blows up. 
But maybe it is the most sensible way to do it.

**Comment by fredreichbier** [comment]
> _easy_?

Well, maybe not _easy_ easy, but easy in comparison to some more complicated migrations that we did :)

> (Acutally I think noone ever used to `user` for users in a policy- except in scope=admin!)

Hm yes, probably not. But having two separate fields may even make the code more understandable -- may be worth a try :)

**Comment by cornelinux** [comment]
OK, I am doing the following:

* [ ] add a field "adminuser" to the table "policy"
* [ ] add the parameter "adminuser" to the library level
* [ ] add adminuser in policy.match
* [ ] add adminuser in webui

**Comment by cornelinux** [comment]
The result after having the ``username`` of the user also in the scope ``admin`` is, that admin policies now also allow for user attribute matching.
