### ISSUE TITLE
fix migration scripts, so that they will always run and not fail

### ISSUE THREAD

**Issue by INuvanda** [privacyidea/privacyidea#1875]
When a user creates a fresh database by running `$ pi-manage createdb`, the database will not be automatically stamped, leading to breakage, when the user tries to run the outstanding migrations later.

**Comment by NuvandaPV** [comment]
I have opened this issue, because I observed breakage with an installation of PrivacyIDEA running against mariadb. It was not possible to run `pi-manage db upgrade`, since in lieu of a stamp, it would apparently run very old migrations, trying to access tables, that have long since ceased to exist (such as `Token`, with a capital T).

So if I am not mistaken, a development setup, created in the way we outline in the top-level README will randomly break at some point, with no real way to fix it, since the database needs a migration, but running the migration is impossible, since the db is not stamped with its current version. If architectural limitations keep us from having the database stamped automatically when created from pi-manage, I think we should at least make clear in the documentation, that the user needs to run `pi-manage db stamp` in Order to keep their development setup from breaking during updates.

**Comment by cornelinux** [comment]
Can you please provide information about your system/setup (OS/distribution, DB and version) and the way you installed it? Which version of privacyIDEA?
Please provide the commands you issued and the complete output.
Please also provide the link to the documentation you followed.

Mariadb works - at least it did for four years. So my suspecion is, that this is a misunerstanding and I want to find out, where this comes from, if you simply missed some docs or if there is wrong or unprecise documentation.

**Comment by cornelinux** [comment]
As it is a feature, that the db is not stamped, i remove the "know issue" tag.

**Comment by NuvandaPV** [comment]
I am setting up a VM right now, to see if I can reproduce this behavior on a clean system. Let's talk about this in person on Friday, that'll be quicker than writing back and forth.

**Comment by cornelinux** [comment]
@NuvandaPV  There is a *tool* privacyidea-schema-update, that updates the privacyidea virtualenv and also can run a schema update. Please check, if this tool can be also used to initially stamp the DB.
...and then add the script to the install documentation.

@plettich  Also check, if there are now any error if we run from the first stamped version.

**Comment by NuvandaPV** [comment]
ToDo:
- [ ] Mention requirement for manual stamping to documentation
- [ ] Add try-accept to first migration script

**Comment by plettich** [comment]
We usually use the [`privacyidea-schema-upgrade`](https://github.com/privacyidea/privacyidea/blob/master/tools/privacyidea-schema-upgrade) script which stamps the db to the first version (`4f32a4e1bf33`) thus the migration script for the first version was never executed during an upgrade and we never saw these errors. They only appear when the db isn't stamped at all.

**Comment by plettich** [comment]
I am reopening this issue since we have a few more information:
- other databases fail as well -> #2618 
- we can change the `createdb` command: https://github.com/privacyidea/privacyidea/blob/9da257537097843005ada5af56de2bc2861b1abb/pi-manage#L562
  But we should check if stamping the database from within `pi-manage` works
- we might need to distinguish between a pip installation and a version running from the git checkout.

**Comment by plettich** [comment]
We fixed this in d8caa3c2
