### ISSUE TITLE
SSL Validity Check

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1896]
Could we check the runtime of an SSL certificate and use the notification handle to warn the admin?

When privacyIDEA communicates to an LDAPS we could *warn* the admin, if the certificate expires in a few weeks.
Or we could warn the admin, if the SSL cert of privacyIDEA itself is about to expire.

What should we monitor in the first step, e.g. with sconnect:

* [ ] WebUI / apache
* [ ] LDAP resolvers if they are using TLS
* [ ] database connection
* [ ] (other less important things)

The most robust an simplest thing would be to have a script with cronjob on each node.

**Comment by plettich** [comment]
Can we access the SSL-Cert of privacyIDEA? I think the webserver handles the SSL-Stuff..

**Comment by cornelinux** [comment]
Not from within privacyIDEA. The webserver cert could be accessed by an external script.

But we have access to the cert of the LDAP server and to the CA cert, that singed the LDAP server cert.
So the LDAP resolver could check this. (And I think this is the more important stuff in this very case)

**Comment by cornelinux** [comment]
We could have a service or tool that checks several end points (like LDAP, SMTP Server, SMS Gateways...) if there are certificates, that are about to expire.

These results could be displayed on a dash board #951

**Comment by pablo-knight** [comment]
Check:
[ ] Get necessary data from the database
[ ] How long is a certificate still valid
   - Has the certificate expired?
   - Root certificate has expired?
   - Has the issued TLS certificate expired?
[ ] Send a mail
[ ] cronjob


**Get necessary data from the database**

Approaches:

A. Configuration query and database query
Read the privacyidea configuration file and get the database user and password from there. 
With the access you get the following values with a database query from the table "resolverconfig".


The data can then be used to perform a certificate check.

Example.
Check whether TLS_VERIFY is checked and get resolver_id
SELECT resolver_id FROM resolverconfig WHERE resolverconfig.Key='TLS_VERIFY' AND resolverconfig.Value='True'

Get the corresponding "LDAP_URI" from "resolver_id"
SELECT Value FROM resolverconfig WHERE resolver_id='$resolver_id' AND resolverconfig.Key='LDAPURI'

Get the "TLS_CA_FILE" path using the "resover_id"
SELECT Value FROM resolverconfig WHERE resolver_id='5' AND resolverconfig.Key='TLS_CA_FILE'



B. Via pi-manage 
Via the command 

pi-manage config exporter -t resolver -f json -o test.json

you can continue working with the json output and filter the following data:


"TLS_VERIFY": "True",
"LDAPURI": "ldaps://ldap-server",
"TLS_CA_FILE": "/etc/privacyidea/some.crt",



**How long is a certificate still valid**

How to retrieve the CA root certificate from an LDAP server:


openssl s_client -showcerts -verify 5 -connect ldap-server.com:636 < /dev/null | awk '/BEGIN/,/END/{ if(/BEGIN/) {a++}; out="ldap-cert "a".pem"; print >out}' 


An LDAP server can also have several certificates, so let's get them all and see what else needs to be done.

**Send a mail**

**cronjob**

**Comment by pablo-knight** [comment]
The certificate audit script should work in a similar way to the cronjob.

`#0 0 * * 0 privacyidea /opt/privacyidea/bin/pi-manage audit rotate_audit --age 360`


`# 0 0 * * 0 privacyidea /opt/privacyidea/bin/cert-checke --days=21 --email=admin@example.net`

The following is kept flexible, email address and how many days before the certificate expires. Optionally, whether only the web server (apache or nginx) should be checked, or only the LDAP client certificate and the CA certificate. Or everything.

**Comment by pablo-knight** [comment]
### Documentation of the Certificate Check Script

#### Overview

This script is used to check TLS certificates for web servers and LDAP servers, as well as CA certificates. It allows you to check the validity of certificates and issue warnings if a certificate is about to expire. The script can optionally create log files.

#### Functions

1. **Logging Configuration**
   - `setup_logging(log_path=None)`: Configures the logging system. If a `log_path` is provided, logs will be written to this file; otherwise, they will be displayed on the console.

2. **Message Logging**
   - `log_message(message, error=False, warning=False)`: Logs messages as info, warning, or error and optionally displays them on the console.

3. **Search Configuration Files**
   - `find_config_files(directory, file_patterns)`: Searches a directory for files that match specified patterns.

4. **Extract Certificate Path**
   - `extract_certificate_path(config_path)`: Extracts the certificate path from a configuration file.

5. **Load Certificates**
   - `load_certificates(cert_path, ca_path=None)`: Loads certificates from specified paths.

6. **Check Certificate Expiry**
   - `check_certificate_expiry(cert, days, cert_description)`: Checks if a certificate will expire within a specified number of days and issues a corresponding warning.

7. **Retrieve Server Certificate**
   - `get_certificate_from_server(server_address, port, starttls=False)`: Retrieves a server certificate using OpenSSL.

8. **Verify Certificate Signature**
   - `verify_certificate_signature(client_cert, ca_cert, cert_description)`: Verifies if a client certificate is signed by a CA certificate.

9. **Main Function**
   - `main()`: Main function that processes the arguments and performs the corresponding checks.

#### Usage

The script is executed from the command line and supports several arguments to configure the certificate checks.

##### Command Line Arguments

- `--days`: (required) Number of days before expiration to issue a warning.
- `--config-dir`: Directory to search for web server configuration files.
- `--web`: Checks the web server certificate.
- `--ldap`: Checks the LDAP server certificate.
- `--ca`: Checks the CA certificate.
- `--all`: Checks all web server, LDAP server, and CA certificates.
- `--logging`: Path to the log file. If not set, logs will be printed to stdout.

##### Example Invocations

1. **Check all certificates and log to a file**

   ```bash
   python check_certificates.py --days 30 --all --logging /path/to/logfile.log
   ```

2. **Check only web server certificates and output to console**

   ```bash
   python check_certificates.py --days 30 --web
   ```

3. **Check LDAP server certificates and log to a file**

   ```bash
   python check_certificates.py --days 30 --ldap --logging /path/to/logfile.log
   ```

4. **Check CA certificates and output to console**

   ```bash
   python check_certificates.py --days 30 --ca
   ```

#### Sample Output

When the script runs, the output may look like this:

```plaintext
2024-05-17 13:39:15,315 - INFO - CA issuer from resolver "ad" certificate is valid for 619 more days.
2024-05-17 13:39:15,316 - INFO - CA issuer from resolver "ucs07" certificate is valid for 1373 more days.
2024-05-17 13:39:15,316 - INFO - CA issuer from resolver "ucs05" certificate is valid for 883 more days.
```

#### Error Handling

The script handles various types of errors, such as failing to retrieve certificates or problems reading configuration files, and outputs corresponding error messages:

```plaintext
Failed to retrieve certificate from 10.0.5.21: Command 'echo | openssl s_client -connect 10.0.5.21:389 -starttls ldap 2>/dev/null | openssl x509' returned non-zero exit status 1.
Failed to connect to 10.0.5.21:389: Command 'echo | openssl s_client -connect 10.0.5.21:389 2>/dev/null' returned non-zero exit status 1.
```

#### Summary

This script is a helpful tool for administrators to monitor the validity of TLS certificates in their systems and receive timely warnings when certificates need to be renewed. By supporting log files and various operating modes, it can be flexibly integrated into different monitoring and maintenance processes.
