### ISSUE TITLE
Users List UI slow 10 seconds if there are 100,000 users in  the sql resolver.

### ISSUE THREAD

**Issue by yangboyd** [privacyidea/privacyidea#1901]
Maybe this is a feature request.
The pagination parameter is not  transferred from web ui to the privacyIDEA  server.
So it causes the UI slowly.

This feature maybe  sql resolver only.
Other resolvers may not support offset/limit search parameters.

**Comment by cornelinux** [comment]
privacyIDEA explicitly adheres to the concept of I-do-what-you-configured. And you probably need to change your settings.

Reduce the parameter "Sizelimit" in your SQL Resolver! Since you probably do not want to browse through a list with 6666 pages! 

You will always first search for a user with certain pattern (and being it the first two characters) and then browse through a list with one or two pages.

Are you really running privacyIDEA with 100K users? Or did you forget the "where" statement.

If you think the SQL-Resolver should be changed, please propose some more details or even a pull request.
(Otherwise this issue is about to be closed)

**Comment by cornelinux** [comment]
no details received, so I am closing this.
