### ISSUE TITLE
mschap v2

### ISSUE THREAD

**Issue by ardegr** [privacyidea/privacyidea#1916]
Hi!
I suppose privacyIDEA does not support mschap v2 authentication. I've tried it with l2tp vpn and it doesn't work. It works only when I choose PAP. It would be great to implement it!
I have also tested multiOTP for authenticating VPN users with l2tp mschap v2 and with 6-digits OTP as a VPN password. It works fine. So maybe you can implement some similar solution? 

I'll try to explain my thoughts about why it is so important to use mschap. I think most of you will agree that it is pretty hard to educate users not to enter their main domain password when connecting to corporate vpn but use OTP only in case of using PAP. Of course if they won't enter OTP, authentication will be unsuccessful but their domain password can be intercepted while using PAP.
What do you think? Thanks!

**Comment by ardegr** [comment]
@cornelinux, I'm talking about option 1. I understand that you do not know LDAP password. But I thought you know <OTPvalue> and you can calculate it's hash. So why can't we use just <OTPvalue> as vpn's password? Sorry, maybe I don't understand something well :)
If I'm not mistaken, multiOTP's solution works this way too. It can use only <OTPvalue> as password, without LDAP password for the same reason.

**Comment by cornelinux** [comment]
These were not specific options. But now I understand your point. 
You are affraid that a wrongly entered password (which in fact is not necessary for the authentication itself) could be leaked somewhere.

Yes, that is right.
But hey, I even once entered the password in the username field and thus diclosing the password in the log file. sh** happens.

I understand you point. But I do not see, why wee should do at least two weeks of effort here.

**Comment by cornelinux** [comment]
One final note:
You might have a bit mixed up scenario: I can only imagine one aspect, where the user would only enter his OTPvalue.
In a frist step s.th. like Netscaler would ask the user for *username* and *password*, which it authenticates against LDAP.
In a second step it will *only*  ask the user for his OTP value (only *one* input line, no username).
This input line is labeled accordingly and tells the user to enter his OTP. This would be verified via RADIUS. Yes, in this scenario and adminsitrator could decrypt with the RADIUS shared secret the entered value - which is usually the OTP value.
Yes, if the user is dumb enough (although the labelling of the field says otherwise) to enter his LDAP password *again*!, then the admin could decrypt the LDAP password.

As this is only one scenario of many others, where using mschapv2 is not even possible
and as also RADIUS is only one scenario of a lot of other authentication protocols which are used today...
(you get the point)

**Comment by linuxchips** [comment]
Hi;
one other situation is when you have a network equipment that only support single step authentication, and it only works with chap or mschap.
here, I d rather use an OTP (alone) over a static clear text password in some database
