### ISSUE TITLE
Add tokeninfo or tokentype to policy condition

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#1947]
For certain policies it might make sense to allow the tokentype to be taken into accout like:

* only require a PIN for a certain token type
* ...

But there are a lot of other policies, where it would not make sense or where it would result in wrong expectations

* A ``userlist`` admin-policy with a condition "tokentype" - what do you think would this mean? Only allow the admin to list users, who have a token of this very tokentype? - probably not.

So the question is, if it makes sense at all to add further conditions to the policies or to split the actions, where it seems to be necessary like:

  * allow max tokens for different tokentypes
  * otppin for certain tokentypes...

In some scenarios we already have this distinction like totp_hash and hotp_hash.

This is why tokenclasses were allowed to add policy-actions in the first place.

**Comment by cornelinux** [comment]
With the new policy ``Match`` API adding tokeninfo seems quite straight forward compared to the userinfo and the http_header.
Adding this to the milestone. :-)

**Comment by cornelinux** [comment]
## Todo

We need to do several changes to ``lib/policy.py``.

Add new section in:

~~~~python
class CONDITION_SECTION(object):
    __doc__ = """This is a list of available sections for conditions of policies """
    USERINFO = "userinfo"
    HTTP_REQUEST_HEADER = "HTTP Request header"
    TOKENINFO = "tokeninfo"
~~~~

Then we need to add a ``PolicyClass._policy_matches_tokeninfo_condition`` here.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L712

## The challenge

We have to get the request or the serial number or the token_object in here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L620

**Comment by cornelinux** [comment]
move this to 3.4

**Comment by cornelinux** [comment]
We could implement this in the same way as we added the ``userinfo`` in the additional conditions.
We also do not always have a user in a request. And we also do not always have a token in the request. So imho implementing ``tokeninfo``  additional condition should be straighforward when applyhing the same logic and code.

We should consider skipping the *tokentype*. If the tokentype indeed is need for some conditions, we could still write the tokentype into a tokeninfo field.

The implementation should be clear and the documentation should be clear, that this condition will only apply, if a token is actually given in the request or if the request is actually ment to act on a token. I.e. when listing users, deleting users, deleting policies, the logic can not check, if this policy only applies to tokens with a certain tokeninfo. We need to avoid getting into a mess ;-)

**Comment by laclaro** [comment]
The challenge mentioned above is indeed the key point. Since it varies from request to request if we have a token serial or anything similar we can work with. If for instance token/setpin ist requested with authorization and serial, we do not pass the serial down to the matching class.

So to make this work, we have to check every policy matching and pass it to the Match functions.

**Comment by cornelinux** [comment]
> So to make this work, we have to check every policy matching and pass it to the Match functions.

I do not understand this.

**Comment by cornelinux** [comment]
We should first do #2534

**Comment by cornelinux** [comment]
#2534 is merged. So now we can add the ``TOKENINFO`` to the ``CONDITION_SECTION`` as mentioned above and enhance
the [filter_policy_by_condition](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policy.py#L737).

We can create a new ``self._policy_matches_tokeninfo_condition``. 
*But!* We still have to pass the g-object or the serial number (or preferrably the tokentype) into the ``PolicyClass``. This is subject to discussion.

**Comment by laclaro** [comment]
Since the serial is only required to filter policies by condition, I would introduce it not in list_policies but only in match_policies.

The argument serial must be fetched from the g object in the Match class (Match.generic).

Since tokeninfo and userinfo work very similar, I suggest to create a filter function self._policy_matches_info_condition which gets either a dbtoken object or a user object to filter.

A full-fledged token object does not work in lib/policy due to circular imports.

By the way: from there, the implementation of token properties as conditions is a small step.

The WebUI fetches the rights to enable/disable buttons without any tokeninfo.
