### ISSUE TITLE
setup.py does not allow  python3

### ISSUE THREAD

**Issue by quynhnhatnguyen** [privacyidea/privacyidea#1955]
### Top-level intent

Installing privacyidea with git

### Steps to reproduce

`pip3.4 install git+https://github.com/privacyidea/privacyidea.git`

### Expected outcome

PrivacyIDEA with pip 3 support installed

### Actual outcome

Failed with errors:

```
ERROR: privacyIDEA requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*' but the running Python is 3.4.10
```

Can you please confirm and remove the restriction for python3 in setup.py. Can we please also update to make sure the deps requirement list in `setup.py` is up to date?

Thank you!

**Comment by plettich** [comment]
According to the [Python 3.4 release schedule](https://www.python.org/dev/peps/pep-0429/) this version has reached it's end-of-life. Which OS are You using? Could You switch to a newer Python version?
Python 3.5 is supported since fc7cfeaa46059bc1293b2fb553007b94f94a227d and available in the current release 3.2.

**Comment by cornelinux** [comment]
Hi @quynhnhatnguyen One thing to point out: To my understanding our code does currently not support python 3.4. I.e.: Probably not all lines of code, not all scenarios can run with python 3.4, this is also a reason why it is excluded in the "supported" versions. Otherwise, see @plettich questions and coments.

**Comment by quynhnhatnguyen** [comment]
Thank you for the clarification.
I was testing with the branch-3.1 code base. I will retry with master and python 3.5 and above.

**Comment by cornelinux** [comment]
Please note that 3.2 was released (you find the version tag in the master).
