### ISSUE TITLE
Support wildcard serials when doing a trigger challenge

### ISSUE THREAD

**Issue by darrenche** [privacyidea/privacyidea#2028]
**Is your feature request related to a problem? Please describe.**
What are you trying to achieve?

Support wildcard serials when doing a trigger challenge. This was supported in the past!

**Describe the solution you'd like**

Refer to https://github.com/privacyidea/privacyidea/pull/2023 with **Lines 451, 529, 533-538**.

**Describe alternatives you've considered**

N/A

**Additional context**
Add any other context or screenshots, that might help us to better understand your idea, your need and your circumstances.

Refer to https://github.com/privacyidea/privacyidea/pull/2023

**Comment by cornelinux** [comment]
It does not work this way. Create a PR and say, I would like to do what is in the pull request.

Issues are used to describe and discuss problems! Your behaviour is annoying!

Please describe what you understand of "wildcard serials". If you check the documentation, there was never something described like a wild card serial. So you may want to have a side effect back, that was never intended on purpose. You need to help us understand you. This issue does not help with that!

**Comment by cornelinux** [comment]
I am wrong. wildcards *do* exist on a library level for searching and using GET /token/.
But they never existed (on purpose) for authentication. So if you think you need to re-add this. You need to describe your usecase in more detail! What you think you should be able to do and what you think should happen!

**Comment by quynh-axiadids** [comment]
Hi @cornelinux,

We also would like to request for this feature.

In our case, a user can have multiple challenge-response tokens, and they are of different types. When the user tries to authenticate, we want to only trigger certain type of challenge-response tokens. Usually, we do this by passing the param `serial=<TYPE>*` to the `/validate/triggerchallenge` endpoint.

It will be great if this can be supported.

Best regards,
Quynh Nguyen

**Comment by cornelinux** [comment]
Hello @quynh-axiadids ,
thanks a lot for your clarification.
So do you **let the user choose**, which token type he wants to use, or do you want **to force** the user, to use a token of a certain type?

If you let the user choose, do you query the tokens of the user first, which tokentypes are availalbe?

If you want to force the user, there are better approaches, than to send a parameter.

If you really need to send a parameter, we can not send a wild card serial, since it is crippled for a lot of different logic features like with the event handlers. So if necessary I would rather (only having thought about it for ten minutes) add a new parameter like ``tokentype`` and ``tokenkind``.

But the real interesting question is, if it is a choice of the user or of the admin/the privacyidea system.

**Comment by quynh-axiadids** [comment]
Hi @cornelinux,

Thank you for the quick feedback.

In our use case, we will only access the `/validate/check` and `/validate/triggerchallenge` endpoint for simplicity and also due to some restriction.

The `/validate/triggerchallenge` is a protected endpoint with admin-role only access (https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L449). The choice will also be the admin choice in this case.

A new parameter such as `tokentype` for the `/validate/triggerchallenge` endpoint will definitely be sufficient for our scenario, if you think it is a better solution!

(On a totally different note, (my advanced apology to bring up another topic in the same thread, but since we are on this), having `/validate/triggerchallenge` to require admin-role access only has been posing some limited usage for this endpoint, such as a remote client access where an admin API key will need to be distributed. I think, enforcing validate-role access may be sufficient for this endpoint? However, I totally understand how this endpoint can be abused if misused, and this is just a quick thought of mine.)

**Comment by cornelinux** [comment]
So we will follow the path to add do authentication only for certain tokentypes or tokenkinds.
I will open another issue for that, since the top of this issue is rather cluttered.

> (On a totally different note, (my advanced apology to bring up another topic in the same thread, but since we are on this), having /validate/triggerchallenge to require admin-role access only has been posing some limited usage for this endpoint, such as a remote client access where an admin API key will need to be distributed. I think, enforcing validate-role access may be sufficient for this endpoint? However, I totally understand how this endpoint can be abused if misused, and this is just a quick thought of mine.)

I do not understand your point with "validate-role access". Please open another issue for this.

**Comment by cornelinux** [comment]
@quynh-axiadids  @darrenche 
Have you you checked the authorization policies "serial" and "tokentype"? 
https://privacyidea.readthedocs.io/en/latest/policies/authorization.html#tokentype

They do exactly what you want. If you *always* want the user to authenticate with a specific tokentype.

Unless you do not want to user to one day authenticate with an email C/R token and next day with a Push C/R token, these policies are exactly what you want.

**Comment by cornelinux** [comment]
Have not created the new issue, yet, since i have the question I stated before. So I am reopening this issue again.

**Comment by quynh-axiadids** [comment]
@cornelinux 

The user will not always authenticate with this tokentype. They will choose to authenticate with typeA or typeB at the same system each time.

**Comment by cornelinux** [comment]
@quynh-axiadids thanks for clarification.
So you actually want the system to send to privacyIDEA: "please authenticate the user now with 'typeA'".

~~~~http
POST /validate/check

user=hans
pass=123456
type=sms
~~~~

~~~~http
POST /validate/triggerchallenge
authorization:...

user=hans
type=xyz
~~~~

So one trigger challenge request, with one token type.
Next time a trigger challenge request with maybe another tokentype, right?

**Comment by cornelinux** [comment]
Hello @quynh-axiadids 
I am still wondering how you actually integrated this into your application?

I would like to verify this, since I am a bit hesitant to implement the tokentype, since it comes with certain drawbacks.

So I assume that you simply assume that the user has tokentypeA and tokentypeB and you *ask* him, do you want to use A or B? And then send the triggerchallenge with serial=A* ?
Am I right here?

Here is another possibility to deal with it in a cleaner way:

# Workflow for specific token challenges

Image a user "hans" wants to login with one of his challenge response tokens.

## Application checks tokens of the user

The application can check which tokens the user actually has. It can do so by issuing

~~~~http
GET /token/?user=hans
~~~~

It will receive the following response:

~~~~json
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": {
            "count": 3,
            "current": 1,
            "next": null,
            "prev": null,
            "tokens": [
                {
                    "active": true,
                    "count": 0,
                    "count_window": 10,
                    "description": "",
                    "failcount": 1,
                    "id": 292,
                    "info": {
                        "2step_clientsize": "8",
                        "2step_difficulty": "10000",
                        "count_auth": "2",
                        "hashlib": "sha1",
                        "tokenkind": "software"
                    },
                    "locked": false,
                    "maxfail": 10,
                    "otplen": 6,
                    "realms": [
                        "testfoo"
                    ],
                    "resolver": "testfpp",
                    "revoked": false,
                    "rollout_state": "",
                    "serial": "OATH001137B7",
                    "sync_window": 1000,
                    "tokentype": "hotp",
                    "user_editable": false,
                    "user_id": "f0362e71-3d5c-4606-9051-00590777a76f",
                    "user_realm": "testfoo",
                    "username": "hans"
                },
~~~~
The application will receive a list of the tokens in with ``tokentype`` and ``serial``.

So your application can actually filter for the C/R tokentypes you want to use, like "Push", "SMS" or whatsoever. The application can exactly show these tokens to the user, which the user actually *has*.

## User chooses token

You can have the user choose "SMS", or in my case "HOTP" and then your application will **know** the serial.

## Application triggers challenge

Now your application can trigger the challenge with the exact serial number.

~~~~http
POST /validate/triggerchallenge
authorization:....

serial=OATH001137B7
~~~~

# Pros

On the pro side your application will only allow the user to choose the tokentype (or the serial) which the user actually **has**. So a user might be allowed to have tokentype A and tokentype B but for some reason he does not have B. So in this case he will only be able to choose A.

What do you think?

**Comment by quynh-axiadids** [comment]
In our usage, the PrivacyIDEA adapter was installed on a remote site, therefore we do not distribute an admin-role API key due to security reason, and we only distribute API key with `validate` role:

Example to generate a `validate` role API key:
```
$ /opt/privacyidea/bin/pi-manage api createtoken -r validate -R corp -d 365
```

With this API key, we cannot access those API endpoints that you mentioned. We also do not access the `auth` endpoint to get the user role API key. The error received for accessing those API endpoints:

```
    "result": {
        "error": {
            "code": 4306,
            "message": "Authentication failure. You do not have the necessary role (['user', 'admin']) to access this resource!"
        },
        "status": false
    },
```

For `/validate/triggerchallenge`, we changed the code behavior to only require `validate` role API key as I mentioned to you in earlier post. This is also why we would like the `/validate/triggerchallenge` also required a lesser privilege API key; we will open this request in a different ticket.

**Comment by cornelinux** [comment]
Honestly I do not know, what to do with that. I do not accept that you change the code and then complain that things do not work as you expect.

I see a certain security issue, as mentioned in #2047,with an application or a user allowing to pass the tokentype. Having a restricted admin account, that is only allowed to check the available tokens of the user is imho a lesser risk.

In addition there is imho no sense in allowing an api key to call triggerchallenge. The account of a triggeradmin can be blocked or changed in the background. The API key can not (easily).

**Comment by cornelinux** [comment]
@quynh-axiadids Use an restricted admin account. it is more secure and more flexible.
You can restrict it by time and IP.
You could also use trusted jwts https://privacyidea.readthedocs.io/en/latest/installation/system/inifile.html#trusted-jwts to exactly what you want.

1. only allow one GET /token (if we do not implement #2047)
2. run triggerchallenge

**Comment by quynh-axiadids** [comment]
@cornelinux Thank you for the pointer. We will take a look into that, although there is still other inconvenience such as multiple triggerchallenge calls for multiple serial numbers of the same token type etc when the user has multiple challenge-response tokens for the same type).

Thanks again for looking this!

Best regards,

Quynh Nguyen

**Comment by cornelinux** [comment]
**Yes, but serial wildcards do not solve this remaining problem either!**
This can be only done by getting all the tokens of the user, asking the user which token to use and then run the triggerchallenge for a specific serial number.
So, why not do it this way in the first place ;-)
