### ISSUE TITLE
Error message shows as wrong otp value while the violation to due to other reasons

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#2161]
What did you try to achieve?

Authenticate with correct error message showed.

Steps:

1. Enroll a token such as HOTP. Set the validity to outside of the moment period to force authentication failure due to validity.
2. Authenticate with correct pin and correct otp value.

### Expected outcome

Authentication fails with error message of validity violation.

### Actual outcome

Authentication fails with error message `wrong otp value`

### Configuration

* **privacyIDEA version**: 3.1.2
* **Installation method**: github
* **Python version**: 2.7
* **Operating system**: centos 6
* **Webserver**: nginx
* **Token database**: PostgreSQL

Validity is just an example, overall it will be more helpful for the users if the error message shows the proper violation as in `TokenClass.check_all()` instead of the generic `wrong otp value` when it is not because of wrong otp value submision.

Best regards,

Quynh Nguyen

**Comment by plettich** [comment]
Hi @quynh-axiadids,
with privacyIDEA 3.2.1 and python 2.7 i get the following json response when authenticating with a token which is not in it's validity period:
```
{
    "detail": {
        "message": "matching 1 tokens, Outside validity period",
        "otplen": 6,
        "serial": "OATH0000C41E",
        "threadid": 140679603177280,
        "type": "hotp"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": false
    },
    "signature": "...",
    "time": 1587397128.118193,
    "version": "privacyIDEA 3.1.2",
    "versionnumber": "3.1.2"
}
```
Does the user has more than one token assigned?

**Comment by cornelinux** [comment]
It is quite clear:

If the OTP value is wrong! this takes precedence. Then the error message is "wrong otp value".

If the OTP value is correct, but the validity is out of the validity period, the error message is "matching 1 tokens, Outside validity period"

The OTP value of the token is **always** checked, since we need to invalidate OTP values. This is quite clear for HOTP tokens.
So if the OTP checking fails, the validity period is not checked anymore anyways.

Works as designed.

@quynh-axiadids If you have other examples, please shoot. 

The example with ``check_all`` bears a similar issue. If you have a disabled token, you will not be informed, that the token is outside of the validity period.

The overall token checking routine in ``token.check_token_list`` currently works this way, that first matching OTP values are checked. The routine works this way, so it works with a list of several to-be-checked tokens of a user. We currently do not want to redesign that.
