### ISSUE TITLE
pi-manage create_pgp_keys does not create keys

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2165]
Hi,

we encountered a problem with `pi-manage create_pgp_keys`. It actually does not create the keys.

The gpg home directory was populated correctly during package install but the above command does not add a key pair. Therefore not key is listed in the "Import Tokens" section in the WebUI.
Also the command
`sudo gpg --homedir /etc/privacyidea/gpg --list-keys`
does not list any keys.

The keys can be created manually using the gpg tool. If you use sudo for this, it is necessary to change the ownership of the tty temporarily (for input of the EMPTY password of the key :smile: ).
- sudo chown <user_before_sudo> /dev/pts/0
- sudo gpg --homedir /etc/privacyidea/gpg --gen-key --verbose
- sudo chown root /dev/pts/0
- sudo gpg --homedir /etc/privacyidea/gpg --list-keys

Result: key ist displayed in the WebUI. Exporting the created key with gpg, encrypting a the token-csv file and importing it in the WebUI works flawlessly.

Best,

Henning

**Comment by cornelinux** [comment]
The problem is, that the underlying GnuPG seems to have changed. The python-gnupg uses the gpg batch mode. The following input string is used:

~~~~
Key-Type: RSA
Key-Length: 2048
Name-Real: privacyIDEA Server
Name-Comment: Import
Name-Email: root@puck
%commit
~~~~

Using this input string at the shell shows us, that (at least under 18.04) gpg asks for a passphrase.
This is why the pi-manage, that uses batch mode and can not ask for the passphrase, fails.

One solution would be to use a passphrase (bad idea, imho) or the
other solution would be to force to use no passphrase using ``%no-protection``:

~~~~
Key-Type: RSA
Key-Length: 2048
Name-Real: privacyIDEA Server
Name-Comment: Import
Name-Email: root@puck
%no-protection
%commit
~~~~

However, [this]() does not work out nicely, becasue the ``%no-protection`` can not be directly added in ``gen_key_input``. We would have to manually remove "%commit" and add both lines at the end,
