### ISSUE TITLE
wizard: QR code is not centered after enrollment

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2348]
The alignment of QR Codes and texts in the wizard is not ideal. 

- The QR image should be centered after enrollment
- The help text what to do with the displayed code after enrollment is not displayed
- keep additional containers in two-step-enrollment in mind

**Comment by cornelinux** [comment]
Please check with an older version like 2.23.
Because this looks to me like the normal behaviour.

The QR code was never centered. It is just scaled in contrast to the normal enrollment and hence it is left aligned.

The enrollment wizard never contained a help text, since it is reading templates that are supposed to be created by the admins so that individual texts can be added above and underneath the QR code.

**Comment by laclaro** [comment]
That is true, this is suggested as an enhancement, not a fix.

I mean the alignment is not ideal since the wizard is most of the time used to greet new users. In that case, there is only the wizard displayed without any additional navigation panels. In a previous issue #2175, we centered the QR codes in the wizard to be aligned with the (only) button that is displayed.

But after enrollment the token QR code is displayed un-centered again and without any additional texts, which looks strange in my opinion. The user may ask - "And now, what to do?"

We should discuss that.
