### ISSUE TITLE
Use autocomplete="new-password" instead of "no"

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2401]
Initiated by #2292

Since in most cases we do use password-fields not for login, but just to hide the input, the browser should not attempt to autofill. We use autocomplete="no" for this purpose.

However, autocomplete="no" is not honored by modern browsers, since they think storing passwords even without master-password protection is more secure than remembering them all.

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

We therefore should check the UI code and replace occurrences of `autocomplete="no"` with `autocomplete="new-password"`, wherever useful. 
https://github.com/privacyidea/privacyidea/search?p=2&q=autocomplete

We should not touch the UI login here:
https://github.com/privacyidea/privacyidea/blob/e09465107bf554a99057b3ae6fa6595b6da3db3e/privacyidea/static/components/login/views/login.html#L72

**Comment by timosturm** [comment]
I suspect, that you meant `'autocomplete="off"` to be replaced where appropriate? `autocomplete="no"` does not seem to exist?

**Comment by timosturm** [comment]
I also would like to mention, that `autocomplete="new-password"` could trigger the browser to recommend generating a new password (that could be bad when `tabulator` is used to switch between password fields, leading to similar problems as in #2292). Maybe something else from [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) list is a better option, I would suggest `"one-time-code"` because it seems unlikely that this will be prefilled or get suggestions on desktop browsers at all.
