### ISSUE TITLE
Verify successful enrollment, assignment or unassignment with 2nd step (like entering OTP)

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2441]
This was:

# Require OTP for assignment (of hardware tokens)

For a help-desk use case, the accidental unassignment of hardware-token may lead to their disappearance (or you immediately realize it track it down in the audit log).

However, we may add a feature that you can only assign (hardware) tokens by giving a valid OTP.

## Use case

Assignment
- Take a physical token from a box at your desk.
- Search the token by serial in privacyIDEA
- assign the token to the user that is standing right next to you
- hand over the functioning token

Unassignment
- Someone returns the physical token
- Search the user in privacyIDEA
- Unassign the token after giving the OTP

By doing so, we prevent that the wrong token gets assigned/unassigned and ensure that the token actually works.

## Implementation

* [x] 1st step (challenge) of enrollment
* [x] 2nd step (verification) of enrollment
* [x] support email tokens
* [x] support SMS tokens
* [x] Allow verify enrollment in WebUI
* [x] Add verify line in the token details, if the token is still in the state "verify".

**Comment by cornelinux** [comment]
# Requiring OTP

The same would be true for enrollment. 

We could add an optional parameter `otp` to the endpoints

* `token/assign`
* `token/unassign`

If the parameter is not specified, the function will fail.

But this would not work for `token/init` since the HOTP secret key is not available yet.

(Well, this is somehow annoying if the token is not available anymore, then it could not be unassigned, since the OTP value can not be created ;-)

A policy could require the OTP value during enrollment, assignment or unassignment.

# Enrollment via Challenge Response

*enrolling*, assigning or unassigning could be done in two steps:

1. User tells privacyIDEA to enroll a token `token/init`
    * privacyIDEA sends QR code
    * User scans qr code
2.  User sends OTP value to privacyIDEA.

In the meantime, between step 1 and 2 the token could remain in a `rollout_state` "client_wait". 
This would be somehow connected to #2784 

# Generic Approach

Looking at this in a generic way, this would mean, that the enrollment can always occur in two steps.

This is true for tokens like push, tiqr, 2step anyways.
But it could be done for any other (especially hotp and totp) token, too.

**Comment by cornelinux** [comment]
# Rollout State

From a cryptographic standpoint the HOTP token would be readily enrolled or finally assigned.
It is however an organizational question, if the user has handled the token correctly.

As stated earlier the token could remain in a special rollout state. Maybe not necessarily the state "client_wait" but some other state like "client_verify", to indicate that we need to verify that the user has handled the token correctly. The correct handling of the token could differ from token type to token type.

For an HOTP or TOTP token this could be providing a correct OTP value after enrollment or assignment.

So if a user enrolled an HOTP token but did not scan the QR code correctly the user will not be able to provide the OTP value and the enrolled token object will remain in the state "client_verify".
Such tokens could later be cleaned up.

A policy could define, if the *client_verify*-step is needed or not.

**Note:** This is maybe a bit different to the original post. I think the original idea was to avoid assigning a *wrong* hardware token. This could be done by verifying that the correct hardware token is in fact preset by providing a valid OTP value.

**Comment by cornelinux** [comment]
# Generic Actions or Token Specific?

There are some tokens, that already have a 2nd step, that assure, that the user has enrolled the token successfully:

The **Push** token is only readily enrolled, when the user acts on his smartphone and the smartphone finally communicates with privacyIDEA server. Thus the server can be sure, that the user has the token.

The **two step enrollment** for HOTP and TOTP only works, when the user enrolls the token and enters the *client part*. This way the server can be sure, that the user is in possession of the token (however, this does only work for the *privacyIDEA Authenticator*)

But these different token types have different ways of a 2nd step. So there does not see to be a generic way for all token types.

So maybe we should generically add the possibility, that a token type (tokenclass) defines the client-verification way, how the server can be sure, that the token was enrolled...

## How could token types assure this?

* PUSH: intrinsic
* HOTP / TOTP with two step: intrinsic
* HOTP / TOTP withoutt 2step: can be done by providing an OTP value
* Email: Can be done by sending an OTP value and entering the OTP value
* SMS: Can be done by sending an OTP value and entering the OTP value
* SPASS: n/a
* Registration: How should we verify if the user writes down the registration code? I think n/a
* WebAuthn: instrinsic
* U2F: intrinsic
* x509: The important part is the private key. And I think this is also intrinsic

Thus, it looks like the solution is only necessary for OTP-like tokens (HOTP, TOTP, Email, SMS) by requesting such OTP.

An open point would still be the question of assignment and unassignment - maybe it can be done the same way. On the other hand: unassigning a WebAuthn-Token is not intrisically assured.
