### ISSUE TITLE
Return the same attribute multiple type in radius plugin

### ISSUE THREAD

**Issue by cmammoli** [privacyidea/privacyidea#2447]
**Is your feature request related to a problem? Please describe.**
In the radius plugin would be nice to have a way to return the same attributes multiple times when, for example, a user belongs to multiple groups

**Describe the solution you'd like**
For example with a configuration like this:

```
[Attribute Fortinet-Group-Name]
dir = user
userAttribute = group
regex = ^CN=(.*?),
```
The radius plugin will return a single Fortinet-Group-Name attribute with the last group of the user.

Instead it should return multiple Fortinet-Group-Name attributes:
Fortinet-Group-Name = group1
Fortinet-Group-Name = group2
Fortinet-Group-Name = group3

**Describe alternatives you've considered**
I tried to hack around in /opt/privacyidea/privacyidea_radius.pm but I really suck big time in perl

**Comment by cornelinux** [comment]
This already works. It the group you specified marked as a multi value attribute in the privacyIDEA resolver?
If so, this should work with the freeradius plugin.

Then, if you think you still have an issue, please open the issue with the freeradius plugin, since it is a separate project:
https://github.com/privacyidea/freeradius
Thanks!
