### ISSUE TITLE
Ability to choose sms gateway identifier in sms enrollment event

### ISSUE THREAD

**Issue by brunocascio** [privacyidea/privacyidea#2506]
**Is your feature request related to a problem? Please describe.**
We need to set SMS Gateway config per realm due we use multiple brands and we don't want to use the same for example, SMS Gateway sender (Same behavior as https://github.com/privacyidea/privacyidea/issues/2452)

**Describe the solution you'd like**
Add a field in the event framework to override the global configuration from privacyidea config 'sms.identifier'

**Additional context**
We're using keycloak as a centralized solution for authentication. We have 2 clients (foo.com and bar.com)
Each client want to send sms with their sms gateway configuration.

**Comment by brunocascio** [comment]
FYI @Jameru

**Comment by cornelinux** [comment]
Hi @brunocascio 

you can already do this on a per-token-basis using the tokeninfo ``sms.identifier``.
This is done via an *admin* or *user* policy where you can define, which gateway a user or admin is allowed to enroll.

Also for automatic enrollment you could set the ``sms.identifier`` in the tokeninfo using an event handler.

~~~~
Otherwise:

But you probably either do not want to "choose" the SMS gateway on each enrollment or you do not want to "allow" a user or a helpdesk user to choose the gateway.
So I would rather recommend to implement a policy, this way you can *rule* that a user in a certain realm gets a certain sms gateway and a service desk user can not override this.

There are two possibilities to approach this:

### 1. During  Enrollment

Using a policy in ``scope=enrollment``.
You could set an SMS gateway for this very enrolled token and save it in the tokeninfo.
It would be difficult to change this afterwards.
And it would be roughly the same, we can already do.

### 2. During Authentication

Using a policy in ``scope=authentication``.
You can define a policy per realm that says, which SMS gateway should be used.
Fallback to generic token configuration.
Pro: You can change easily change the gateway for a certain realm later.

(If so, we should do the same for email tokens)

**Comment by brunocascio** [comment]
Hi @cornelinux

I'll take a look at option 2 for both SMS and email gateways!

Thanks for your time!

**Comment by brunocascio** [comment]
@cornelinux 

We found with @Jameru that the functionality can be achieved with `additional_params` for both SMS and [email token](https://github.com/privacyidea/privacyidea/pull/2461/files#diff-f8504ebc544eca522e2db1fe1518f5bfead644daf8fb4d8d951e43d29bd37211R450)

So at this point

1. We could make a PR with the SMS identifiers list (Like [smtp does](https://github.com/privacyidea/privacyidea/pull/2461)) to be consistent
2. Do nothing, and use additional params, so smtp_identifier list in event handler could be deprecated :laughing:

Thoughts?

**Comment by cornelinux** [comment]
Adding an options to the tokenhandler sounds fine to me like:

~~~~python
"sms_gateway_identifier": {
                            "type": "str",
                            "visibleIf": "tokentype",
                            "visibleValue": "sms",
                            "description": _("Use a specific SMS gateway configuration for this token."),
                            "value": [...list of sms gateways...]
                        },
~~~~

You then need to set ``init_param["sms.identifier"]``  in the tokenhandler.

Please also remember to add the documentation here: https://github.com/privacyidea/privacyidea/blob/master/doc/eventhandler/tokenhandler.rst#enroll (I think although it is missing for the smtp_identifier ;-) 

(as far as do-nothing is concerned: You could set the sms.identifier as a tokeninfo - as it is this way - manually in the tokenhandler. So it would already work as you wish in the event handler. My suggestion above simplifies the configuration task for the admin)
