### ISSUE TITLE
Enroll Push Token via Link

### ISSUE THREAD

**Issue by marcohald** [privacyidea/privacyidea#2522]
**Is your feature request related to a problem? Please describe.**
Enroll a push token without the need of a second device.
**Describe the solution you'd like**
An additional Link to the QR Code displayed which opens the Authenticator and enroll it

**Additional context**
Normally our users enroll their push token on the office PCs.
Sometimes it is needed to ship them a company Laptop with VPN Client and enabled two factor before they enrolled their token.
Some users do not have a second device which can open the PrivacyIdea Site to log in with their registration token and scan the QR code with the app.
So it would be great to do it on one device.

**Comment by cornelinux** [comment]
Is this not possible with push tokens? I thought so, since it is possible with all other tokens with QR code:
![image](https://user-images.githubusercontent.com/1908620/99574512-c8e39e80-29d7-11eb-9ce7-1adc0201273d.png)

On the right side you see "click HERE or scan the QR Code".
I.e. on a smartphone the user could click the link.

Or maybe there is a misunderstanding?

**Comment by marcohald** [comment]
On my Browser there is no such link:
![grafik](https://user-images.githubusercontent.com/10107699/99633917-f95f2300-2a3f-11eb-8702-12b89174785b.png)

**Comment by cornelinux** [comment]
Thanks, that is right.
We are missing the clickalble link for the push token here https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enrolled.push.html#L10

We should add it just like it is with the HOTP/TOTP token:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enrolled.totp.html#L21
