### ISSUE TITLE
no serial in polling on /ttype/push

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2605]
We may have a bug in push polling. This exception occurs on polling

https://gist.github.com/laclaro/743618d11f61f8a817e273db6b804a9a

This may be related to #2534.

**Comment by cornelinux** [comment]
In ``test_lib_tokens_push.py`` we have a lot of tests of /ttype/push with a serial. To me it looks like as if the server shoud work correctl.y

So it could also be, that the app actually sends an empty serial, which results in the error. 
@laclaro  Which App and version was used when observing this?

**Comment by plettich** [comment]
Actually @laclaro is right, the (API) tests use the FakeFlaskG class which sets `serial` to `None` (so it exists).
When calling the `/ttype` endpoint, the `serial` is not set in the `g`-object since it uses a different `before_request` decorator.
We should add this to the `before_request` decorator for the `/ttype` endpoint but we should also check if requiring it in the user matching 
https://github.com/privacyidea/privacyidea/blob/2bf8295da409b0f86483b11ae1fb3badd928650b/privacyidea/lib/policy.py#L2574
is necessary (All other endpoint decorators set it to `None`).

**Comment by laclaro** [comment]
> @laclaro Which App and version was used when observing this?

Mostly, the Authenticator 3 Beta Channel on iOS, possibly also on Android.

**Comment by laclaro** [comment]
We need the serial in the matching, since we may have tokeninfo conditions in every policy. I suggest to to add a line to before_request().

https://github.com/privacyidea/privacyidea/blob/0622dcbf3fb3f34fcf4fcb7331f54047a3858dcf/privacyidea/api/ttype.py#L70-L71

``` python
72      g.serial = getParam(request.all_data, "serial") or None
```

**Comment by plettich** [comment]
This is not yet in out master branch, so we usually keep the issues open until then...
