### ISSUE TITLE
Mass token init 

### ISSUE THREAD

**Issue by cochennec** [privacyidea/privacyidea#2633]
In our administration, we transfer a list of new users to their manager, including their LDAP login.
We would like the manager to use a csv containing all the logins in a column to do a "mailing" of their registration codes, after initializing a registration token, for each of them.

We already have [the API for that](https://privacyidea.readthedocs.io/en/latest/modules/lib/tokentypes/registration.html#code-registration-token) so we can make a script that would do a HTTP POST request for each user, and then parse the result.
But it would be better if a single HTTP POST request could be done for the whole bunch of users.
Our interest for a unique request is beacause firewalls don't really like repeated requests on the the same url and also the global performance of the process. 

Maybe the API is not the solution for that, I don't know, maybe a new feature in the admin UI would be better, no idea.
For example, modifying [this code](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/token.py) to allow the "user" field in the POST request to be a list of logins instead a single login, and the response to be a list of JSON responses instead of a single JSON response would be a great improvment for us.

**Comment by cornelinux** [comment]
Hello @cochennec,

thank you for your thoughts.
We will not do an API for that, since we can not clutter the interface.

There are already scripts for that. Of course you usually would have to check, if you need to use the API or the library level.
Take a look at that [scripts](https://github.com/privacyidea/scripts/blob/master/create-remote-and-spass.py) that works well in an environment with tens of thousands of users. I think slight modifications will also work for you.
