### ISSUE TITLE
Truncate Audit log entries by default

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2699]
We have the configuration option `PI_AUDIT_SQL_TRUNCATE` which truncates data fields before they are written to the audit table.
Since most databases don't like to write more data than fits into the specified column they return an error and the Audit-log-entry won't be written and thus won't show up in the audit log.
I recommend setting the option `PI_AUDIT_SQL_TRUNCATE` to `True` by default.

**Comment by cornelinux** [comment]
New installations could have this in pi.cfg as default.

**Comment by pablo-knight** [comment]
This line has already been implemented two years ago on ubuntu systems. Should this be done the same for Centos systems, because the "PI_AUDIT_SQL_TRUNCATE = True" is missing there.

https://github.com/NetKnights-GmbH/ubuntu/commit/c8ff8b23e117c15dec4d46c585af459e6180b6d7#diff-87ba292dbb79af0a07e22faae14baa3de7c81b4b33b64a52bf15dfb3f74cc774

**Comment by cornelinux** [comment]
Done in centos repo.

**Comment by cornelinux** [comment]
Add in documentation for pip install, that TRUNACE should be set.

**Comment by cornelinux** [comment]
Done in CentOS and docs
