### ISSUE TITLE
allow placeholders in eventhandler usernotification email reply-to

### ISSUE THREAD

**Issue by jroth-haj** [privacyidea/privacyidea#2711]
We are using Eventhandler / Usernotification / Action sendmail if a token is locked.
Please add support for placeholders for the users email of this token for the reply-to header.
So our ticket system can assign the user from the reply-to header.

**Comment by cornelinux** [comment]
@jroth-haj 
do you really need placeholders (because you probably do not want to put s.th. in there like the current date - which we have as tags/placeholders in the email body)...

...or do you actually need the same behaviour like with the "To" field, where you can select:

* tokenowner
* logged_in_user
* internal admin -> (choose names of internal admins)
* admin realm -> (choose admin realm)
* email -> (choose static email address)

I would see this as more appropriate.

**Comment by jroth-haj** [comment]
Tokenowner (Email) in the Repy-To Header would be enouhg Form pur use case.
