### ISSUE TITLE
Push without firebase

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2720]
In order to use push without firebase, the SMS-gateway definition must allow empty fields for the firebase values, leaving only the following attributes as required fields:

* registration URL 
* time-to-live

Moreover, the rollout QR code should then be generated without the firebase values.

Maybe we do not need the SMS provider at all and we can simply do *Poll-Only* if no PushProvider is defined.

**Comment by cornelinux** [comment]
We try this in 3.6.

**Comment by cornelinux** [comment]
# Variant A: Easy setup without push gateway

In the enrollment policy we can enhance `push_firebase_configuration` with an entry like "poll-only". (Similar to `passthru` policy being either default "userstore" or one of the configured radius configs)

![image](https://user-images.githubusercontent.com/1908620/118646800-f1aaec00-b7e0-11eb-9dfe-53209e1ad972.png)

However, we would need the `registration_url` (and ttl). 

We could have this in the token configuration like this:

![image](https://user-images.githubusercontent.com/1908620/118647359-8ca3c600-b7e1-11eb-967c-476896419d50.png)

# Variant B: Firebase Gateway without the firebase

We could however define a firebase gateway, which does not contain any firebase:

![image](https://user-images.githubusercontent.com/1908620/118647557-c2e14580-b7e1-11eb-9555-06d80e736108.png)

This might look a bit awkward, since the SMSGateway "Firebase" would actually not use at all any firebase.

**Comment by cornelinux** [comment]
We also need to add a migration script:

The URL and TTL need to be moved from the FirebaseConfig to this very policy, that contains this FirebaseConfig.
