### ISSUE TITLE
push tokens get triggered when disabled

### ISSUE THREAD

**Issue by droobah** [privacyidea/privacyidea#2723]
### Top-level intent

A handful of our users were having issues with push tokens and were temporarily switched to SMS tokens.  Their push tokens were set to be disabled.   The users were also using the same PIN for their SMS and Push tokens out of convenience.

### Steps to reproduce

1.  Assign a user a push token and set the PIN
2.  Assing a user a second token with the same PIN which could be SMS/Email or any other challenge/response token
3.  Disable the push token

### Expected outcome

Push token would be ignored and SMS token would be used for challenge/response.  The push_wait policy would be skipped and the push tokens would not be triggered as they are in a disabled state.

### Actual outcome

Push token is still triggered and the user must wait until the push_wait timeout expires before receiving/being prompted to enter the tokencode from their SMS/Email/etc

### Configuration

* **privacyIDEA version**: 3.5.2
* **Installation method**: Ubuntu Packages
* **Python version**: 3.5.2
* **Operating system**: Ubuntu 18.04 LTS
* **Webserver**: Apache
* **Token database**: MySQL

**Comment by cornelinux** [comment]
This happens in `check_token_list`.

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2144

We enter this function actually also with disabled tokens. We do this on purpose, so that - if a token is disabled on the server side - but a user uses e.g. the valud OTP value of the disabled token, this OTP value is compromised and must be validated by the server. For this reason the check for disabled tokens is only done *after* authentication happens.

It looks like that in case of a push token this means, that the check blocks the token loop. 
So we would have to additionally check, whether the push token is disabled.

We could also add a class attribute to tokentypes that says: "This tokentype must be checked, even if it is disabled".
We could then in `check_token_list` clean the to-be-checked token list of these tokens, where such attribute would be false, just like we do for revoked tokens:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2186

~~~~python
tokenobject_list = [token for token in tokenobject_list if (not token.is_active() and token.check_if_disabled)]
~~~~

**Comment by cornelinux** [comment]
All other disabled challenge-response tokens are already handled here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L2382
