### ISSUE TITLE
Add documentation for nginx plugin

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#275]
Daniel wrote an nginx plugin.

Add a link in the application plugin documentation.

https://github.com/dhoffend/lua-nginx-privacyidea
https://github.com/privacyidea/privacyidea/tree/master/doc/application_plugins

**Comment by dhoffend** [comment]
A bit of documentation aka configuration example is available in the README.md as well as which debian packages are required. 

https://github.com/dhoffend/lua-nginx-privacyidea/blob/master/README.md

I tried to keep it simple and use most of the available nginx lua functions and keep them amount of external libraries at a minumum. That's what the hash of the credentials is only sha1_hmac instead of something better. If you need higher encryption you just have to include other openresty modules and replace the password_hash/verify functions.

**Comment by cornelinux** [comment]
Yes, the sphinx doc I would put it here:
https://github.com/privacyidea/privacyidea/tree/master/doc/application_plugins
This way privacyIDEA users will hopefully easier be able to find this plugin.

**Comment by cornelinux** [comment]
closed by #276
