### ISSUE TITLE
rollover does not work with tokens which are in clientwait state

### ISSUE THREAD

**Issue by laclaro** [privacyidea/privacyidea#2763]
A token rollover is an token/init request using the serial of an existing token.

In case of a token with tokeninfo "clientwait", this will fail with "ERR905: 2stepinit is only to be used in the first initialization step."

This affects hotp, totp and push tokens.

**Comment by cornelinux** [comment]
This is probably due to the `tokeninfo`, that contains the information that the token is in the 2nd enrollment step.
This info is not deleted/removed after the token is enrolled.

So before rolling over such a token, this `tokeninfo` has to be deleted.

**Comment by cornelinux** [comment]
Hm, I *was* actually able to rollover an HOTP token with 2step enrollment (via "allow", did not test "force", yet).
It also makes sense to me. Since while investigating for #2784 I saw in the code and checked in the database, that the `rollout_state` is reset after the token is successfully enrolled.
So I am not sure, what the problem actually is.

@laclaro can you please explain, what you are trying to do here?
(Or course you can not rollover a token, where the 2step enrollment was not finished in the first place).

**Comment by cornelinux** [comment]
I think what we might try to do here is, to rollover a token that is actually in "client_wait", since it was not readily enrolled.

Like: The user forgot to enter the client component and now has a not-working token. 
Thus the user goes to "rollover" to reenroll the token. 
This would actually be a scenario, which also makes sense.
