### ISSUE TITLE
Content-Type x-www-form-urlencoded for POST not considered

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2800]
The body of a POST request which has the Content-Type application/x-www-form-urlencoded is url encoded. It seems that it is not considered by the server because the body is not decoded and therefore the requests result in failure.

**Comment by cornelinux** [comment]
The problem seems to arise, that we usually expect application/json, which we do not need to decode.

We might need to check whether we receive a request as application/x-www-form-urlencoded and would need to decode these data.

Looks like we have to decode the parameters here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/lib/utils.py#L246

were we combine all type of paramters (json-body, form-params) to our new dict ``request.all_data``.

**Comment by plettich** [comment]
Interesting, i just stumbled upon this issue in the tests when updating Flask/Werkzeug. So it might be a good idea to check for `application/x-www-form-urlencoded`.

**Comment by cornelinux** [comment]
@plettich I am not sure, should we only unquote, if the content type is **really** urlencoded, or should we always unquote.

~~~~python
def get_all_params(request):
    """
    Combine parameters from GET and POST requests
    """
    param = request.values
    body = request.data
    return_param = {}
    for key in param.keys():
        return_param[key] = param[key]
        if request.content_type.lower() == 'application/x-www-form-urlencoded':
            return_param[key] = unquote(param[key])
~~~~

**Comment by plettich** [comment]
> @plettich I am not sure, should we only unquote, if the content type is **really** urlencoded, or should we always unquote.

I am not sure about the quoting but in my case these parameters were only available in `request.form`:
https://stackoverflow.com/a/16664376/7036742

**Comment by cornelinux** [comment]
Interesting. We always since ever read data from `.values` and `.data`. Maybe some enhancements in versions.
