### ISSUE TITLE
Connection reject does not work as expected when running freeradius as a service

### ISSUE THREAD

**Issue by imennodenis** [privacyidea/privacyidea#2818]
Hi!
I'm using a fresh install of PrivacyIDEA 3.6 on Ubuntu 20.04.
I have configured  "TIMEOUT = 30 " parameter in /etc/privacyidea/rlm_perl.ini.
When I test freeradius with "freeradius -X" command everything works as expected so if I ignore (or press Decline button) push request on my phone then my connection attempt is rejected after ~30 seconds (or right after pressing Decline button).
But when I start freeradius as a service my connection attempt continues for ~1min 30sec before my connection attempt rejects (even if I press Decline button).
If I press Allow button everything works as expected in both cases.
What could be the reason of that?
Thanks!

**Comment by laclaro** [comment]
Hi,

thank you for asking that question. The timeout with push and radius is complicated since you have several requests, several timeout-loops (RADIUS-Client, FreeRADIUS, privacyIDEA Plugin, Webserver, privacyIDEA Server, general tcp ttl). However, since this is the developer-issue tracker, I invite to ask your question at https:/community.privacyidea.org/. If it turns out that your problem is indeed a bug, we will open a new issue.

Best regards,

Henning Hollermann
