### ISSUE TITLE
Check TAN

### ISSUE THREAD

**Issue by katgirl** [privacyidea/privacyidea#2842]
When creating TAN tokens, it would have to be checked whether the TAN is already being used by the user on another TAN list.
Otherwise, when checking the TAN on several lists, a True will go back, which is handled incorrectly in the event.

**Comment by plettich** [comment]
Hi @katgirl i am not quite sure if i understand this correctly. Creating a TAN token creates a list of OTP values (TANs) which can be used for authentication. So if a user has two TAN tokens, he has two separate lists of OTP values (TANs).
These lists should not contain the same values (well, since there is a finite space of 6-digit numbers there might be equal values on both lists but this is very unlikely).
If a user has two TAN-lists, both will be checked if they contain the value. If this is the case, "true" will be returned. If the value can not be found on either of the lists, it returns "false".
