### ISSUE TITLE
No PIN field for Admin Rollover 

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#2886]
If an admin does a token-rollover for a user, no PIN field will be shown. The admin only ever sees a PIN field when enrolling tokens (admin PIN policies) or assigning users to tokens (which PIN policies apply then?).
A user PIN policy will be ignored for an admin rollover.
A rollover will fail if an admin PIN policy is set (even though the admin won't see a PIN field).

**Comment by cornelinux** [comment]
Is this the intended behaviour? Does it currently work differently? Please describe.

**Comment by cornelinux** [comment]
@plettich I think if an admin does a token rollover, I would not expect them to *change* the PIN of the token. 

Ah, ok, but if a PIN policy is set, it fails? I would consider this a bug. 
My expectation would be:
* The admin can not set a PIN (since e.g. the user had set a PIN, which the admin does not know)
* No new PIN is set, the old PIN is unchainged. 

We probably need to pass this information that it is a rollover and the PIN policy is not checked. Maybe we can identify this by the existing serial number...
