### ISSUE TITLE
The AES security module should also encrypt empty strings

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#2899]
Currently the aeshms module does not encrypt empty strings.
It is not clear, if this has any relevance or any impact on functionality.
Check it and fix it.

**Comment by plettich** [comment]
According to the current PKCS#11 spec, the `C_Encrypt` function with the `CKM_AES_CBC_PAD` method should allow any input length: https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061242
However tests with [SoftHSM](https://www.opendnssec.org/softhsm/) (due to the lack of a real HSM with `AES` capabilities) produce an error.
It is unclear, if the function would ever be called with empty data so i guess we could live with an error here.

**Comment by cornelinux** [comment]
We need a working error handling, since in some cases we might e.g. have an empty password and we need to save "something", so that later the empty password (e.g. of an LDAP resolver) can be used.

**Comment by plettich** [comment]
> We need a working error handling, since in some cases we might e.g. have an empty password and we need to save "something", so that later the empty password (e.g. of an LDAP resolver) can be used.

We could get rid of the weird and not very intuitive password settings in case of an error:
https://github.com/privacyidea/privacyidea/blob/2a66d4792289424e0643178bd902a2e6e5f96482/privacyidea/lib/crypto.py#L350
https://github.com/privacyidea/privacyidea/blob/2a66d4792289424e0643178bd902a2e6e5f96482/privacyidea/lib/crypto.py#L319

This way the admin gets a direct response when something went wrong while saving the password.
