### ISSUE TITLE
Push challenge is not created when ERR401: Failed to submit message to firebase service occurs

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/privacyidea#2904]
For push to work without firebase, the push challenge should be created even if firebase is unavailable (or there is a firebase token mismatch etc.). That way, the smartphone can still poll the challenge directly and answer it without firebase being involved.
Currently, the server returns
{"detail": null, "id": 1, "jsonrpc": "2.0", "result": {"error": {"code": 401, "message": "ERR401: Failed to submit message to firebase service."}, "status": false}, ...
in that case.

1. The challenge is not created and cannot be polled by the smartphone.
2. The plugin does not know (even if the challenge was created on the server side) that it should offer push as a login method.
3. Other challenges are not sent either, this problem completely blocks the login with challenge-response type token.

**Comment by cornelinux** [comment]
This happens here:
https://github.com/privacyidea/privacyidea/blob/a89b0dabed312e8b9d1e3b343f9a27573fc86524/privacyidea/lib/tokens/pushtoken.py#L866
and here
https://github.com/privacyidea/privacyidea/blob/a89b0dabed312e8b9d1e3b343f9a27573fc86524/privacyidea/lib/tokens/pushtoken.py#L873

The tokens Email and SMS actually only raise an exception if the options/parameter "exception" is given.
See here: https://github.com/privacyidea/privacyidea/blob/2b075edc8ff0f4f481de4c36411dc648f114ce01/privacyidea/lib/tokens/emailtoken.py#L253

Otherwise they simply pass and write to the log file.

I think the same behaviour for the `ValidateError` in the pushtoken case makes sense.

**Comment by cornelinux** [comment]
@nilsbehlen The problem is, we have no interactive message for the user. Should we add the note, that the submit to firebase failed, add to the challenge text?

**Comment by nilsbehlen** [comment]
I think adding that submitting the message to firebase failed to the challenge-message is not very helpful for the user who sees the message. You could add something to the message that hints users to use the poll function to get the authentication request and just log the "submitting the message to firebase failed" for administrators

**Comment by cornelinux** [comment]
That is a good idea. Done in 8aabcc3f
