### ISSUE TITLE
Policy selfservice totp Google auth  asks for PIN

### ISSUE THREAD

**Issue by cuph62** [privacyidea/privacyidea#311]
We only have users from AD userresolvers
I have created this policy to simplify "Enroll a token" for Google auth to the max,
(we would like only a button "Enroll" without any options at all.)

| self1_srvc      | user           | { "totp_hashlib": "sha1", "totp_timestep": "30", "auditlog": true, "totp_otplen": "6", "enrollTOTP": true, "totp_force_server_generate": true, "delete": true } |

What's the purpose of the "PIN" that gets asked in the "Enrollment" ?

![enroll1](https://cloud.githubusercontent.com/assets/13996396/12234594/661776f8-b86e-11e5-85e0-b9ad6a080ce6.jpg)

**Comment by cornelinux** [comment]
This is the token PIN, that is used for authentication as the first factor of knowledge.

There is no easy way to hide this based on authentication policies, since the authentication policies are also depending on the client IP.

Even if you configure scope=authenticatoin, otppin=userstore, there might be another policy for other client IPs requiring a PIN.
