### ISSUE TITLE
Probably missing url encoding in TiQR URL

### ISSUE THREAD

**Issue by lferrarotti74** [privacyidea/privacyidea#3121]
Hi all,

as mentioned in the community [https://community.privacyidea.org/t/tiqr-token-reflections-and-possible-improvements/2434](url), could be that the actual process in generation of the QR Code needs to be a little bit improved.

Based on the documentation a QR code need to have this schema :

`tiqrauth://[<identityIdentifier>@]
<serviceIdentifier>/
<sessionKey>/
<challenge>[?<return Url>]`

Analyzing the code here : [privacyidea/tiqrtoken.py at master · privacyidea/privacyidea · GitHub](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/tiqrtoken.py#L430)

I find out that at the end inside the QR code is also present the “service_displayname”. As in the WebUI in PI is not prevented the usage of white spaces (TiQR Service Displayname under Config → Tokens → TiQR), in case of the presence of white spaces the QR Code is generated with those present and as per result an error in authentication. 

Just checked adding a dash instead of the space. In this case the auth is working prefectly.

So making a small change in the PI code mentioned before and using “service_identifier” in this line [privacyidea/tiqrtoken.py at master · privacyidea/privacyidea · GitHub 2](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/tiqrtoken.py#L435) instead of “service_displayname”, the problem described before using the Mobile App is not present anymore and the authentication process is working perfectly and always with positive results.

Many Thanks & Best Regards,
Luca

**Comment by cornelinux** [comment]
I think we need to check if

a) we really need to put the `service_identifier` in the URL of the qr code or
b) if we need to urlencode it anyways.

**Comment by lferrarotti74** [comment]
Your doubts are for sure right and valid. 
My findings are coming from an analysis using the only Mobile App that I know present, at least in Apple Store world, and available if you want to play with this kind of Auth Token.
Could be that a different and custom App Token can react in a different way, but at the moment I cannot confirm that.
At least with this mobile App and after the analysis of the QR Code provided from the [tiqr demo website](https://demo.tiqr.org) , with mine suggested enhancements the App was super happy.
In theory also without the `service_identifier` is supposed to be working, except some complaints from the App itself.
Also this latest part was tested by me and working.
So probably your point a) would be the best approach for being more flexible in the future. But I can also be wrong.

**Comment by NNLemling** [comment]
We had a problem with IOS that if the display name contained spaces, the authentication was unsuccessful because spaces were contained in the url. This was our mistake as this is inherently correct behavior as spaces should not be included in a url.

After we encoded the displayname we noticed the following:

- On IOS everything works as expected. Authentication successful, the string is encoded and the display name is displayed in the APP with spaces. `My Service Name`
- With Android, however, the encoded string is displayed as the display name in the app. `My%20Service%20Name`

Strangely, Android was able to process the spaces and display them correctly without encoding. However, the authentication with IOS then failed.

We will keep the changes in ea721dc5f764b266d6c4a44486fe556d3dbdd8ae for now. The behavior is correct. Currently the display name is shown under android encoded. 
However, this problem is not ours, which is why I opened an issue at SURFnet.
(https://github.com/SURFnet/tiqr-client-android/issues/156)

If this bug is fixed at some point, we won't have to make any changes again.
