### ISSUE TITLE
ImportException is not a subclass of privacyIDEAError

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3131]
The `ImportException` (thrown when something happens during token import) is not derived from the `privacyIDEAError` class which leads to a `500` Error in the WebUI if the import fails due to an error.
We could just derive it from `privacyIDEAError` and give it an `id`, this should give more meaningful error messages in the WebUI.

**Comment by NNLemling** [comment]
**Fixed in:**

- [ ] adjust importotp tests 4405637f268b7b7d3d4e3b59d2b8f9fa0e2ac524
- [ ] import TokenImportException class to `privacyidea/lib/error.py` 1b01d7ee06186b9c87164e8c2f128feca458a994
- [ ] remove ImportException class from `privacyidea/lib/importotp.py` 6d0757722d09694153a18d3320fd6e199bdfb710
