### ISSUE TITLE
key_enc field too small (cannot register tpm-fido as WebAuthn token)

### ISSUE THREAD

**Issue by melanger** [privacyidea/privacyidea#3137]
### Top-level intent

Register [tpm-fido](https://github.com/psanford/tpm-fido/) as webauthn token

### Steps to reproduce

1. Add webauthn token
2. use tpm-fido

### Expected outcome

Token is added.

### Actual outcome

Server error occurres, because `key_enc` field of the `token` table is too small. 

https://github.com/privacyidea/privacyidea/blob/cb59ea363b25a2154a6c26ba35f1005a592d0b3b/privacyidea/lib/tokens/webauthntoken.py#L863

https://github.com/privacyidea/privacyidea/blob/7295cf019f898949e5b18d01a4db9aade0532692/privacyidea/models.py#L300

The value is webauthn token's credential_id, [hexlified](https://github.com/privacyidea/privacyidea/blob/cb59ea363b25a2154a6c26ba35f1005a592d0b3b/privacyidea/lib/utils/__init__.py#L206) and [encrypt](https://github.com/privacyidea/privacyidea/blob/7295cf019f898949e5b18d01a4db9aade0532692/privacyidea/lib/crypto.py#L360)ed (which means hexlified again). credential_id can be of arbritrary length in [WebAuthn v2](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#dom-publickeycredential-identifier-slot), current draft of [WebAuthn v3](https://w3c.github.io/webauthn/#credential-id) proposes limit of 1023 bytes. Currently the `key_enc` column of privacyIDEA has only 1024 character limit, which is too small even for shorter credential_ids (credential_id of length 214 is too long).

### Configuration

* **privacyIDEA version**: 3.7
* **Installation method**: pip
* **Python version**: 3.9
* **Operating system**: does not matter
* **Webserver**: does not matter
* **Token database**: PostgreSQL

### Log file

```
Exception on /token/init [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1024)
...
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(1024)
[SQL: UPDATE token SET key_enc=%(key_enc)s, key_iv=%(key_iv)s WHERE token.id = %(token_id)s]
```

**Comment by cornelinux** [comment]
This would mean making the `key_enc` DB column longer.

**Comment by plettich** [comment]
There is an unnecessary hexlification here:
https://github.com/privacyidea/privacyidea/blob/00da9e4ee3a813ed5a992530f7ba1351209cb4c5/privacyidea/lib/tokens/webauthntoken.py#L869
https://github.com/privacyidea/privacyidea/blob/00da9e4ee3a813ed5a992530f7ba1351209cb4c5/privacyidea/lib/tokens/webauthntoken.py#L793
By removing this, we could increase the possible size of the `credential_id` to 511 bytes due to another hexlification during our internal padding:
https://github.com/privacyidea/privacyidea/blob/9371bdc61f780f38431753c31186d78b4f7fdba8/privacyidea/lib/security/default.py#L410
When using PKC7-padding we could achieve the 1023 byte size for the `credential_id`.

On the other hand we could also save the `credential_id` in the tokeninfo table with a `password` type. This way it is still encrypted and the `Value` column in the tokeninfo table is unlimited.

**Comment by plettich** [comment]
If we remove the additional hexlification in the code we won't be able to use older WebAuthn tokens since we would get a wrong `credential_id` from the token.
We would need a special migration script to decrypt the otpkey in the Flask app-context, remove the additional hexlification and encrypt it again.

**Comment by cornelinux** [comment]
I would try to keep the credential_id at one place (e.g. the key_enc). 
I think also for support it is a bad idea to sometimes store the credential_id in one place (key_enc) or another place (tokeninfo).

Thus we might need to enlarge the DB field definitino `key_enc`.

**Comment by cornelinux** [comment]
Increase the column width. Please check, if e.g. 2048 -> 4096 would be sufficient.

**Comment by plettich** [comment]
Currently the `key_enc` column is set to 1024 chars: https://github.com/privacyidea/privacyidea/blob/be99398a8793dcea786f00322d242024d5e704aa/privacyidea/models.py#L187
If we want to support a `credentialId` length of 1023 (https://w3c.github.io/webauthn/#credential-id) we would need to increase the `key_enc` column to at least 2800 (.37 increase for base64 encoding and times two for the additional hexlification).
