### ISSUE TITLE
Helpdesk policy should disable the ¨modify realm button¨. (Action : resolverread )

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3149]
**Is your feature request related to a problem? Please describe.**
Trying to set up a helpdesk policy with helpdesk users that have no  rights to see  the resolver (Scope admin, Action : resolverread)
The helpdesk policy with no ´resolverread´ activated still display the button modify realm.

**Describe the solution you'd like**
When the helpdesk admin is on the page of Users, he shouldn't see the button ''modify realm''.

**Describe alternatives you've considered**
<---------------->

**Additional context**
<----------------->

**Comment by cornelinux** [comment]
Currently every adminsitrative role can read realms.
See
https://github.com/privacyidea/privacyidea/blob/38cde6e9028494a31aba3ac2eff91136def160e3/privacyidea/static/components/user/views/user.html#L45
I think I remember that this is technically necessary. I.e. if the admin does not have `resolverread` rights, the admin can still read the realms but can not read the resolvers.

So from a rights perspective it is logical that the "edit realms" link is visible, since the admin **can** read the realms. So even if the link was not present, the admin could still do a `GET /realm/` from an API point of view.

So I am really not sure, if we should do this, since it is only cosmetic.
