### ISSUE TITLE
Radius Token not working

### ISSUE THREAD

**Issue by John222** [privacyidea/privacyidea#316]
Hi guys when we try to setup a user with a "RADIUS" token, the request never is sent to the external radius server. We cannot see any network traffic. The server configuration have been added under Token->Radius

as message in the audit and when we try to authenticate through radius client locally always:

```bash
wrong otp pin
```

We are using privacyidea 2.9 under debian, installed from the ubuntu package store.

**Comment by cornelinux** [comment]
The RADIUS request is only sent if the pin is ok.
So the question is to check for the Pin.

Please check
* system wide PIN setting
* Policy pin settings
* Radius definition: pin locally or remote
* how many tokens has the user

**Comment by John222** [comment]
Hi. Where should be a "system wide PIN setting". I only saw the following configuration parameter in the webui "Prepend the PIN in front of the OTP value . Otherwise it will be post pended.". We do not have set any policies for pin settins. The pin should be remote validated, because we do not have marked the setting "radius.local_checkpin". We always trying with just one token assigned. The "RADIUS token".

**Comment by cornelinux** [comment]
Then this token is not allowed to have any PIN at all! Since *everything* is to be sent to the other RADIUS server.

**Comment by John222** [comment]
So in the webui while configuring the token or assign it to the user, there is no option to disable the pin setting. Do i have to do a policy for this?

Freundliche Grüsse/kind regards
Reto Rayen

**Comment by cornelinux** [comment]
You can either set an empty pin or create an authentication policy with otppin=none.

Kind regards
Cornelius

**Comment by John222** [comment]
As i can remember. We tried this with the policy. I am not sure anymore. I'm going to test it again..... When we assigned the **RADIUS TOKEN** we never entered a pin. Maybe the webui interprets the empty fields as a "" string an interprets this as a set pin.

**Comment by John222** [comment]
Ok. We tried with this policy **otppin=none**. But it didn't worked. The message "wrong otp pin" still appears.

**Comment by cornelinux** [comment]
Hello,
Are you running version 2.9? 
I know at least one installation where this is run successfully. So I guess something is misconfigured here.
Activate debug logs and take a look at privacyidea.log
https://privacyidea.readthedocs.org/en/latest/installation/system/logging.html?highlight=debug

Also please note the Google group.
https://groups.google.com/forum/#!forum/privacyidea

But I guess in your case you should take a look at services to help get up and running. 
https://netknights.it/en/leistungen/one-time-services/

I will close this issue, since it obviously does not have to do anything with the code itself.

Kind regards
Corneius

**Comment by cornelinux** [comment]
PS: I assume you are running a migration scenario from another system with RADIUS. So please consider dropping a note to netknights.

**Comment by John222** [comment]
Yes we are running the latest version 2.9. We are planning to running migration scenario when this would work.
