### ISSUE TITLE
Allow modification of base_url

### ISSUE THREAD

**Issue by adamboutcher** [privacyidea/privacyidea#3181]
**What are you trying to achieve?**
Allow admins to set base_url.

**Describe the solution you'd like**
A variable in the config file for base_url

**Describe alternatives you've considered**
Rewrites in nginx/apache however these do not work with email templates etc.

**Comment by cornelinux** [comment]
Could you please be a more elaborate about **what are you trying to achieve**?

Here are some example question - not all you need to talk about.
What are you understanding with base_url? 
For which sceanrio to you need this --- e.g. which scenario does not work out for you?

**Comment by adamboutcher** [comment]
I'm trying to run privacy idea via a Web proxy presented under a suddirectory.

Eg

Auth.example.com/otp

However the email templates don't support this and half the templating system breaks as they use absolute urls based on root eg /static/ vs simply static/

**Comment by cornelinux** [comment]
Please be more precise, what you are doing and what breaks.
You might also be mixing two issues here: webui and email-policies.

It is fully supported with all webui templates to run in a subdirectory.

So it seems to occur in conjunction with your webproxy. So you need to provide more input in regards what your webproxy is doing, what it changes.

Otherwise this is a wild guessing from our side!

**Comment by cornelinux** [comment]
The question **what are you trying to achieve** is ment as a top level question.
We try to understand concepts and implement concepts. So you need to explain your scenario and what your actual problem is.
