### ISSUE TITLE
Allow case insensitive usersnames in Policies

### ISSUE THREAD

**Issue by wwalker0307** [privacyidea/privacyidea#3281]
**Is your feature request related to a problem? Please describe.**
When configuring policy application to a user, the username must exactly match the case of the user store.

**Describe the solution you'd like**
Either remove case sensitivity or expose a setting to remove case sensitivity from a policy.

**Additional context**
Windows systems are not case sensitive and in moderately sized organizations, ensuring uniform creation of user account names can be difficult.

**Comment by cornelinux** [comment]
@wwalker0307 so case insensitivity only refers to usernames?
What about simply adding a checkbox, or even allow regexp in usernames?

**Comment by cornelinux** [comment]
We think this should be done in the policy checking, since this can be independent from user resolving.

So a checkbox in the policy if it should be independent or not.
Hm, this will be somewhere here in the Matching object:

https://github.com/privacyidea/privacyidea/blob/741e79052e44fcc89759e8dc43337f6579bcd61c/privacyidea/lib/policy.py#L2704
