### ISSUE TITLE
Realm name is case sensitive when login to the WebUI

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3329]
The login as an admin on the webGui is key sensitive.

Example:
 
xxxx@helpdesk => Login is functioning. User has the admin rights

xxxx@Helpdesk => Login is possible, but the user doesn't have the admin rights.

Privacyidea 3.7.3

* [ ] Fix login at webui (/auth)
* ~~[ ] We need check if the same problem exists in /validate/check or in other endpoints to identify the user~~
  This only affects the admin rights, the authentication in the realm works correctly. Realm are always lower case.

**Comment by cornelinux** [comment]
@sepp67 We use projects for weekly development. Do not add issues to projects. If you think so, add an issue to a milestone (which is the release). But release 3.7 is closed. ;-) 
So if you really would think (what I do not think so), that this needs to be fixed in a 3.7patch, move it there. But I will not add this to 3.7, since the impact is too big.
