### ISSUE TITLE
Missing sequence for `customuserattribute` table in migration

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3356]
When adding the `customuserattribute` table during migration, the sequence for the `id` is missing (needed by e.g. PostgreSQL):
https://github.com/privacyidea/privacyidea/blob/5cc92448833bf5de3bb0ab10cd669496cfcef7d0/migrations/versions/888b56ed5dcb_.py#L20
We should check if other tables added through migration scripts are missing the sequence definition.

**Comment by cornelinux** [comment]
We should create a new migrationscript and not modify the existing one.

**Comment by cornelinux** [comment]
Oh - there are a lot of tables, that do not have a sequence.
E.g. tokengroups! ;-) since it is not automatically created by `pi-manage db migrate`.

It would have to be added manually like here:
https://github.com/privacyidea/privacyidea/blob/07fd2e706a9c321f1bf70066f63664afb46b8e0c/migrations/versions/dceb6cd3c41e_.py#L31

First task:

* [ ] find all tables for which the `<tablename>_seq` is missing.

Then:

* [ ] Create one migration script to add the missing sequences.

**Comment by cornelinux** [comment]
Are these all tables?

~~~~shell
migrations/versions (git)-[2993/multichallenge_enroll] % grep "create_table" *
~~~~

The last sequences, that have been created:

~~~~
% grep "_seq'" *
48ee74b8a7c8_.py:        seq = Sequence('tokenowner_seq')
d756b34061ff_.py:        seq = sa.Sequence('eventcounter_seq')
dceb6cd3c41e_.py:            create_seq(Sequence('policycondition_seq'))
~~~~

**Comment by cornelinux** [comment]
It looks like(TM) that it is:

* customuserattributes
* tokengroup
* tokentokengroup
