### ISSUE TITLE
Writing audit-log fails when adding/updating a policy with multiple realms/resolvers

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3398]
When a policy is added/modified and the realm- or resolver-condition contains multiple entries the corresponding audit entry is missing and in case of a MySQL db an error is printed in the log about `"Data too long for column 'realm'"`.
We add the realm to the audit data here:
https://github.com/privacyidea/privacyidea/blob/8b2c2618361f113450630b680d419f2277a56edd/privacyidea/api/before_after.py#L193
and in case of multiple realms this entry is a list (which breaks when writing it to the db).
We could
1. convert the list to a string before adding it to the audit data
2. adjust the [`Audit.log()`](https://github.com/privacyidea/privacyidea/blob/34ddaf4352aae7ddaebcb1677102490655239eed/privacyidea/lib/auditmodules/base.py#L161) and [`Audit.add_to_log()`](https://github.com/privacyidea/privacyidea/blob/34ddaf4352aae7ddaebcb1677102490655239eed/privacyidea/lib/auditmodules/base.py#L176) functions to always convert the entries to a string
3. convert all non-string audit data to strings before [finalizing the log](https://github.com/privacyidea/privacyidea/blob/34ddaf4352aae7ddaebcb1677102490655239eed/privacyidea/lib/auditmodules/sqlaudit.py#L258).

**Comment by cornelinux** [comment]
Is the problem due to being a list instead of a string or is it the length of the field?
For the field-to-long we already have the PI_AUDIT_SQL_TRUNCATE.

So we might probably only need to convert the list to a string?
Which in turn might be not that straigtforward, since the audit log also does links to the resolvers and realms. So in this case we would also have to adapt the UI, like with the "multiple serial numbers" in the audit log (#3285)

**Comment by cornelinux** [comment]
closed by #3412
