### ISSUE TITLE
Check result of splitting PIN and OTP

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3467]
In some cases (multiple tokens for a user, one is a Yubikey in AES-mode) it happens that the split of PIN and OTP returns empty values which in turn create errors when binding to the LDAP-server with an empty password.
We could check whether the split was successful and return some kind of status value here:
https://github.com/privacyidea/privacyidea/blob/3f6ad403462d8147fbfe030210907fa911ad9438/privacyidea/lib/tokenclass.py#L1383

**Comment by cornelinux** [comment]
Well,  the pin splitting works as expected.
I think we first would have to define, what a correct/expected behaviour would be.

**Comment by plettich** [comment]
This happens when:
- PIN and OTP are entered together (could be mitigated using challenge-response) and
- the user has tokens with different OTP length (TOTP/HOTP with 6/8 and/or yubikey in AES mode)

This may lead to a wrong password being checked for the user.

**Comment by cornelinux** [comment]
Since the behaviour is correct, we should check if we should either check for empty passwords in the LDAP resolver password_check or maybe catch the specific exception to avoid data revelation.

We could also check within the AES-Mode token if the length of the password is to short for the OTP-length.

In both cases this should be treated as an invalid-PIN token.

**Comment by cornelinux** [comment]
I am adding a check for the length of the given password, so that the given password is not shorter than the expected OTP length of the token. This would be the case for

HOTP with otplen 6 and Yubikey with otplen 44/48.

So in this case we would have an early exit in case the user enters the 6 digit otp and the yubikey would exit with a wrong PIN from pin splitting and thus the PIN (AD password) would not be verified.
