### ISSUE TITLE
WSGI Settings

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3506]
When configuring a ms ca connector the wsgi will one day freeze if not used a global parameter. See .5.33.

**Comment by plettich** [comment]
It looks like the `mod_wsgi` is unable to run privacyIDEA with a sub-interpreter (which is the default) due to some C-Extension-Library (probably from the grpc module).
We need to run privacyIDEA in a Single-Application-Mode (which would make sense since privacyIDEA is generally the only wsgi-app running on that system):
https://modwsgi.readthedocs.io/en/latest/user-guides/virtual-environments.html#daemon-mode-single-application
So basically we would need to add `WSGIApplicationGroup %{GLOBAL}` to the privacyIDEA Apache config file.
Running several privacyIDEA instances works as well with these settings.

But if someone wants to run Django on the same server, they need to configure that themselves...

And i think we should add the `WSGIPythonHome /opt/privacyidea` entry to the privacyIDEA Apache config file. Or was there a specific reason to add it to a separate file?

**Comment by plettich** [comment]
RHEL8 uses Python 3.6 so we are on the safe side here. RHEL9 includes Python 3.9 so we need to check if we run into the same problem here.

**Comment by pablo-knight** [comment]
ToDo: build packages for Rhel9 [ ] @pablo-knight
