### ISSUE TITLE
Evaluate X-Forwarded-For HTTP-Header-Field if existing 

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#356]
Hello Cornelius,

when operating privacyidea behind a http proxy server (e.g. for load balancing and redundancy) privacyidea actually does not evaluate the X-Forwarded-For HTTP header and therefore sees all client requests (services and self-service-users) originating from the proxy server's IP address. Filtering for special IP address ranges via privacyidea policies then is not possible anymore.

Therefore - at the moment - it seems to be not possible to use privacyidea in a load balancing or redundancy scenario in combination with ip filtering policies.

It would be great for anyone to see this feature in one of the next privacyidea versions.

Best regard,

Bernd

**Comment by cornelinux** [comment]
Hi Bernd,
why not give it a try? We are open for pull requests!

This is the function, that is run before eacht request:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L109

You can see in line 109 that this is the client, that is at least written to the audit log.

Usually all policies are using the 

    request.remote_addr

like here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/lib/prepolicy.py#L118

I think there are two possibilities:

1. rewrite the request.remote_addr in the before-function or

2. define a new client value that is either filled with request.remote_addr OR with X-Forwarded-For in the before-function.

I would prefer (2) since it is more flexible in the future.

Regards
Cornelius

**Comment by cornelinux** [comment]
Note: You can also use the "client"-parameter in authentication requests! So your app could use this param.

**Comment by berndnicklas** [comment]
Hi Cornelius,

thanks for your advices! I already had a first look at the code and will give it a try next week.

Best regards,

Bernd

**Comment by cornelinux** [comment]
I already changed most of it. 

There are four locations where the client_ip is set in the before_request:
https://github.com/privacyidea/privacyidea/blob/80c416b40e17314c7732da01aeb14e82983ae42f/privacyidea/api/ttype.py#L71
https://github.com/privacyidea/privacyidea/blob/80c416b40e17314c7732da01aeb14e82983ae42f/privacyidea/api/validate.py#L99
https://github.com/privacyidea/privacyidea/blob/80c416b40e17314c7732da01aeb14e82983ae42f/privacyidea/api/before_after.py#L100
https://github.com/privacyidea/privacyidea/blob/80c416b40e17314c7732da01aeb14e82983ae42f/privacyidea/api/auth.py#L80

It could be in 

    request.environ.get("X-Forwarded-For")

could be something like this:

    g.client_ip = request.environ.get("X-Forwarded-For") or request.remote_addr

But you could also create a function that does the trick and also define some config settings, if X-Forwarded-For should overwrite the remote_addr.
