### ISSUE TITLE
Add a policy action to disable private key checking

### ISSUE THREAD

**Issue by kkalev** [privacyidea/privacyidea#3590]
We are using push tokens to authenticate  users. The `/triggerchallenge` endpoint calls the `create_challenge()` function in `lib/tokens/pushtoken.py`. This function calls `_build_smartphone_data()` which among other things uses `load_pem_private_key()` to load a per token private key.

Profiling `create_challenge()` for execution time showed that more than 200 msecs are consumed inside `_build_smartphone_data()` with mostly all of them inside `load_pem_private_key()`. Based on this [issue](https://github.com/pyca/cryptography/issues/7236) we tested the following code (a loop of 1000 calls to the function):
```
from cryptography.hazmat.primitives import serialization

for _ in range(1000):
    with open("key.pem", "rb") as key_file:
        private_key = serialization.load_pem_private_key(key_file.read(), password=None)
```
with a total execution time of `29.089s`.

Based on suggestion in the above issue we also added the following on the above code:
```
from cryptography.hazmat.backends.openssl import backend
backend._rsa_skip_check_key = True
```
which resulted in a reduction of total execution time to **0.5 secs**. The same was true if disabling key checking in `_build_smartphone_data()` with a drop of execution time to a few msecs.

Benchmarking the endpoint with and without key checking resulted in a throughtput of 3-4 reqs/sec vs 20-30 reqs/sec depending on concurrent requests. CPU usage was 100% in the first case after 16 concurrent request while it typically remained **below** 100% when key check was disabled. We are talking about an order of magnitude improvement.

Since the private key is created by privacyIDEA itself when a token is enrolled, we would like to suggest that a policy action is added to allow for the key checking to be disabled if desired by the administrator.

Thank you for your time

**Comment by cornelinux** [comment]
We could revert the logic due to #3604 and define a policy that explicitly *enables* key checking.

**Comment by plettich** [comment]
We have several places where we load private key files:
- The [PUSH-Token](https://github.com/privacyidea/privacyidea/blob/4092a8b70bad077f740134efbdb9a1ea5fce715a/privacyidea/lib/tokens/pushtoken.py#L204)
- The [Sign-object](https://github.com/privacyidea/privacyidea/blob/d4903c388f7aab3ebd813d0350cd58b5f28472e7/privacyidea/lib/crypto.py#L709), which is used for
  - signing the Response (can be deactivated with `PI_NO_RESPONSE_SIGN`)
  - signing the Audit-Log (can be deactivated with `PI_AUDIT_NO_SIGN`)
  - checking the subscription (only `load_pem_public_key()` is used)
- The [MSCA CAConnector](https://github.com/privacyidea/privacyidea/blob/dd383d87b00e47cb23fdc922700b8977154d1b2f/privacyidea/lib/caconnectors/msca.py#L171)

All those private keys come from a secure location. If an attacker gains access to the filesystem, the whole system should be regarded as compromised.

For the PUSH-Token this should be straight forward.
For the `Sign` object i propose an extra parameter since we do not know where this object might be used in the future.

**Comment by cornelinux** [comment]
We disable private key checking during loading for PUSH always! fixed code!

As we have a similar problem with Audit log, but since the audit sign key could originate from an external source, we add a pi config key:

`PI_AUDIT_NO_PRIVATEKEY_CHECK`.
