### ISSUE TITLE
TOTP: Time Step 60 doesn`t work with Google- /Microsoft-Authenticator

### ISSUE THREAD

**Issue by regnilor** [privacyidea/privacyidea#3634]
TOTP with a choosen time step of 60 sec. doesn`t work neither with Google- nor with Microsoft-Authenticator. It does fine with privacyIDEAAuthenticator. 

My suggestion is to mention this problem in the WebUI-Text and to point out the privacyIDEAAuthenticator, which works fine.
I`ve done this in the german translation via weblate.org, at the price of not fitting exactly the english text. I would be pleased if the hint founds its way into the original text.

**Comment by cornelinux** [comment]
I think we should change the recommendation text in the UI to use the privacyIDEA authenticator.

It is MS Auth or Google Auth fault to not support other timesteps, accept the URI and simply ignore not supported parameters. These totally suck. 

# Todo

* [ ] change the text in here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.hotp.html#L5 
* [ ] https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.totp.html#L5


Otherwise we end up with noting restrictions for all crappy apps like here:

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.hotp.html#L54

https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/components/token/views/token.enroll.hotp.html#L67

We might change this to s.th. like "Other apps like GA might not support SHA256, SH512 or ... other digits or anything sensible".
