### ISSUE TITLE
Set `g.logged_in_user` during successful `/auth` request

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3710]
When an authentication is successful we could set the `g.logged_in_user` to be able to use it in a POST-event handler (See #3676 )

**Comment by cornelinux** [comment]
OK, I see that `g.logged_in_user` is only set when the JWT auth token is verified successfully:

https://github.com/privacyidea/privacyidea/blob/752a1f95bfc9e052f73ab021483b422a351578ec/privacyidea/api/auth.py#L438

This of course does not occur in the /auth request itself.
The even handler could also check (as a condition) for the JWT, or we add the `g.logged_in_user` to the request object here, when we also create the JWT:

https://github.com/privacyidea/privacyidea/blob/752a1f95bfc9e052f73ab021483b422a351578ec/privacyidea/api/auth.py#L379

~~~~Python
    token = jwt.encode({"username": loginname,
                        "realm": realm,
                        "nonce": nonce,
                        "role": role,
                        "authtype": authtype,
                        "exp": datetime.utcnow() + validity,
                        "rights": rights},
                       secret, algorithm='HS256')
    g.logged_in_user = {"username": loginname, "realm": realm, "role": role}
~~~~

This should be simple, since all data is actually available for the JWT and later it is actually read from the JWT.

I think we can add this one-liner still to 3.9.
