### ISSUE TITLE
Some translated strings do not display actually translated

### ISSUE THREAD

**Issue by gryffus** [privacyidea/privacyidea#3721]
* **privacyIDEA version**: 3.8.1
* **Installation method**: PyPI
* **Python version**: 3.9.2
* **Operating system**: Debian 11
* **Webserver**: Apache/2.4.56
* **Token database**: PostgreSQL

I have noticed, that some translations are always showing original english text only, despite already translated. For example:

https://github.com/privacyidea/privacyidea/blob/4271b06d27d364adb458a71b30bebfb5181ece04/privacyidea/translations/de/LC_MESSAGES/messages.po#L2645

I tried with multiple languages, but this exact message is always shown in english, no matter what. There are more, but let's take this as an example.

Is there anything I can do to debug this further? I have done some contributions on weblate lately and I would like to help with Czech language at least.

**Comment by plettich** [comment]
Hi @gryffus
thanks for the heads-up and Your effort.
Updating the translation is currently a rather manual process. We need to extract and commit the marked strings and let weblate pull the changes. If some strings have been translated, weblate issues a pull request and then we have to compile the translation before packaging.
The specified translation is used, when a request with a `Accept-Language` header is received.
In this particular case i can confirm, that the translation is not used. I'll have to dig deeper for this...

**Comment by plettich** [comment]
It looks like we have to *lazy* evaluate these strings since they are constants (there are a few more in the code). We'll need to make some changes on how the translation is built.
- [ ] make `lazy_gettext()` available (like `_()` here: https://github.com/privacyidea/privacyidea/blob/9753edf49f6e5d60952abe6370d23aa399eef9f7/privacyidea/lib/__init__.py#L21)
- [ ] check python code where translations are used in constants or class variables
  - https://github.com/privacyidea/privacyidea/blob/9cbf551a6837ced492da9e2dd86e46432d77852f/privacyidea/lib/smsprovider/SMSProvider.py#L76
  - ...
- [ ] update `pybabel extract` call to include `lazy_gettext`
