### ISSUE TITLE
additional condition in Events Handler

### ISSUE THREAD

**Issue by mont2fa** [privacyidea/privacyidea#3726]
Hello,
Can you add a new condition 'user_token_type' to this section 
'Config - Events - Create new Event Handler
Handlermodule - Token
Condition tab - user'
with the ability to specify the type of token - sms, email, totp and others?
and if this 'user_token_type' condition is active and a token type is selected, 
then the Action is triggered when another condition 'user_token_number' is active and equal to the number of assigned tokens of the specified type, not all tokens
Thanks

**Comment by cornelinux** [comment]
I am not sure, if I understand you correctly. 

But this is not how the conditions work!

A tokentype condition does exist. The condition is checked during the API call. This means, the API call must be done for a token of that *type*.

What you seem to want, is that an action is only performed on certain tokentypes, but you do not want to use it as a *condition*.

We will not do this, since it would mix up the conditions and the actions and would result in to much confusion.

If you want to act only on certain tokentypes of a user, you need to use a script handler.

**Comment by mont2fa** [comment]
I would like to be able to set the number of tokens with particular tokentype as a condition for certain user when the user logs in.
