### ISSUE TITLE
Token limit error phrasing

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#3834]
When it comes to assign a token after the user has met the token limit/maximum.
 
That process being:

    User logs into PrivacyIDEA webui
    They click "Assign [Hardware | Software] Token"
    Click "Enroll Token"

If the user has met the limit, they receive an error of "The number of tokens for this user is limited!"

![imit of token](https://github.com/privacyidea/privacyidea/assets/95854213/cc928043-37e7-4d68-9ad0-34bfe2e70e36)

That message is ambiguous to end users, limited to how many?
Is this a standard limit or has their account been limited entirely?
Furthermore, it's not clear what they should do to fix this or if they even can do anything.
A better message would be something like "the maximum number of tokens is 3, a token must be unassigned before a new one can be created".

**Comment by cornelinux** [comment]
You think this is a nice error message:

"A token must be unassigned before a new one can be created".

Well, others might think an error message like

"You must delete a token, before you can assign a new one".

Or

"Please delete a token, before enrolling a new one".

You do not know, if the user should delete or unassign a token. You do not know if a user assigns or enrolls a token.
So This does not make sense to me.

If we would respond to this, we can turn in circles again and again, since there always can be a different arguemnt.

Also: The logic to tell if the token is limited to 3 is to complex.

The user could be limited to 2 hotp and 1 totp token. If the user tries to enroll a 2nd totp token how should the error message then look like:

"You already have enrolled 1 totp token. Your totp tokens are limited to 1. But you only have 1 hotp token enrolled. You may enroll a 2nd hotp token or otherwise delete or unassign your totp token before enrolling a new totp token.

=> This error message stays at it is.
