### ISSUE TITLE
WebAuthn offline refill

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3857]
A WebAuthn Offline Token can be used offline and online.
It can even be used offline on several machines.

However, currently the refilltoken for webauthn does not work correctly, since the refilltoken is not bound to a machine.
Also with online webauthn auth the refilltoken gets regenerate.

Thus we need to improve the webautn refill mechanism this way that:

a) an online authentication ignores the refill aspect and does not generate a refilltoken
b) we have a desctinct refilltokens for several offline notebooks **or** all offline occurrances of one WebAuth Token use the same refilltoken.

We could assume that the computer name in the windows domain is unique, so we could use the computer name (in the user agent?) as identifier.
This ensures, that the admin can also understand which notebooks (by the computer name) currently have a webauthn offline token.

**Comment by cornelinux** [comment]
privacyIDEA needs to know the machine identifier, which could be the machine name. This could be sent via the user agent in the HTTP Header.

If we put the machine name in the header, we need to ensure, that the user agent handling in the subscription handling works right. 

This should work since already implemented in #3800 and PR #3801

**Comment by nilsbehlen** [comment]
Useragent will be `privacyidea-cp/3.5.0 Windows/laptop-tsrtm3jc` where `laptop-tsrtm3jc` is the computername as returned from `GetComputerNameW`.

**Comment by nilsbehlen** [comment]
Some thoughts:
* Using WebAuthn offline without a machine name is pointless because it will inevitably break. So that should not be possible.
* If we want to remove a WAN token from a machine, the refilltoken is removed. However, this is only short lived because with the next successful /validate/check, the token is given out again.
* This means we do not only need to track the refilltoken per machine, but also the machines for which the token should not be given out.
* => There are 3 "states": token is on machine, token can be given to machine, token is forbidden to be on machine.
* We could additionally offer a more restrictive approach, where the machines that should be allowed to have the token have to be explicitly listed.
