### ISSUE TITLE
New scripts will not run in certain environments

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#3858]
All scripts in the development branch are currently failing with encoding:

~~~~
Traceback (most recent call last):
  File "./pi-manage", line 53, in <module>
    from privacyidea.cli import pi_manage
  File "/home/cornelius/src/privacyidea/privacyidea/cli/__init__.py", line 20, in <module>
    from privacyidea.cli.privacyideatokenjanitor.main import cli as pi_token_janitor
  File "/home/cornelius/src/privacyidea/privacyidea/cli/privacyideatokenjanitor/main.py", line 1
SyntaxError: Non-ASCII character '\xc3' in file /home/cornelius/src/privacyidea/privacyidea/cli/privacyideatokenjanitor/main.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
~~~~

We most probably need to put the line

    # -*- coding: utf-8 -*-

into the for backward compatibility.

It also looks like the whole rest of running a development server has undocumented massively changed and everything seems f***ed up.

**Comment by plettich** [comment]
I could not reproduce the `coding` issue. Which Python version are You using?
Since Python 3 all code files should be treated as UTF-8.

But it looks like the loading of the CLI modules is broken. When using the `pi-manage` command, the `token-janitor` modules should not be loaded as well.

Regarding the development server and other commands: since the `click` framework does some things differently, the structure of the commands changed. But i made sure that all the old commands still work (Still figuring out how to mark them as deprecated and hide them from the help-view). The documentation was therefore not (yet) updated.
But to start the development server, You need to use
```
pi-manage run <parameter>
```
instead of `pi-manage runserver <parameter>`. I'll update the documentation accordingly.

**Comment by cornelinux** [comment]
I am using Python 3.8. 
I think it is safer to use the coding information anyways.

**Comment by plettich** [comment]
Since [PEP 3120](https://peps.python.org/pep-3120/) the default encoding of source files is UTF-8. I'd rather not add the encoding declaration but instead remove the remaining encoding declarations since we do not support Python 2 anymore.
