### ISSUE TITLE
Verify enrollment does not work with indexed secret token

### ISSUE THREAD

**Issue by plettich** [privacyidea/privacyidea#3869]
customer care: 4114

Like in #3809 the indexed secret is created new when using the "verify enrollment" policy.
Enforcing a user-attribute as the secret with the user policy `indexedsecret_force_attribute` should prevent this. This won't work for user-provided secrets.

We should add integration tests for all tokens with `can_verify_enrollment = True` if the verification **and** a following `/validate/check` succeeds.

The specific observation is, that the indexed secret token that is created via verify enroll has a different length than the requested positions: Like: During enrollment the user enters 10 characters but the length is 40.

Could this be sth with the hexlify and encoding?

**Comment by cornelinux** [comment]
Can we solve this in a generic way, as we also had this issue with TAN tokens.

**Comment by cornelinux** [comment]
The problem is, that in the 2nd step of the verify enrollment a call to /token/init is made with the parameters: "verify" but not with the parameters "otpkey" and no "genkey". 

Thus we trigger this condition:
https://github.com/privacyidea/privacyidea/blob/662774047d37fdfe335fcf523892eff11ca5f881/privacyidea/lib/tokens/indexedsecrettoken.py#L173
