### ISSUE TITLE
Remove token realm removes the user in the token details

### ISSUE THREAD

**Issue by jelinaunger** [privacyidea/privacyidea#3986]
Removing the realm of a token also removes the user on the token details page. However, the user is not unassigned. Trying to assign a new user causes an error. In the token list, the original user is still visible.

### Steps to reproduce

1. Enroll a token with a user assigned.
2. Remove the token realm.
3. Assign a user.

### Expected outcome

Either removing the token from the owners realm is disabled or the user is unassigned properly.

### Actual outcome

The user is unassigned from the token, but only on the token details page. Assigning a new user to the token results in an error: `ERR1103: Token already assigned to user`
In the token list the user is still visible for the token.

### Configuration

**privacyIDEA version**: *3.9.3*

**Comment by cornelinux** [comment]
Ok, sounds like a logical flaw.

The token can have additional realms. This is why an admin can add realms or remove realms.

I am not sure, if the user should be removed, if an admin "by accident" removes the realm of the assigned user.
This would be additional action, that might not be expected.

So I would recommend avoiding being able to remove the realm of the assigned user.

"You can not remove this realm, since the token is assigned to... the user."
