### ISSUE TITLE
If a user has multiple tokens, the fail counters in the Ldap a going up very quickly.

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#4031]
Hello

When a user has several tokens, and he enters the wrong pin or OTP, the counters rise very quickly, blocking the user in Ldap.
On the privacyidea server, you can reset all the fail counters with the policy: reset_all_user_tokens.
	
But on Ldap, multiple failed connection attempts can't be reset like this.
Increasing the number of failed authentications on the Ldpa, is not a good solution.

Would it be possible to find a solution to reduce the number of requests when a user has many tokens?

#174445

**Comment by nilsbehlen** [comment]
this is fixed in version 3.10.
There will be only 1 ldap try per user, no matter how many token.
In case there is PIN+OTP, there will be 2 tries, because the first just checks the pin the second checks the cut input.
There is also a new `force_challenge_response` policy, to control the PIN+OTP case.
