### ISSUE TITLE
update owncloud 8.0 authenticator to support owncloud 9.0

### ISSUE THREAD

**Issue by chris001** [privacyidea/privacyidea#410]
The new version owncloud 9.0 is being adopted quickly...

**Comment by cornelinux** [comment]
This is a looooong story. I am not actively maintaining the owncloud app since owncloud is not really communicative.
Dealing with owncloud is no fun to me. 
And there is no customer, who is giving me compensation for my potential personal suffering. :-)
There are some posts about this topic..

If you jump in, just tell me. Otherwise i will close this ticket in a while.

**Comment by cornelinux** [comment]
please state this issue here:
https://github.com/owncloud/core
