### ISSUE TITLE
Offline token must be detached before it is possible to delete them

### ISSUE THREAD

**Issue by sepp67** [privacyidea/privacyidea#4136]
Hi
When a token is in offline modus, you cannot delete it.
![error ofline](https://github.com/user-attachments/assets/bcc3a234-7e1b-4070-9cca-8468822335bf)

Even an admin cannot delete it. You need first to click on the button ¨detache¨ it. Only then you can delete it.
![offline token delete](https://github.com/user-attachments/assets/17013cf0-360e-474b-a564-5279fe63f464)

Kind regards
s.c

**Comment by cornelinux** [comment]
That is correct.

Is this a problem?

**Comment by nilsbehlen** [comment]
Trying this with 3.10, the token does not have to be detached before deleting it. This would be the behavior i desire.

**Comment by plettich** [comment]
The problem is that we don't delete the database entries properly. Here
https://github.com/privacyidea/privacyidea/blob/b3270a9ffd5a08a67f60afa3662fe60930871df9/privacyidea/models.py#L295-L297
we want to delete the related `MachineToken` when deleting a token.
The call to `.delete()` issues an SQL `DELETE` statement for each matching row in the `MachineToken` table.
Unfortunately our relationships are not defined such that the delete is propagated to the corresponding `MachineTokenOptions` entries, thus the delete fails due to the foreign-key constraint.
The `MachineToken` class does have a working `delete()` function but it isn't called in this case.
The easiest fix for now would be to just loop over the results and call the `delete()` function directly for each entry.
In the long run we should properly define the relationships such that deletes will be propagated to entries with foreign-key constraints.
