### ISSUE TITLE
Test LDAP Resolver with objectGUID does not return users

### ISSUE THREAD

**Issue by buzzyxtra** [privacyidea/privacyidea#423]
When using the LDAP resolver with Server 2012R2 it is not possible to get user accounts based on objectGUID. Using the 'Preset Active Directory' button fills out the form but you need to change objectGUID into DN for it to work with Server 2012R2.

Because you have to use DN this will result in a token being lost/unassigned when a user is moved in Active Directory.

**Comment by cornelinux** [comment]
Your text is not quite right. The preset button works just fine. The presetted configuration might only not work for your settings. But: The objectGUID is known to work with 2012R2.

So please provide some more information - like  the version you are running and some debug log.

**Comment by buzzyxtra** [comment]
Sorry for the late response, wasn't able to reply sooner. 
Version in use on this moment is: V.2.12.1

I have included the difference of the last lines of the debug logs.

With UID Type set to 'DN':
[2016-06-24 12:16:09,394][533][139865166116608][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:563] Added host02.intern.ssczn.nl, None, False to server pool.
[2016-06-24 12:16:16,196][533][139865166116608][DEBUG][privacyidea.lib.resolver:184] Exiting pretestresolver with result (True, 'Your LDAP config found 826 user objects, but only 823 with the specified uidtype')
[2016-06-24 12:16:16,198][533][139865166116608][DEBUG][privacyidea.api.resolver:184] Exiting test_resolver with result <Response 304 bytes [200 OK]>

With UID Type set to 'ObjectGUID':
[2016-06-24 12:12:39,762][533][139865250043648][DEBUG][privacyidea.lib.resolvers.LDAPIdResolver:563] Added host02.intern.ssczn.nl, None, False to server pool.
[2016-06-24 12:12:39,999][533][139865250043648][DEBUG][privacyidea.lib.resolver:184] Exiting pretestresolver with result (False, 'AttributeError("\'NoneType\' object has no attribute \'get\'",)')
[2016-06-24 12:12:40,000][533][139865250043648][DEBUG][privacyidea.api.resolver:184] Exiting test_resolver with result <Response 286 bytes [200 OK]>

**Comment by cornelinux** [comment]
Hi Buzzy,

thanks a lot for saving the planet and avoiding probably unessary transmission of payload. This helps to keep the need for bandwidth down and so energy consumption will not eat us up. Also Greenpeace appreciates your doing!

But if you really want to get some help, you should provide some more information. Like more debug output. Or more side information. Please read https://www.privacyidea.org/getting-help/
Obviously you experience this problem when **testing** the LDAP resolver. 
Does it occur when using the LDAP resolver?

Yes, you might have stumbled upon a bug. Thanks a lot for that. But identifying this on my side with these information takes me at least half and hour or more. Because I do not experience this bug!

You have 823 objects in your Active Directory. If you are not able to investigate more details on this problem, you should be able to get some professional help to address this problem in an analytic way.

Kind regards
Cornelius

**Comment by buzzyxtra** [comment]
;-)

I did some more testing and found something useful to work with...

If i use 'DC=test,DC=domain,DC=org' as a base DN together with 'objectGUID' as UID Type it will result in an error.

However when i use 'OU=testou,DC=test,DC=domain,DC=org' with 'objectGUID' as UID Type it does find the user accounts in AD

So searching from the root of an AD is not working only when searching 1 level below that on OU level.

**Comment by cornelinux** [comment]
Searching from the root does not work at all unless you have set "no anonymous referrals".

Searching from the root without "no anoynmous referral" should not even work for type=DN.
The root contains other partitions, which can only be read by the administrator.

Can you confirm, that you chose "no anonymous referral" and objectGUID does not work anyway?
Did you check if **using** this resolver config does not work?

(I am a bit lazy, because I have to dig out my domain controller. I do not know, where I left it)

**Comment by buzzyxtra** [comment]
No problem I can test it.
The 'no anonymous referral' was checked.

Also the 'testing' part does not work, actually saving it (with objectGUID) does resolve users.
Actually didn't tried that because the test failed.

So this thread can be changed to 'testing ldap connection with UID Type set to objectGUID doesn't work, using it does' :-)

**Comment by cornelinux** [comment]
@buzzyxtra finally i migrated and fired up my 2012DC. I can confirm your observation. This is good, so I have something to debug on my side :o)

**Comment by cornelinux** [comment]
This was simple. The productive search has a try-except block around grabbing the users. The test-resolver had not.
Search from the domain root will also return the configuration partition. Which will cause an error, if the configuration partition is handled as user object. The try-except block in the productive search dealt with that. The testresolver would then immediately fail.
We just add a try-except block to the testresolver and it works like a charm.
