### ISSUE TITLE
Consistent audit log information

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#425]
Hello Cornelius,

a look in the audit log brings up messages like
- "The user authenticated against his userstore according to policy 'authentication_guests'."
- "The user has no tokens assigned"
- "matching 1 tokens"
- "wrong otp value"
- "wrong otp pin"

which differ in form and also in the supplied information. The following would be great: 
- The information about the matched authentication policy should be always included (readable at least for admins, possibly not readable for ordinary users). Therefore an additional db field for the matched authentication policy would make sense.
- On matching tokens, on wrong otp value and on wrong otp pin the message should be more human (E.g. "Wrong otp value supplied." or or "The user supplied a wrong otp value." or "The user supplied a wrong one time password.")

How do you think about it? How's the complexity of the change? Do some users rely on the existing message strings?

Best regards,

Bernd

**Comment by cornelinux** [comment]
Hi Bernd,

I do not know, if there are users parsing and regexping these messages.
These are messages, that are also returned in the API REST response. So it could be!

The challenge is, that several policies could apply!
So if adding a Audit DB field for matching policies, this would have to be concatenated or whatever.

The difficulty is not the implementation that much. But the difficulty is to determine the right way to implement it, so that you will not get stuck in half a year ;-)

Well, "wrong otp value" or "wrong otp value supplied" - I don't care. But: This is also the message, that is shown to the user (e.g. when logging in to the UI with OTP).
If I (the user) provide a wrong OTP value, I would not like to see the message "The user entered a wrong OTP value". I would prefer: "You entered a wrong OTP value". Maybe this is the reason why it is "wrong otp value" at the moment ;-)

Kind regards
Cornelius

**Comment by cornelinux** [comment]
As far as the policies is concerned:
The question is, if you want to limit this to the authentication policies.

1. During one authentication request, several authentication policies can match
2. you could also add other policies scopes. *authorization*, *admin*, *user*.

So there is a list of matching policies, you might want to log. 
Would you log it as a list, as a comma seperated string. Would you log only the names or also the scopes...
