### ISSUE TITLE
Token auto-assignment for users that already have an existing token

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#438]
Hello Cornelius,

it would be great to have auto-assignment working also for users that already have an existing token. What do you think and what's the complexity of an implementation?

Best regards,

Bernd

**Comment by cornelinux** [comment]
Auto assignment is a really costly function.

(hm, you could however limit the autoassignment to certain client IP. Only at home in the subnet...)

Are you running autoassign with "any_pin" or "userstore password"?

What could happen?

PI checks for all tokens of the user. It does not find a matching token.

If you are running "any_pin", autoassign will run for **every** authentication process - no matter if it fails or not!!! As an attacker I would flood the system with auth requests and since they are doing autoassign, the system will die very quickly of DOS (not even DDOS ;-).

If you are running "userstore password" privacyIDEA would calculate 10 OTP values of **every** unassigned token!

Do you really want to do this? Have you checked the performance with the number of tokens you are expecting?

What is your scenario? (off-github)
Kind regards
Cornelius

**Comment by berndnicklas** [comment]
The scenario would be a small ease of our hardware token rollout process, since some users already have a software token and auto-assignment would not work in those cases. To be honest, I did not think about the performance implications of such an implementation and also the existing auto-assignment implementation, so the question possibly was a little naive.

Since we use userstore pin for auto-assignment this would limit performance issue.

In any case, the performance issues of auto-assignment means, that you should always limit the count of unassigned tokens per realm.

The benchmarks I just run show, that ~20 unassigned hotp tokens in a realm do not have any measurable performance impact on the requests/sec count of ~100 concurrent authentication requests.

**Comment by berndnicklas** [comment]
> The benchmarks I just run show, that ~20 unassigned hotp tokens in a realm do not have any measurable performance impact on the requests/sec count of ~100 concurrent authentication requests.
OK, I did the test again with with an OTP value length matching the token OTP length. Now I see, what you mean, since we now only reach a throughput of 1/4.

**Comment by cornelinux** [comment]
Do you think you can ask the user to assign the tokens themselves? If they already have a token, they could use this token to login to the web ui.
Then they could assign the token by the serial number imprinted on the hardware token.

Admitted - I know that this often causes **** helpdesk calls.

**Comment by berndnicklas** [comment]
I think we just run different enrollment processes for users with and without tokens ;-)

**Comment by cornelinux** [comment]
We could discuss this in a telco...?

**Comment by cornelinux** [comment]
As discussed, we are closing this issue
