### ISSUE TITLE
After qr code display, verify the user has indeed enrolled the token

### ISSUE THREAD

**Issue by splashx** [privacyidea/privacyidea#503]
[Feature request]
Now privacyIDEA displays the QR code to the user but privacyIDEA can only assume the user has scanned the QR code. 
To verify if the user has in fact scanned the code, this can be done e.g. like Google and Microsoft do: in the page there the qr code is displayed, the user must click "next" and enter the OTP displayed (this way we know for sure the user has scanned and registered the token on his/her device and the token works).

Below is the way Microsoft does (step 4):
![image](https://cloud.githubusercontent.com/assets/1154133/18586753/83c11384-7c1e-11e6-917e-af6485081de3.png)
]

I would suggest privacyIDEA to not create a token for a user unless the user has verified the OTP...

**Comment by cornelinux** [comment]
In our setup the privacyidea server creates the otp seed. Thus the token is already created in the backend. 
We could however use the rollout state in the token table. 

What do you think should happen,  if the user does not enter the right otp value?

**Comment by eidorb** [comment]
I thought the verification step described by @splashx was a great addition to the enrolment process. I was able to implement the functionality using the API:

- Authenticate user and retrieve authorization token.
- Initialise a token, then immediately disable the token.
- Display token QR code and ask for OTP as verification.
- Validate the token against the user-supplied OTP. (Be sure to use otponly=1).
- If validation succeeded, enable the token.
- Otherwise, delete the token.

**Comment by splashx** [comment]
@eidorb are you by chance open sourcing this?

**Comment by eidorb** [comment]
My implementation is running on a hardware reverse proxy, so the code is only applicable to that product (a few hundred lines of TCL making HTTP requests).

That being said, I made a small Javascript page as a proof of concept. It follows a slightly different approach to my dot points above. It uses an admin authorization token created ahead of time, rather than a user authorization token. And rather than disabling a token, it unassigns it. But the general idea is the same. Hopefully this might get you going in the right direction. Your privacyIDEA web server will have to have CORS enabled for this to work.

https://gist.github.com/eidorb/56b72017445a563d200d16f65b79d1e9

**Comment by cornelinux** [comment]
This is a great example of using the API. Thanks a lot.
Please note, that the normal authorization token you are getting from the ``/auth`` request is only valid for one hour.

You could also do the following:

Authenticate the user by the means of the privacyIDEA WebUI.
Use the /auth endpoint to get an authorization token for a user.
http://privacyidea.readthedocs.io/en/latest/modules/api/auth.html#post--auth
This way you can do a "login dialog" for the user.

You can then use this auth token to do all consecutive requests with the user's rights.

**Comment by eidorb** [comment]
Yes you're absolutely right and that's how I'm doing it in production. 

For my test page I was using the (undocumented?) admin API key created with pi-manage. That should be valid for 365 days. However, I decided not to use it in the end because I may not be around in 365 days to update it!

**Comment by cornelinux** [comment]
hm. Yes the api key from pi-manage was an idea especially for the validate check API, so that not every client would be able to query the validation API.
This is why the documentation was hidden in the policies.
https://github.com/privacyidea/privacyidea/blob/master/doc/policies/authorization.rst#api_key_required

But now I also added some more docs.
https://github.com/privacyidea/privacyidea/commit/d6512b35c5707c23aaf8137f5597be0f772e9360
