### ISSUE TITLE
Deny policy - or Firewall Rule style

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#543]
# Can there be a functionality, that per default denies access for a user?

The policies work different than firewall rules. Unlike firewall rules there is no order in which the policies are worked on. This is because when the policies were designed, there would not be that much policies, to have the need for an order.
At the beginning of the request, the complete policy-set is read, so that each policy check can fetch the matching policies based on the user and client IP.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/before_after.py#L115

To have a deny functionality we could implement a new policy like

 *  scope:authorization
 *  action:deny.

This can have the same defaul-deny-effect:

If there is a request that matches only the deny policy and no other policy in the scope *authorization*, then this request can be denied.
We should avoid introducing new central system settings.

The deny-policy would be implemented as a policy-decorator. This way the decorator can simply decorate each endpoint-function.
Which endpoints (validate, token, system... see http://privacyidea.readthedocs.io/en/latest/modules/api.html) should be decorated by the deny-policy?

**Comment by axiadidsProdops** [comment]
Thanks Cornelius

Most Authentication/Authorization solutions we've come across allow to define set of Channels/Applications and apply which group of users is allowed to authenticate on each application, and with which type of tokens etc. It would be very beneficial if we could add this capability to privacyidea.

Essentially we would like to setup is something like this:

Users from group/resolver 1 can access App1(Client IP x,y,z) with Token type XXX only
Users from group/resolver 1 can access App2(Client IP a,b,c) with Token type YYY only
Users from group/resolver 2 can only access App1 with any token type

Any users not belonging to group/resolver  1 or 2 authenticating on App1 or App2 are denied.

From a security perspective we feel better about a model where the policy by default is "Deny unless explicitly Authorized" (Of course for backwards compatibility purposes this would have to be set as an option that is off by default).

For example, we wanted to propose adding a "validate_authorize" action the authorization scope allowing to specifically allow combinations of Realm, Resolver(s), ClientIPs to be authorized. If no AuthZ policy with the "validate_authorize" action is matched, then the validate call is denied (with a proper message that says essentially Authentication is OK, Authorization is Denied).

Also since this applies to authentication exclusively, and that authorization for UI is handled differently we could live with this applied exclusively on /validate for now.

I hope this makes sense - I may not fully understand how policies work exactly yet so forgive me if this doesn't make sense. But at least I hope you understand the requirement.

Thanks
Sam

**Comment by cornelinux** [comment]
I understand. This is why I would add the default behaviour as such a policy

   scope:Authorization
   action: "Deny unless explicitly Authorized" (bool)

The scope authorization applies to the validate-endpoint 
(see http://privacyidea.readthedocs.io/en/latest/policies/authorization.html)
so this is the right scope to put it.

And you are right - it would ease the understanding to add another policy

    scope:Authorization
    action: allow

Otherwise you would have to define a policy 

     scope: Authorization
     action: tokentype=<all>

to allow the access for a user by allowing it for all tokentypes.

**Comment by cornelinux** [comment]
Hi Sam,

I started to add more information about policies. Please check out, at which point I should improve this.

Thanks a lot
Cornelius

**Comment by cornelinux** [comment]
## privacyIDEA User handling

privacyIDEA gets an authentication request with "user" and "pass(word)" and maybe "realm". Now privacyIDEA first tries to get a userobject.

Therefore it itererates through all resolvers of the realm (or default realm) to find a userobject, which matches the loginname "user".
The iteration of the resolvers is determined by the priority in the realm definition. Small numbers first.

If privacyIDEA finds a userobject this one is used.

## Authentication or Assigning

Now privacyIDEA has a userobject which consist of a userid like the objectGUID, the resolver and the realm. Now it can lookup the tokens of this user to authenticate or it can use this userobject to assign a token.

If there are other resolvers (with lower priority, i.e. higher number) in the realm, these are ignored, even if there would be  a userobject with the loginname. 

# Deny - Policies

We could use this effect to setup the deny policy scenario.

The single realm can contain one catch-all-resolver with the highest priority. Tokens will be assigned to the userobject in this catch-all-resolver and users will authenticate with the userobjects in this catch all-resolver.

## Defining resolvers

Thus you could define a realm with the following resolvers:

* catch-all, prio 1, dc=dc1,dc=tld
* app1, prio 2, ou=group1,dc=dc1,dc=tld
* app2, prio 3, dc=dc1,dc=tld, memberOf=someUsers

This way all tokens will always be assigned to users in the catch-all resolver, no matter what you are doing with the other resolvers, if you remove resolvers from the realm, if users are added to the other resolvers, if resolvers are deleted.

## Policy matching

Now *we only need to* extend the policies this way, that the policy would also check for similar users in other resolvers.

I.e. you could define a policy

* scope:authz, action:tokentype=HOTP, client=10.1.1.1,resolver=app1, any-resolver=true

Now the user would authentication and the userobject would be determined by privacyIDEA to 
*User(loginname, resolver=catch-all, realm=default)*.
At the moment this policy would not match, since the user is in the wrong resolver. 
But as *any-resolver* is set to **true**, the policy checking could be enhanced, that a new user lookup in all resolvers is performed and the policies for all possible users are evaluted.

I.e. the userobject would be mapped to:
* *User(loginname, resolver=catch-all, realm=default)*
  => no matching policy
* *User(loginname, resolver=app1, realm=default)*.
  => policy matches!

**Comment by cornelinux** [comment]
The policy can contain a bool flat "check_all_resolvers". This indicates, that the policy will be checked for matching resolvers of the user, which are not the "main" or "first" resolver.

*Realm1* has the resolvers

 * resolver *catchall*
 * resolver *group1*
 * resolver *group2*

A user *user1* could be located in *catchall* and *group1*.

The user **user.cathall@realm1** authenticates.
A policy with *check_all_resolvers* would check for this very user for resolvers *catchall* and *group1*.

**Comment by cornelinux** [comment]
Hi @axiadidsProdops 
The concept is implemented, now.

You can add a policy, that looks like this:
![bildschirmfoto vom 2016-12-19 18-27-54](https://cloud.githubusercontent.com/assets/1908620/21322331/efb091e8-c618-11e6-84ba-f350f6362977.png)

This policy will match a user in the specified resolver, even if this is not the resolver with highest priority, which the user contains.

Please checkout, if this works out for.
You may also drop a note, in which scenarios you are using this (only scope=authorization)?, since then I can check the code, if all calls to the policies contain the necessary parameters (i.e. the username and realm).

Then I would like to close this issue.
