### ISSUE TITLE
Filter token realms in token view

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#545]
The following additional filter attributes in token list would be great:

- user
- realm

Additionally, the REST API documentation for GET /TOKEN should be altered:

- `tokenrealm` parameter is actually used, not `viewrealm` like mentioned in code documentation

**Comment by cornelinux** [comment]
This can be very complex and time consuming, since the username is not stored in the token table. 
We would fetch all user objects from LDAP, which look like the entered values. Then we would have to fetch all tokens for this list of users.

This is intentionally not implemented.
I recommend to got to the user list, search for the user and the go to the user details to see his tokens.

The docstring is changed from viewreal -> tokenrealm. Thx! :+1:

**Comment by cornelinux** [comment]
Filter only realms of assigned tokens,

**Comment by cornelinux** [comment]
Discuss...

**Comment by fredreichbier** [comment]
* [ ] We add a column "token realm" in the WebUI.
* [ ] We add the possibility to search for tokens with a specified user realm or token realm.

**Comment by cornelinux** [comment]
The list of the tokens already contains the keys ``user_realm`` of the assigned used and the key ``realms`` which is a list of the token realms.

The API ``GET /token`` already accepts the parameter ``tokenrealm`` which return tokens with are located in the given realm.

**Comment by plettich** [comment]
#1964 introduced a bug: listing tokens from the API will always send a `tokenrealm` parameter thus forcing the token query to check for token realms as well.
Newly created and unassigned tokens do not have token realm set (except through policies and/or event handler) and so won't be found by the token query.

**Comment by cornelinux** [comment]
The problem obviously arises from the *join* between the token table and the tokenrealm table.
Tokens, that have not entry in the tokenrealm table will not be contained in the join.
See here: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/token.py#L189

**Comment by cornelinux** [comment]
Work as expected now.
Will add a nice test.
