### ISSUE TITLE
This projects developer is an ASS!!!

### ISSUE THREAD

**Issue by MaRRiK74** [privacyidea/privacyidea#552]
![image](https://cloud.githubusercontent.com/assets/19833001/20489155/d84aa162-b009-11e6-9c20-c6ef2ba5c12a.png)

WTF?? I'm tryinng to help solving a bug. As fast as I can to provide information.

This is how you handle the community, if that's so you're an ASS Cornelinux!

**Comment by cornelinux** [comment]
Thanks a lot for opening this issue!

privacyIDEA is an open source project which everyone can use and is free to contribute, if he likes to. 

But also should everyone understand, that certain information need to be available to realy help fix a problem. privacyIDEA is a complicated and complex product, which is not ment for an end user but for a system administrator.
I expect when asking a question or filing a bug, that certain basic information which an IT guy can collect have already been gathered and are provided. 

This is why we use the TEMPLATE_ISSUE.md for filing issues.

Thank you for keeping this in mind, when filing a bug.

Otherwise I might happily turn you away or ignore you.
