### ISSUE TITLE
LDAP user UI/UX improvements (Disable Live search & UI "busy" indicator)

### ISSUE THREAD

**Issue by sam-axiadids** [privacyidea/privacyidea#567]
Hi Cornelius!

We are dealing with production environments with multiple ldap resolvers pointing to large LDAPs with sometime higher than average latency, causing user searches to be very slow (10-15s to return a list of users for instance).

We wanted to propose a couple enhancement to improve user experience with looking up LDAP users in the WebUI:

 - Have an option allowing to disable "live search"  when looking up users (i.e start search when pressing enter rather than for every character typed) This would also prevent unnecessary load on the backend every time a character is typed.

- Have some kind of UI spinning icon or some kind indication that it is "busy" waiting for an answer when looking up users in the WebUI. (When a list of users takes 10 to 20s to return results it is not clear if no users are found or if the system is still waiting for an answer).

Thanks!
# Versions
privacyIDEA: 2.16.1
Installation method: from source / github
OS: Amazon Linux
Webserver: Uwsgi/nginx
Tokendatabase: PostgreSQL / AWS RDS

**Comment by cornelinux** [comment]
Disabling the user search could be done at least in two different ways. I would like to know your opinion on this:

1. We could add a webui policy, that defines, if the user search should be done or not.
    In this case the administrator could no change this. This might be also an expected behaviour
    if you do not want the helpdesk to fiddle around with that.

2. You can add a switch in the UI, where the admin can deactivate the search. He would have to set 
    the switch all the time. 

3. We could combine both. Set a webui policy for the default behaviour and the admin could change it.
    (I am not sure if the admin or helpdesk user needs to change this)

Hitting the enter button for searching is a bit tricky, since I think enter sends the form. We need to check this.

**Comment by quynhnng** [comment]
Hi Cornelius,

I think we just mean to disable the live search. To be specific, at the moment, user.list.html's ng-change fires up _getUsers() on each input change in the filter. For example, if "penny" is to be entered in the filter, ng-change will send 5 LDAP lookups for *p*, *pe*, *pen*, etc.

In some scenario, LDAP query is very costly, and results in this operation takes very long (>15s) to finish, and is stresses the LDAP server.

I have tested, and able to change this behavior from taking action on each input change to only take action on enter key pressed:
in privacyidea/static/components/user/views/user.list.html:
`ng-keypress="($event.which==13)?_getUsers():return"></pi-filter>`

I tested it with Firefox, Chrome, and IE11.

If you see the value to enforce this, then we dont need an extra option, but in stead change to behavior to this instead of ng-change.

**Comment by cornelinux** [comment]
I would like to make this configurable, since I think many users like the live search.
So I would see how I can add a webUI policy.

**Comment by quynhnng** [comment]
Hi Cornelius,

Thank you for updating this issue!

It would be great if other live searches in web ui also follows this policy, such as the loading user drop-down, or loading tokens drop-down when enrolling a token or assigning a token, also the search for token filter in the token list html :)

**Comment by cornelinux** [comment]
I added this to the token list.
But it is not easily addable to the assigning process.
The enter key assigns the token.
And I am not sure what would be a sensible design here...

**Comment by quynh-axiadids** [comment]
Hi Cornelinux,

Regards disabling the livesearch for loadUsers and other 'typeahead', I have implemented this modification (tested on Chrome/Firefox/IE11):
24382386cc381e00004746d33ddf770c3e9b30f1

- The type of the button is changed so that enter key does not result in submitting the form. I think it little affect user experience.
- The change allows to only do queries on enter key press.
- Typeahead is still implemented. If user continue to input within the range of the latest queried result, an filtered 'offline' matching list is shown as usual. If user inputs outside the filter of the latest query, then they will have to press enter again to retrieve matches if they want.
- Other notes:
 - typeahead-wait-ms to allow ng-keypress to proceed and the modal to be updated before typeahead kicks in
 - typeahead-focus-first is disabled to give priority to enter key press within input field (vs enter key press in dropdown typeahead list)

I am looking forward to your feedback!

**Comment by cornelinux** [comment]
This was finally solved in @quoc-axiadids PR 3ffaf632750cfcef67180fc6920384f794407153
