### ISSUE TITLE
OTPPIN: policy violation when enrolling a token

### ISSUE THREAD

**Issue by jh23453** [privacyidea/privacyidea#580]
privacyIDEA 2.16 from Ubunutu PPA with Apache

# What did you try to do?

I did have a user policy with "otp_pin_minlength = 6".
As a user for whom the policy is applicable I enrolled a TOTP token in the WebUI.
I get the message "The minimum OTP PIN length is 6"[1] and no chance to enter an OTPPIN.
The token can not be enrolled.
I tried with setpin in the policy set and unset, but that doesn't make a difference.
After removing otp_pin_minlength from the policy I could enroll the token.

[1] The translation to german seems to be missing.

# What outcome did you expect?

I expected to get questioned for an OTPPIN, where the check would be perfectly valid.

**Comment by cornelinux** [comment]
A new policy was introduced. Obviously in a bad way. scope=user, action=enrollpin.
If this is not set, the user can not enroll a PIN.
Please set this action.

**Comment by jh23453** [comment]
You seem to be right - I can't reproduce now. And I'll probably stick with OTPPIN in Userstore anyway.

What might be useful: the user policy is large and (for me) unsorted in the UI.
First is setpin and revoke, some enroll<TOKEN> rights later, resync and unassign mixed in.
The policy definition in python is better structured, but I guess due to storage in an dictionary
it gets unsorted. That would make the policy management easier, but probably needs 
a new ticket (using groups in the policy?).

**Comment by cornelinux** [comment]
Yes. You are welcome to open a FR about the policy list.Your ideas are welcome!


Cornelius Kölbel +49 151 2960 1417
NetKnights GmbHHttp://NetKnights. It
+49 561 3166 797

-------- Ursprüngliche Nachricht --------Von: jh23453 <notifications@github.com> Datum: 26.12.16  09:00  (GMT+01:00) An: privacyidea/privacyidea <privacyidea@noreply.github.com> Cc: Cornelius Kölbel <cornelius.koelbel@netknights.it>, Comment <comment@noreply.github.com> Betreff: Re: [privacyidea/privacyidea] OTPPIN: policy violation when enrolling a token (#580) 
You seem to be right - I can't reproduce now. And I'll probably stick with OTPPIN in Userstore anyway.
What might be useful: the user policy is large and (for me) unsorted in the UI.

First is setpin and revoke, some enroll rights later, resync and unassign mixed in.

The policy definition in python is better structured, but I guess due to storage in an dictionary

it gets unsorted. That would make the policy management easier, but probably needs

a new ticket (using groups in the policy?).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/privacyidea/privacyidea","title":"privacyidea/privacyidea","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/privacyidea/privacyidea"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jh23453 in #580: You seem to be right - I can't reproduce now. And I'll probably stick with OTPPIN in Userstore anyway.\r\n\r\nWhat might be useful: the user policy is large and (for me) unsorted in the UI.\r\nFirst is setpin and revoke, some enroll\u003cTOKEN\u003e rights later, resync and unassign mixed in.\r\nThe policy definition in python is better structured, but I guess due to storage in an dictionary\r\nit gets unsorted. That would make the policy management easier, but probably needs \r\na new ticket (using groups in the policy?)."}],"action":{"name":"View Issue","url":"https://github.com/privacyidea/privacyidea/issues/580#issuecomment-269180039"}}}
