### ISSUE TITLE
Recent performance drop for authentication and token list

### ISSUE THREAD

**Issue by berndnicklas** [privacyidea/privacyidea#595]
Please think about and cover the following questions:

# Versions

privacyIDEA: 2.18dev, commit 6fd1050a36651d6829103a1f63119ac2d470f621

Installation method:

- from source / github
- Debian Jessie

Webserver: NGINX, UWSGI

Tokendatabase: PostgreSQL

# What did you try to do?
Updated privacyIDEA from b0291eff731c5fb20636d41d361cdac8cf5f69d3 to 6fd1050a36651d6829103a1f63119ac2d470f621.

# What outcome did you expect?
Comparable performance to previous version.

# What outcome did you experience?
- For authentications with only username and password (=passthru + no token) against /validate/check, we experience a performance drop of ~40%
- For the token list, we experience a performance drop of ~60%, e.g. for ~600+ tokens we have now ~10 seconds loading time (compared to ~3 seconds before), which feels very slowish.

Can anyone reproduce this performance drop? Any ideas for possible reasons?

**Comment by berndnicklas** [comment]
- Checked privacyIDEA logs, no special errors
- Checked UWSGI logs, no re-occurring worker restarts
- Checked NGINX logs, no special errors

Of course this could be also related to possible unusual load peaks in our virtualization clusters or our networks. I am not sure about that, so I'll check that.

**Comment by cornelinux** [comment]
How did you update?
Do you know, which version of the ldap2 module you were running before?

If you are running a virtualenv, did you make a backup of your virtualenv by any chance?

I very much assume this is connected to LDAP access time. But I would not have expected this.

**Comment by berndnicklas** [comment]
In fact I am still using ldap3 0.9.8.4-1trusty1 (newer than debian jessie version) from privacyidea launchpad ppa, so there was no update. I just saw your latest changes relating ldap3 v2, so I'll update to v2 and check again...

**Comment by cornelinux** [comment]
the 2.17 release still supports both.

The 2.18dev (current master) only supports ldap3 v2. We will switch to this newer version, since it has improvedments in attribute handling, objectGUID, redundancy, timeout...

A packed version is available in the dev ppa:privacyidea/privacyidea-dev.

**Comment by berndnicklas** [comment]
Corrected used version to 2.18dev (current master).

**Comment by berndnicklas** [comment]
Hi Cornelius,

I must say, that after a closer look and several benchmark tests more I now can't say whether the upgrade had any impact on the authentication or token list performance. Since all worker machines are running as virtual machines in VMware or KVM cluster, they are dependent on the load of all virtual machines. I was able to create a few (not many) results that were in line with the benchmark tests end of last year. So it could be a general increase of computation load in our organization.

After all, now I can confirm, that the upgrade of ldap3 v0.9.8.4 to ldap3 v2 had *no* negative impact on the performance, which is good to hear.

To deal with the specific problem of loading a 600+ token list in around 4-12 seconds (and we will have more tokens soon), possibly a limit for the token list could make sense, similar to the user limit in the user resolver (this solved all performance problems in the user list). I don't know whether this could solve the performance problem, since I did not have a look into the concrete implementation here.

Thanks,

Bernd

**Comment by cornelinux** [comment]
Hi Bernd,
thanks a lot for again looking into this and your feedback.

If you are talking of loading tokens in the token view?
I am about to add this text to the FAQ section of the documentation.
Does this fit to your situation?

Kind regards
Cornelius

What happens in the tokenview?
------------------------------

A question which comes up often is why you can not view hundrets of tokens in
the tokenview. Well - you are doing - you are just paging through the list ;-)

Ok, here it what happens in the tokenview.

The tokenview fetches a slice of the tokens from the token database. So, if
you configure the tokenview to display 15 tokens, only 15 tokens will be
fetched using the ``LIMIT`` and ``OFFSET`` mechanisms of SQL.

But what really influences the performance is the user resolver part.
privacyIDEA does not store username, givenname or surname of the token owner.
The token table only contains a "pointer" to the user object in the userstore.
This pointer consists of the userresolver ID and the user ID in this resolver.
This is usefull, since the username or the surname of the user may change. At
least in Germany the givenname only changes in very rare cases.

This means that privacyIDEA needs to contact the userstore, to resolve the
user ID to a username and a surname, givenname. Now you know that you will
create 100 LDAP requests, if you choose to display 100 tokens on one page.

Although we are doing some LDAP caching, this will not help with new pages.

We very much recommend using the search capabilities of the tokenview.

**Comment by cornelinux** [comment]
Added in this commit cacf823c9b1b6686f307cdc2343c6e6cb7f77398.
I am closing this issue since the initial problem seems not to be valid anymore.
Further details can be discussed offline or in this closed issue.
