### ISSUE TITLE
Rename userresolver and realm

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#631]
We should rename the user resolvers and the realms to

userresolver -> user store (German: Benutzerquelle)
realms -> ??? (German: ??? )

**Comment by mimugmail** [comment]
In the world of Radius, realm = realm, also in German. In the world of VPN everything after an @ is a group. And when I look into the UI and replace realm with group it could fit very well. :)

**Comment by cornelinux** [comment]
So you can define several **userstores** to find the users. Then you can group several of these **userstores** like LDAP, flatfile and another LDAP to a **group**. Hm. Could this be misleading? Yes, the realms have somehow the functionality of a group, but sometimes also the resolver/**userstores** do.

I *suspect* it might be a good idea to find describing names, that have no previous connotation?

**Comment by berndnicklas** [comment]
_userstore_ fits well, as it describes, where the users are stored (since privacyIDEA is able to not only resolve the users, but to add/edit/delete them, too).

_realm_ is used to differentiate the people/users at a high level according to organisational/territorial structures (e.g. guests, students, staff, technical administrators). You can think of a realm as something related to an area of influence, where a sovereign rules (e.g. the faculty administration, the university administration, the university computing center administration; see also the general definition of realm: https://en.wikipedia.org/wiki/Realm). Since _realm_ is a standard term in LDAP, AD, RADIUS and Kerberos authentication context, I think there is no need to find a translation for it in German.

_group_ is usually used in a context where a group of people/users possibly across different realms is granted granular role memberships and permissions at a lower level (e.g. permission to publish articles in a specific directory of the content management system). Using _group_ as a replacement for _realm_ could lead to administrator confusion (I know, Cisco ASA uses the term _VPN group_, but hey, it's Cisco and they can afford their own wording).

**Comment by cornelinux** [comment]
@mimugmail @berndnicklas thanks a lot for your input!

**Comment by quynh-axiadids** [comment]
In our environment, we also use realms to define:
- admin realms: different level of authorities for admin realms
- user realms: different AD domains (this is for multiple reasons)

For these critical purposes, realms are highly utilized for us. 
I think I don't have any issue with the current naming, and the term 'realms' fits well for me so far.
I agree with @berndnicklas that it is standard term in a lot of other applications, and thus easy to have a grab of what it is for.
Other than that, one relevant term I can think of is 'domain', if we are interested in options :)

**Comment by cornelinux** [comment]
Hi @quynh-axiadids, thanks for your feedback! **domain** also sounds quite nice. It feels like a similar idea. But we probably  will stick with **realm**.

**Comment by cornelinux** [comment]
We decided not to rename resolvers.
