### ISSUE TITLE
Events handler with "validate_check" disrupts "passOnNoUser / passOnNoToken "

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#634]
The policy for one Realm is:

```
{
"reset_all_user_tokens": true,
"passOnNoUser": true,
"passOnNoToken": true,
"otppin": "none"
}
```

This is the "right" reply without Event Handler:

`{"jsonrpc": "2.0", "signature": "...", "detail": {"message": "The user does not exist, but is accepted due to policy 'business_authentication'.", "threadid": 140452636370688}, "versionnumber": "2.17", "version": "privacyIDEA 2.17", "result": {"status": true, "value": true}, "time": 1488275316.468263, "id": 1}`

Enabling this Event Handler:

`[ "validate_check" ] / UserNotification /  {"token_locked":"True"} / sendmail / ...`

this is the "wrong" reply:

`{"jsonrpc": "2.0", "signature": "...", "detail": null, "version": "privacyIDEA 2.17", "result": {"status": false, "error": {"message": "ERR905: The user can not be found in any resolver in this realm!", "code": 905}}, "time": 1488275304.915057, "id": 1}`

**Comment by cornelinux** [comment]
This makes absolute sense from a logical standpoint (although it might not be the expected behaviour) ;-)

The event handler tries to determine the user to send him an email. But the user can not be determined.
Do you have any other event handler in place?

What is your expected behaviour? I guess --- since no user is involved, that the programm passes silently and does not send a notification?

Do you have by any chance the traceback of the privacyidea.log file?

**Comment by simvirus** [comment]
Hi Cornelius,
the "Event Handler" (in this case UserNotification) must be a "passthrough" without changing the behavior.

This case is : ["validate_check"] -> {"token_locked":"True"}? -> FALSE (user not present)  -> do nothing.

Are you talking about "PI_LOGLEVEL = logging.DEBUG" ?

**Comment by cornelinux** [comment]
Yes, the debug log level should add the traceback to the log file.

**Comment by cornelinux** [comment]
The same happens with the policy ``scope=authorization`` , ``action=user_detail``.
