### ISSUE TITLE
Lockscreen displays useless @ when logged in as admin@localhost

### ISSUE THREAD

**Issue by mimugmail** [privacyidea/privacyidea#636]
# Versions

privacyIDEA: 2.18dev3

Installation method:

virtualenv

## more details: 

OS: Debian 8

Webserver: Apache

# What did you try to do?

Wait for Lockscreen

# What outcome did you experience?

Message is: Sie sind als Benutzer admin@localhost @ angemeldet.

**Comment by cornelinux** [comment]
This is totally fine. The @ is not useless, it indicates, that you have a user with the name "admin@localhost", which is in no realm (since there is nothing behing the @).
Obvisouly the admin@localhost is an internal administrator.

If you would name your internal administrator simply *admin*, then the message would be, "you are logged in as admin @". The same as it is in the upper right orange button.

If a normal user from *realm1* logs in it would be
You are logged in as user @ realm1.

If a helpdesk admin from *helpdesk* logs in it would be
You are logged in as admin @ helpdesk
