### ISSUE TITLE
Apache error when install in CentOS

### ISSUE THREAD

**Issue by lidfgab** [privacyidea/privacyidea#641]
Hello,
I have finished this step in CentOS(1611) installation, without any problem
pi-manage.py runserver -h 10.0.0.47 -p 80
but after I finished the Apache configure following the installation guide, I only see the page like this:

Index of /
Name	Last modified	Size	Description

Is there any key point on the Apache configure?

**Comment by cornelinux** [comment]
I assume you are referring to 
https://www.privacyidea.org/two-factor-authentication-with-otp-on-centos-7/

stop pi-manage and connect via https to apache.

**Comment by mchvgs79** [comment]
Hello,

I am having the same issue.  I had the server working as needed, then complete the last steps in the process "Update privacyIDEA"   and now the page only displays:

Index of /
Name	Last modified	Size	Description

I'm not finding this helpful >>> stop pi-manage and connect via https to apache 

Thanks for any help...

**Comment by plettich** [comment]
Hi,
 
> I'm not finding this helpful >>> stop pi-manage and connect via https to apache ( likely due to my lack of experience with this, can it be expanded on?)

If the development server (`pi-manage runserver`) is still running, stop it by typing `CTRL+C`.
And You need to connect to the server via `https`, so You need the following URL in the browser: `https://<your ip>/` since privacyIDEA is only accessible via SSL/TLS.
If You have the firewall running, You need also need to open the port for https.

Hope it helps
