### ISSUE TITLE
Validity Format

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#644]
# Versions

privacyIDEA: 2.17

Installation method:

- from source / github

## more details: 

OS: AmazonLinux

Webserver: nginx

Tokendatabase: PostgreSQL

======

Hi Cornelinux,

We are seeing some issue with the Validity Period settings:

**1. WebUI format mismatch with database**
If you try to select a date from the calendar only, the date format string shown in the UI as a result is DD/MM/YY, and is recorded fine as DD/MM/YY in the token info (database)

However, if you try to select a date from the calendar and then insert a time string after, the date/time format shown in the UI is DD/MM/YY hh:mm, yet is recorded as MM/DD/YY hh:mm in the token info (database)

This is very confusing for user experience.
The calendar selection format should agree with the string entering format.

**2. Timezone**
The time enter in the webUI is likely local time zone for the user (for example PST), but it is always converted to GMT when saved in the database. And when the user authenticate, it is matched with local time zone against the literal-saved validity time in the token info.

For example:
If the validity is entered as 08/03/17 04:43 (**PST**), it will be saved as 03/08/17 11:43 in the token info, and displayed in token details as so. (date and month is switched, and time is converted to GMT)

Provided that I manually fix the date so that the token info now is 08/03/17 11:43 (**GMT**). When a user authenticates at 11:00 PST it is failed due to out side of validity window because it is matching against the literal 11:43 **GMT** in the token info.

Because there is no timezone is shown, it is further confusing, especially for organization that has users across multiple timezones.

I am not sure if I may be missing some configuration to adjust this issue.
I am looking forward to your input!

Thank you.

**Comment by cornelinux** [comment]
Hi @quynh-axiadids ,
no, there is no timezone configuration here. It is a know issue (#239) that the validity time has problems with the timezone. We did not fix it, yet.

I was not aware the the day and month is switched?

**Comment by quynh-axiadids** [comment]
Hi @cornelinux,

Thank you for your clarification.

Yes, the date/month are switched when you select a date from the calendar and then input a time after.

It is very convenient for user to select a date from calendar and input a time after as they want. But right now, the behavior is unexpected.

**Comment by cornelinux** [comment]
I will look into this again. I think privacyIDEA acts right on the date part.
I think the thing is, that the date format in the database is in fact DD/MM/YY.

I think I will change this to DD.MM.YY, so that the confusion is obvious ;-)
The problem is that there are different date notations in different countries and we do only use *one*.

**Comment by cornelinux** [comment]
Renamed the issue, since it works as designed.

**Comment by cornelinux** [comment]
We could add a configuration paramter specifying the date format.

**Comment by quynh-axiadids** [comment]
@cornelinux,

My apology to to be unclear when open this ticket, or if I misunderstand your response.
However, the problem at the moment is the conflict behavior of these two:

1. WebUI calendar date selection ONLY: format display after selection is "DD/MM/YY", the database/token info shown as DD/MM/YY as expected.

2. WebUI calendar date selection + time string input by keyboard: format display is "DD/MM/YY hh:mm" (supposedly, as reference to the bullet above), format saved in the database is as "MM/DD/YY hh:mm".

For example, if you choose March 02, 2017 from the calendar, in the (1), it is displayed after selection and saved correctly as 02/03/17. But if you choose the same date (the input is 02/03/17), and then input the time like 05:22 (the input is now 02/03/17 05:22), it will be saved as 03/02/17 13:30 (which is actually February 03, 2017, and the time is in UTC).

The UTC issue aside (I hope we can adjust the js to make this also agree with the backend), the date is switch in case of with and without a time string after select the date from the calendar. This behavior is unexpected, and I hope we are able to make the calendar style agree with the datetime input format with a time string.

Thank you again for looking into this.

**Comment by cornelinux** [comment]
Thanks a lot for your patience. I took a look at it again and finally I see.
As long as you stick with the datapicker everything is fine.
As soon as I use the date from the datapicker **and** add a time manually, the *month* and *day* is indeed switched.

**Comment by sam-axiadids** [comment]
Thanks Cornelius for looking into this. 
We have users in multiple time zone. It is important that the date picker and the db storage handles timezones consistently.

**Comment by cornelinux** [comment]
We could use tsomething like this javascript to verify the user's timezone/offset

http://stackoverflow.com/questions/40401543/get-timezone-from-users-browser-using-momenttimezone-js

**Comment by cornelinux** [comment]
@fredreichbier if we touch the datepicker. Should we use this to update angular and bootstrap?
We are shipping *extremely* old bootstrap templates! 
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/static/contrib/js/ui-bootstrap-tpls-0.13.0.js

**Comment by fredreichbier** [comment]
Yes, I also think that this would be a good opportunity to also update Angular to 1.6 and angular-ui-bootstrap to 2.5.0, especially because we would then have some time until the next release to find web UI quirks evoked by the update.

**Comment by jean-gui** [comment]
My 2 cents (PrivacyIdea 2.14):

- It is not clear in the WebUI that you can specify a time in addition to the date. There should at least be a message explaining this
- Why not use [ISO8601](https://www.iso.org/standard/40874.html) instead of this "strange" format? This way, timezone would also be stored in the database and it would be possible for different clients to use different timezones (PI WebUI simply being one such client)
- The required format should appear in the WebUI and [documentation of the REST API](http://privacyidea.readthedocs.io/en/latest/modules/api/token.html?highlight=validity_period_end#post--token-init) to avoid having to try and guess it looking at the logs:
```
ValueError: time data '2017-04-25T10:33:15+0000' does not match format '%d/%m/%y %H:%M'"
ValueError: time data '25/04/2017 10:35' does not match format '%d/%m/%y %H:%M'
```

**Comment by cornelinux** [comment]
@jean-gui  @sam-axiadids please see our thoughts after internal discussion
https://github.com/privacyidea/privacyidea/wiki/concept:-datetime

**Comment by jean-gui** [comment]
Sounds mostly good to me. Perhaps there should be a timezone user setting so that users can enter a date/time in their local time without having to know what their time difference is.

**Comment by cornelinux** [comment]
Sounds good to me so far. But till now, we have not user settings.

**Comment by jean-gui** [comment]
No user settings per se, but there are some user information like phone and email.  Timezone could be another one, although that may not be the best place to store that info. 
Another possibility would be to automatically detect where the user using his IP address, or (I don't know if that's possible) get it from the OS.

**Comment by fredreichbier** [comment]
Just for the record: I think the reason for the weird switch from DD/MM/YYYY to MM/DD/YYYY for the date portion lies in [this line of angular-ui-bootstrap](https://github.com/privacyidea/privacyidea/blob/de7ed353a9a3b1c43945c26fdd4801241a6ebacd/privacyidea/static/contrib/js/ui-bootstrap-tpls-0.13.0.js#L1576): As ``dateParser.date(...)`` cannot parse the ``DD/MM/YYYY hh:mm`` format, it returns null, which makes angular-ui-bootstrap use the ``new Date(viewValue)`` constructor, with ``viewValue`` being the user-supplied datetime string. The string constructor of ``Date`` then [apparently](http://dygraphs.com/date-formats.html) favors the MM/DD/YYYY format, regardless of the browser timezone.

**Comment by cornelinux** [comment]
@jean-gui We (@fredreichbier and me) discussed this a lot today. We could identify the timezone or the offset to UTC of the client and convert the time / a.k.a. save the time accordingliy. But this would be a hidden functionality to the helpdesk user. And the helpdesk user would usualy set a time for another user. And the other user might not be located in the same timezone like the helpdesk user. 
So we think that the best idea is to totally follow the to technical but transparent approach. Save the timezone which the user adds and give an explanatory text.

The next thing: The expiration datetime belongs to a token, not to a user. And when a helpdesk sets the datetime for a users' token, should we use the helpdesk users' timezone, so that the helpdesk user understands, what he is doing or the token owners' timezone? 
In my opinion this is to complicated. Requiring to set the timezone like +0200 is not very user friendly but it is unambiguously clear.

**What is your usecase of using the validity period?**

**Comment by cornelinux** [comment]
@fredreichbier The validity time is set here:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L850
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokenclass.py#L880

We should change the DATE_FORMAT in lib.tokenclass and be able to only read (not write) the old date format.

**Comment by cornelinux** [comment]
I think the easiest and most straight forward solution could be:

In the datepicker directive we use the following format:

    datepicker-popup="yyyy-MM-ddTHH:mmZ"
    datepicker-popup="yyyy-MM-dd HH:mmZ"

When the user selects a date, the field is filled with: 

    2017-04-12T00:00+0200
    2017-04-12 00:00+0200

Obviously the datepicker chooses the timezone (+0200) by itself. The user sees, that he could change the time manually.

Now we should simply pass this string in the API. We can easily save this in the database and it will be a clear point in history and time, since it contains the ZT / UTC offset.

**Comment by cornelinux** [comment]
Looks like normal ``datetime`` module in python can not handle the timezone or utc offset. We probably need ``dateutil``.

    s
    '2017-04-12T00:00+0200'
    format
    '%Y-%m-%dT%H:%M%z'
    import dateutil
    from dateutil.parser import parse
    parse(s)
    datetime.datetime(2017, 4, 12, 0, 0, tzinfo=tzoffset(None, 7200))
    d = parse(s)
    d
    datetime.datetime(2017, 4, 12, 0, 0, tzinfo=tzoffset(None, 7200))
    d.strftime(format)
    '2017-04-12T00:00+0200'

**Comment by cornelinux** [comment]
# Parsing old time formats

We could simply parse the string from the database like:

    parse(s)

But if the string does not contain a timezone, a naive datetime is returned.
After parsing, we should check, if the datetime is naive (this would be an old time!) then we need to add the local timezone, we can do this by parsing again:

    parse(s, tzinfo=tclocal)

## Parsing problem

The old time format is ``DD/MM/YY hh:mm`` in the database. 11/04/17 22:00, 24/04/17 22:00.

THe parse command works right in case of 24/04/17 but in case of 11/0417, it thinks it is November 4th.

Maybe we can not use the ``parse`` command?

**Comment by cornelinux** [comment]
<pre>
'2017-02-06T10:00:00'
>>> parse(alt).tzinfo
>>> parse(neu).tzinfo
tzoffset(None, 7200)
>>> d = parse(neu)
>>> d.tzinfo
tzoffset(None, 7200)
>>> parse(neu, dayfirst=True).isoformat()
'2017-06-02T10:00:00+02:00'
>>> parse("23/12/17", dayfirst=True).isoformat()
'2017-12-23T00:00:00'
>>> parse("23/12/17 10:00", dayfirst=True,tzinfos=tzlocal).isoformat()
'2017-12-23T10:00:00+01:00'
</pre>
