### ISSUE TITLE
Redundant ldap3 open() calls

### ISSUE THREAD

**Issue by quynh-axiadids** [privacyidea/privacyidea#650]
Please think about and cover the following questions:

# Versions

privacyIDEA: 2.18

Installation method:

- from source / github
## more details: 

OS: Amazon Linux

Webserver:

Tokendatabase: PostgreSQL

====

Hi @cornelinux,

We are in the progress of testing 2.18 migration.

I found some open() call for ldap3 that creates unnecessary connections to the ldap servers (which may turn out to be very expensive calls in some cases of remote ldap server) (privacyidea/lib/resolvers/LDAPIdResolver.py, line 1042)

I also attempt to remove other redundant open() calls that are followed by a bind(), because the ldap3 documentation states that:

> In ldap3 you establish the connection to the server with the open() method of the Connection object. The bind() method will open the connection if not already open.

(http://ldap3.readthedocs.io/bind.html)

I am looking forward to your input.

Thank you.

**Comment by quynh-axiadids** [comment]
On the hands, I also find that the schema queries are still remaining in most operations...
Would it be sensible in your opinion to have the `ldap3.NONE` as the default behavior for `get_serverpool` method instead?

**Comment by cornelinux** [comment]
Please give us some time to look into this.
Can you please tell, which version of ldap3 you are using?

**Comment by quynh-axiadids** [comment]
The ldap3 version we are using is 2.2.1.

**Comment by fredreichbier** [comment]
I think you're right: As ``create_connection`` already calls ``open``, any calls to ``open`` after a ``create_connection`` call are in fact redundant and cause a slowdown. 

In the PR #651, ``create_connection`` calls ``open`` only if STARTTLS is enabled. However, I think it would be nicer if ``create_connection`` always calls ``open``, because then we get a uniform interface for the function (i.e. we can say "``create_connection`` returns an already-open connection in any case"). What do you think?

Interestingly, the implicit ``open`` call in ldap3's ``bind`` passes ``read_server_info=False``. Maybe we can also do that in ``create_connection``. From a quick glance, authentication seems to work if we do, but some tests fail because ``ldap3mock``'s ``open`` does not take any arguments.

With these changes, I did a quick benchmark with a LDAP userstore + ``otppin=userstore`` policy. The mean response time went from 1200ms down to 580ms, so this is really nice :-)

**Comment by cornelinux** [comment]
I talked to the ldap3 developer and from what he said I get these recommendations:

1. don't use open() if not necessary, because the server information would be read twice. Once in the open statement and once in the bind statement.
Thus we should only use bind().

2. There is one scenario, where we need an open connection ``open()`` before the bind. And this in fact is
Port 389 and StartTLS. we can only do StartTLS on the open connection:

   l.open()
   l.starttls()
   l.bind()

Now the bind will be performed encrypted.

Originally I also thought, hey, lets do the open() in the create_connection, so we always return an open connection. But in most cases (ldap and ldaps/696) this will call two server infos and have performance impact. 
We get better performance if we do it just like in PR #651. Although we in some cases return an open connection (port 389 + STARTTLS) and otherwise return a not-yet-opened connection.

Thus the question is 
a) uniform interface with a defined opened connection or
b) performance

**Comment by quynh-axiadids** [comment]
Hi @cornelinux and @fredreichbier 
Thank you for your researches and thoughts. It has been very insightful.
In my opinion, the b) is not just about performance but also about properly implement the library.
For the a), I think it will also may put some limitation for future enhancements, and may further effect the performance.

**Comment by fredreichbier** [comment]
Well, then I would tend to follow the ldap3 developer's recommendations and remove all unnecessary calls to ``open`` like you did in #651. I guess prioritizing performance makes a lot of sense in a performance-critical code location like the LDAP resolver.

I'm wondering: In the case of STARTTLS, could we then use ``open(read_server_info=False)`` in ``create_connection`` to avoid reading the server info twice?

**Comment by quynh-axiadids** [comment]
I can do some more tests on that idea and also on the bind call with read_server_info=false and update you further.

Thank you for looking into this.

On Mar 16, 2017, at 05:15, Friedrich Weber <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, then I would tend to follow the ldap3 developer's recommendations and remove all unnecessary calls to open like you did in #651<https://github.com/privacyidea/privacyidea/pull/651>. I guess prioritizing performance makes a lot of sense in a performance-critical code location like the LDAP resolver.

I'm wondering: In the case of STARTTLS, could we then use open(read_server_info=False) in create_connection to avoid reading the server info twice?

**Comment by fredreichbier** [comment]
Great, thank you! I just noticed that ``start_tls`` also takes a parameter ``read_server_info`` with defaults to True, so there may be even more room for improvement.

**Comment by cornelinux** [comment]
Please go on discussing the read_server_info in the speical ticket #655. I will merge quynhs pull request and thus close this issue.

**Comment by cornelinux** [comment]
Closed by PR #651
