### ISSUE TITLE
Use U2F device for local login

### ISSUE THREAD

**Issue by foot3print** [privacyidea/privacyidea#690]
Please think about and cover the following questions:

# Versions
- privacyIDEA: 2.18
- ubuntu xenial
- apache2

# What am I trying to do
- Im trying to use u2f tokens for ssh authentication through REST API using pam_exec.so my_skript.sh
So far I managed to follow the workflow in privacyidea.lib.tokens.u2ftoken getting the callenge with

`curl -k --request POST -d "user=pwal&pass=s3cr3tpa55word" https://privacyidea.domain.com/validate/check | python -m json.tool `
-yes I know, its not safe to pass clear passwords... its just for testing purposes ;-)

Response:
{
    "detail": {
        "attributes": {
            "hideResponseInput": true,
            "img": "static/css/FIDO-U2F-Security-Key-444x444.png",
            "u2fSignRequest": {
                "appId": "https://privacyidea",
                "challenge": "vKQv4hEH5XQZ9KEbfTUVAFZW03my6oU1v_fJzd2bi1w",
                "keyHandle": "s4ffkssmYi9ytZojqYrCKn9-LHrXaePHD75CELAbJLVtZ-7MtHJN2vWa2FQrgU4YJORwfCUOoYpAz1chlGJgUQ",
                "version": "U2F_V2"
            }
        },
        "message": "Please confirm with your U2F token (Yubico U2F EE Serial 401665350)",
        "serial": "U2F0001333D",
        "threadid": 140190304835328,
        "transaction_id": "16121718861357964200"
    },
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "status": true,
        "value": false
    },
    "signature": "22078623395394929165224855467848112702859072398640456418070001562061250233357936897948503700832553582001278503442279191273182830295636778388461291686694579501586386580610388363133750537778604903324820117905927073953289680822928038372984024895092842285841880822569736462379942926174285213441629778631934221060763963841415517357855469153006294097752483698402945037292135615293699430057770937885277881718240857610939359760414124647740284403405107832661990322776439031364100688368577681451226492502170647515238428255586507681447616630006258587540442987997086719578203046910198294477619275392813262971224451240288837759369",
    "time": 1493297144.575808,
    "version": "privacyIDEA 2.18.1",
    "versionnumber": "2.18.1"

However, I could not seem to get the 'signatureData' and 'clientData' required for the next API call /validate/check which is returned by u2f.sign :-(

Could you help me on this? Or would this be possible using curl in a shell script?
PS- you can close this ticket if it is too irrelevant. Thank you!

**Comment by cornelinux** [comment]
This sounds quite interesting. However, the problem is, that you can not use u2f to login remotely via SSH, since you need to excute programs on the client side.
If will only work locally, unless you are willing to do some manual nasty copy and paste handling!

Note: U2F was designed for the web, not for native applications!

You need to take the "u2fSignRequest" contents and put it in a file like: ``request.txt``:
<pre>
{
  "appId": "https://puck.az.intern",
  "challenge": "Jqw-WBsA3RvzzxmVH61QohCR7FpAMtusJcw7DD-rh0E",
  "keyHandle": "X_EUn8sCwqQ9PMojBSU8iMZkOwua_R6fYjJrXtjPxfw5Lz1-7HBk68SiT41A4pRMk_dq239FV7d0QBur-I63IA",
  "version": "U2F_V2"
}
</pre>

Then you need to pass this data to the u2f-host command (you would not have to put it in a file the first place, but it is easier to experiment with):

    cat request.txt  | u2f-host -aauthenticate -o https://puck.az.intern

The LED will blink. When you press the LED you get the response:

<pre>
{ "signatureData": "AQAAAAYwRQIgVvE9JnvjmYojp[...]bQ==", "clientData": "eyAiY2hhbGxlbmdlIjogIkpxdy1XQnNBM1J2enp4bV[...]IgfQ==", "keyHandle": "X_EUn8sCwqQ9PMojBSU8iMZkOwua_R6fYjJrXtjPxfw5Lz1-7HBk68SiT41A4pRMk_dq239FV7d0QBur-I63IA" }
</pre>

Now you can send the response to privacyIDEA.

It would be great if you would integrate this into privacyIDEA client components.

I am looking forward to your pull request.

**Comment by foot3print** [comment]
I will try to integrate this test. But for the meantime, im quite busy with work. :-(

**Comment by cornelinux** [comment]
Don't be sad! Be happy. Your work buys you your food! :-)

**Comment by cornelinux** [comment]
@foot3print any news on this?

**Comment by foot3print** [comment]
@cornelinux 
ive been a little occupied these past few days.. Ill try to sqeeze some time on this.. till then, if you want/need to close this ticket, please do so. Ill just open an issue by then. Thanks!

PS. btw, i think ill buy a shirt! :-)
