### ISSUE TITLE
Unset validity_period_end (and other tokeninfo)

### ISSUE THREAD

**Issue by jean-gui** [privacyidea/privacyidea#691]
It would be useful to be able to unset the validity_period_time (and probably other fields if it's easy enough).
My use case is: there are two steps to enroll a U2F device. I'd like to set an expiration date on the token for the first step so that I can remove all U2F enrollments that never completed easily. When enrollment is completed, I want to unset that expiration time.
A workaround would be to set it to a date far in the future, but that's not very elegant.

**Comment by cornelinux** [comment]
There are at least two possibilities to do this.

Either setting an empty value (but this would probably leave the tokeninfo entry, just with an empty value) or deleting the entry with a call like

    DELETE /token/set/<serial>?key=tokeninfo_key

or 

    DELETE /token/set/<serial>/<tokeninfo_key>

**Comment by cornelinux** [comment]
hm, token/set is originially used to set values in the token table like description, sync window, count window.

There are some logical additions like count_auth_max and validity_period which are stored in the tokeninfo table. We could however use an API to set arbitrary tokeninfo keys and values. At the moment such an API does not exist.
Deleting validity_period should probably be part of such an API.

    POST /token/info/<serial>/<key>?value=
    DELETE /token/info/<serial>/<key>

We do not really *need* a get request, since all this information is returned with GET /token
