### ISSUE TITLE
pi-manage crashes

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#696]
# Version

privacyIDEA dev version

# Error occurs

When running a pi-manage command on ubuntu 16.04 in a productive environment I get:

<pre>
Traceback (most recent call last):
  File "./pi-manage", line 486, in <module>
    manager.add_command('profile', CommandOutsideRequestContext(profile))
TypeError: object() takes no parameters
</pre>

**Comment by fredreichbier** [comment]
Interesting! You're right, this happens due to a version mismatch: While requirements.txt refers to flask-script 2.0.5, Ubuntu 16.04 ships flask-script 0.6.7 -- in this version, the ``Command`` [does not define](https://github.com/smurfix/flask-script/blob/v0.6.7/flask_script/commands.py#L90) an ``__init__`` function. I'll try to get the ``profile`` command working with the 0.6.7 API tomorrow.
