### ISSUE TITLE
Verify: Optimize condition checking

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#762]
Could we speed up condition checking?

See
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/eventhandler/base.py#L325

Conditions are checked with a long list of ``if`` statements. All following ``if``-statemens seem to contain 

     and res

So if the result for **any** check is ``False`` and skip many if statements, which would be False anyway (since ``res`` is False)

Please verify.

**Comment by cornelinux** [comment]
Should we replace every 

    res = False

by 

     return False

and remove all ``and res`` from the conditions?

**Comment by fredreichbier** [comment]
Well, I think returning early would probably be faster. If we don't want to touch the code structure too much, we could also use ``if res and ...:`` instead of ``if ... and res:`` to benefit from short-circuiting.

But I'm not sure if the difference would be noticeable in any case: We could do some benchmarking to check that.

**Comment by cornelinux** [comment]
2ms! ? ;-)

**Comment by cornelinux** [comment]
Hm, I tested with timing ``test_lib_events.py``. And the results we "rather similar" with the orinigal. 24.99 - 25.7 seconds.
If the tests are representative, I assume the question is simply what is more readable.

**Comment by fredreichbier** [comment]
Hm, interesting. I guess there is not much difference because the branching conditions do not do much: simple checks like ``"logged_in_user" in conditions`` are probably pretty fast.

For readability, I agree it would be better to remove the ``and res`` conditions and use ``return False`` in the ``if`` bodies instead?
