### ISSUE TITLE
Revoking a Token disables challenge response generation for other tokens of that user

### ISSUE THREAD

**Issue by lavesh-axiadids** [privacyidea/privacyidea#771]
Created multiple tokens for a user with same pin. Lets say 3 tokens A, B and C
Out of these 3 tokens, one of the tokens is revoked.

When hitting the url /validate/check?user=<user>&pass=<pass>, multiple challenge request is not getting generated for other tokens. This is happening as **TokenAdminError: ERR1007: This action is not possible, since the token is locked** is getting raised when any one of the tokens is revoked/locked.

Is it possible to generate challenge request for Enabled tokens other than the tokens which are 
revoked

Here is the traceback of the issue:-
Traceback (most recent call last):
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/token.py", line 1977, in check_token_list
    options=options):
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/log.py", line 154, in log_wrapper
    return func(*args, **kwds)
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/tokens/emailtoken.py", line 206, in is_challenge_request
    return self.check_pin(passw, user=user, options=options)
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/policydecorators.py", line 89, in policy_wrapper
    return self.decorator_function(wrapped_function, *args, **kwds)
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/policydecorators.py", line 613, in auth_otppin
    return wrapped_function(*args, **kwds)
  File "/Users/lavesh/dev/privacyidea2/privacyidea/lib/decorators.py", line 43, in token_locked_wrapper
    "token is locked"), id=1007)
TokenAdminError: ERR1007: This action is not possible, since the token is locked

Thanks,

**Comment by cornelinux** [comment]
If the user has several challenge response tokens and one of the challenge response tokens is locked, the other tokens should create a challenge.

We are looking into this.

I *assume* this could be due to the decorator, which checks the lock-state of a token and raises an exception.

**Comment by cornelinux** [comment]
I just added a test, which reproduces this problem.

One toke locked, one token active => response fails.

**Comment by cornelinux** [comment]
It breaks in ``tokenobject.is_challenge_request`` in the ``token.check_pin`` call.
https://github.com/privacyidea/privacyidea/blob/771/multipleCR/privacyidea/lib/token.py#L1947

``check_pin`` has token lock decorater which throws an exception, which works nice in most cases.
https://github.com/privacyidea/privacyidea/blob/771/multipleCR/privacyidea/lib/tokenclass.py#L385

There are at least two approaches to deal with this:

1. catch the exception in the ``check_token_list``, which does not work nicely, since the exception is raised from within the if condition. We would have to extract the condition and catch the exception before. This would break our nicely stacked if-else-statements.

2. add an options key to the ``is_challenge_request`` which gets passed to the ``check_pin`` which could signal the decorator to not raise an exception but to return False.

@fredreichbier Would I prefer version 2?

**Comment by fredreichbier** [comment]
Hmm, I agree (1) is not very nice. However, I think having a function argument that changes the function behavior like in (2) is not super-nice either :-)

Just a thought: What about modifying ``is_challenge_request`` such that it catches the ``TokenAdminError`` and returns ``False`` in case it is raised?

**Comment by cornelinux** [comment]
This would change the overall behaviour:

If the user has only one token or tries to authenticate with a specific token and this token is locked, he gets an exception in the response i.e. HTTP Return 400. 

If we changed to False, he would only get: You failed to authenticate.

The problem is really to distinguish between only one token that is locked and a successful auth, although one of the many tokens of a user is locked.

**Comment by fredreichbier** [comment]
I see, that's not optimal either.

Well, then, I don't have a strong opinion on this -- personally I would go for (1) even though it messes up the ``if`` structure a bit just because we don't have to touch a lot of different code locations then :-) But that's just personal taste.

**Comment by cornelinux** [comment]
I take the third approach. Remove locked tokens from the list to be checked. :-)
