### ISSUE TITLE
Replication stops caused by temporary disconnect where node1 deletes and node2 updates (revokes) the same token

### ISSUE THREAD

**Issue by sandervanburken** [privacyidea/privacyidea#792]
# What did you try to do?

Test master-master replication with this set up:

* Two Ubuntu 16.04.3 LTS servers with latest patches installed
* MySQL 5.7.19
* PrivacyIDEA packages:
  * privacyidea-nginx                  2.19.1-1xenial
  * privacyidea-radius                 2.19.1-1xenial
  * python-privacyidea                 2.19.1-1xenial
* Followed these instructions:
  * http://privacyidea.readthedocs.io/en/latest/faq/high-availability.html?highlight=replication
  * https://www.digitalocean.com/community/tutorials/how-to-set-up-mysql-master-master-replication

Test case:

* Starting with a working set up with two nodes AND replication
* Create token on server1
* Observe that this token is listed on server2
* Observe that is it possible to use this token on server1 and server2 with `radtest`
* Disconnect the servers (On both servers: `iptables -A INPUT -p tcp --dport 3306 -j DROP`)
* On web portal of server1 revoke the token
* On web portal of server2 delete the same token
* Reconnect the servers (On both servers remove the rule)

Result:

* Replication on server2 fails; it can't replicate the 'update query' from server1 (revoke token) since it has already deleted this token.

Bonus:
* It is possible to re-enable replication on server2:

```sql
set global sql_slave_skip_counter=1;
stop slave;
start slave;
```

# What outcome did you expect?

That replication does not stop.

# What outcome did you experience?

Replication stopped. Had to manually intervene to start it again.

# Configuration

* privacyIDEA Version: 2.19.1

* Installation method: Ubuntu packages

## more details: 

* OS: Ubuntu 16.04.3 LTS

* Webserver: nginx (1.10.3)

* Tokendatabase: MySQL (5.7.19)

**Comment by cornelinux** [comment]
Funny guy - you.

1st this is a database issue. The database is totally transparent for privacyIDEA. 
Ask the question in a mysql channel.

You also do not take a hammer and hit on the hard disk and the come around and ask, what is wrong with privacyIDEA - it does not work anymore!

2nd: I very much recommend think about your issue youselve at least twice, so that you realize that this is a stupid idea.

**Comment by sandervanburken** [comment]
@cornelinux Thank you for your reply. Be assured that I really appreciate the hard work you have put into making this product and providing it to the community!

I need Master-Master replication to connect sites on different continents through a WAN connection. That is why I tested a scenario where:
* the two Masters loose their connection to each other
* 'users' make changes on both sites
* the connection is restored

1. Is PrivacyIDEA designed for the scenario I described?
2. Did I miss PrivacyIDEA documentation about how to set up Master-Master replication?

**Comment by cornelinux** [comment]
As I try to point out. There is nothing privacyIDEA can do about this. Because one privacyIDEA instance does not know, that there is another privacyIDEA instance. 
This is all a matter of the underlying database. And the database has obviously a hard time to decide, if a token should be deleted or revoked - what is the "real state". This is why I tell you, you should ask mysql guys!

In this case you need to fix the database manually - probably take down one node and replicate again the node YOU decide to be the real/current one.

1. No, privacyIDEA is not designed for this scenario, since the database level is not designed for this scenario.
2. No probably not.

**Comment by sandervanburken** [comment]
Thank you for clarifying these points!

**Comment by berndnicklas** [comment]
Multi-master replication like provided in Galera typically needs at minimum 3 nodes to assure all nodes reach a consensus about (1) which nodes are currently in the cluster, (2) which nodes are temporarily or permanently disconnected from the cluster and (3) who is the current writing master.

A setup of 3 nodes allows for maximum 1 node failing. A setup of 2 nodes with losing connectivity between the nodes will result in split-brain situations and inconsistent data, since both nodes will think they are (1) alone in the cluster and (2) the writing master, see e. g. [MySQL Galera Cluster documentation > Getting started > Minimal cluster size](https://mariadb.com/kb/en/library/getting-started-with-mariadb-galera-cluster/).
