### ISSUE TITLE
Action: "passOnNoUser" and "passOnNoToken" are ignored after upgrade to version 2.20

### ISSUE THREAD

**Issue by simvirus** [privacyidea/privacyidea#798]
After the upgrade to the version 2.20 the "passOnNoUser" and "passOnNoToken" are ignored:

**Reply-Message = "ERR905: The user can not be found in any resolver in this realm!"**

The config is:

```
Scope: authentication
Action: { "reset_all_user_tokens": true, "passOnNoUser": true, "passOnNoToken": true, "otppin": "none" }
Realm: [ "business" ]
User: []
```

A rollback to the previous version is needed to remove the issue introduced with the new version

Thanks

---
Sim

**Comment by cornelinux** [comment]
@simvirus thanks for the notification!
We added the resolvers to several policies - unfortunately to the PASSNOUSER policy - which makes no sense, since the user object would contain no resolver. Hm. But nevertheless the user object would have no resolver and the policy should be found. We should add a test case for this!

See this file: https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/policydecorators.py#L261

>   2017-07-20 Cornelius Kölbel <cornelius.koelbel@netknights.it>
>              add resolver dependent policy for lastauth, otppin, passthru,
>              timelimit, losttoken

Add a testcase here:

Strange - this policy should actually work 
https://github.com/privacyidea/privacyidea/blob/master/tests/test_lib_policydecorator.py#L184

-> investigate

**Comment by simvirus** [comment]
Hello Cornelius,
let me know how I can help you.
For now i've downgraded to the previous version (2.19.1) for solve the issue.
Regards

**Comment by cornelinux** [comment]
Hi @simvirus 
I am trying to reproduce this error in a test case - currently with no luck.

I am defining this policy:

    set_policy(name="pol1",
               scope=SCOPE.AUTH,
               action="{0}, {1}, {2}, {3}=none".format(
                   ACTION.RESETALLTOKENS,
                   ACTION.PASSNOUSER,
                   ACTION.PASSNOTOKEN,
                   ACTION.OTPPIN
               ),
               realm=self.realm1)

Which basically looks like yours.

But the question is: Which parameters do you pass to the in the HTTP Request. Maybe you are passing a wrong resolver?

Can you please verify which data your application sends to privacyIDEA in the ``/validate/check`` request!?

**Comment by simvirus** [comment]
Hello Cornelius, thanks for reply!

Here a new test (with 2.19.1 downgraded):

`https://192.168.200.81/validate/check?user=test&pass=test&realm=business`

`jsonrpc	"2.0"
signature	"...."
detail	
message	"The user does not exist, but is accepted due to policy 'business_authentication'."
threadid	140105415108352
versionnumber	"2.19.1"
version	"privacyIDEA 2.19.1"
result	
status	true
value	true
time	1507276016.69491
id	1
`

`35710 	10/6/17 09:46:56 	GET /validate/check 	1 					test 	business 		192.168.200.252 	The user does not exist, but is accepted due to po 	OK 	OK 			192.168.200.81`

And now with 2.20.... "apt-get upgrade" ..... Browser refresh (F5)

`jsonrpc	"2.0"
signature	"...."
detail	null
version	"privacyIDEA 2.20"
result	
status	false
error	
message	"ERR905: The user can not be found in any resolver in this realm!"
code	905
time	1507276173.853275
id	1
`

`35713 	10/6/17 09:49:33 	GET /validate/check 	0 					test 	business 		192.168.200.252 	ERR905: The user can not be found in any resolver 	OK 	OK 			192.168.200.81`

Regards

**Comment by cornelinux** [comment]
I am sorry, I can absolutely not reproduce this. Not with test cases, not with a running system.
Obviously you have some contradicting settings - policies or events, which lead to a changed behaviour in 2.20 in contrast to 2.19.1.

There are two possible steps:

1. Upload the output of Config->get System Documentation to https://lancelot.netknights.it/owncloud/s/3SF2FO5Z19x98S8
**Remove any potential passwords**

2. Get a remote session.

**Comment by cornelinux** [comment]
We determined, that it is due to the policy, which contains a resolver.
The problem is:

if the policy contains a *realm* and a *resolver*, a non-existing user will create an internal user-object ``User(name, realm, None)`` with no resolver. But such a user will not match the policy => the policy for PassOnNoUser will not match.

Solution: Remove the resolver from the policy.
