### ISSUE TITLE
EMail tokens not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by sed-sytarchuk** [privacyidea/privacyidea#799]
I am currently trying to get email tokens working with our Privacyidea server and it doesn't seem to send the token for the email token for the user. I've checked the email settings and it is able to send a test email but when it comes to the token, it doesn't seem to work. Our email server doesn't have any logs regarding the token email and there isn't anything in the privacyidea log regarding this.

I tried getting privacyidea set up with CentOS7 and email tokens worked there but it lacked the apache2-client we wanted.

# What outcome did you expect?

It should send the otp token emailed to the user

# What outcome did you experience?

The email wasn't set

# Configuration

* privacyIDEA Version: 2.20

* Installation method: ubuntu packages

## more details: 

* OS: Ubuntu 16.04.03

* Webserver: Apache2

* Tokendatabase: MySQL

Let me know if you need anything else.

Thanks.
Dean
[privacyidea.log](https://github.com/privacyidea/privacyidea/files/1360815/privacyidea.log)

**Comment by cornelinux** [comment]
Hi Dean,
I think this might be a configuration or user problem.
We try to put those to https://community.privacyidea.org and use github issues not for questions but for real bugs, feature requests and enhancements - regarding development.

You do not tell, what you try to do. I assume you do not know how to trigger the sending of the email - since you do not tell anything about this.!
An email is triggered, if the user authenticates with his OTP PIN/password.

If you do not mind, please ask this at the above mentioned community forum.

Kind regards
Cornelius
