### ISSUE TITLE
Dot in realm causes issues. 

### ISSUE THREAD

**Issue by justin-p** [privacyidea/privacyidea#808]
Good afternoon,
We currently have privacyIDEA deployed on a server, but (unfortunately) we are having some difficulties with getting realms to work. 
In our use case we want to use TOTP tokens on an Citrix Netscaler. The user logs in with their UserPrincipalName (user@domain.tld) and password ( which gets passed on to an Active Directory) on the NetScaler 'vserver'. 
Whenever the AD login is succesfull the Netscaler passes the UserPrincipalName and Token to PrivacyIDEA. We use the FreeRADIUS Perl plugin to catch this reqeust on PrivacyIDEA.

On the PrivacyIDEA side we created a LDAP resolver for this domain named 'domain1'. After that we created an realm named 'domian1.tld'. Whenever we do this the privacyIDEA is unable to fetch data of the LDAP user when we open the user in privacyIDEA. We get the following error : 'ERR905: The user can not be found in any resolver in this realm!'.
However when we simply create a new realm without a dot, like domain1_tld, and connect the 'domian1' LDAP resolver to this realm it works fine. 

Currently as an work around we created 1 realm which is the default and has all the LDAP resolver. This works fine for the time being. Currently all the customers that need 2FA are located in the same Active Directory. But we would also like to use this deployement for other AD's.

Is there a possibility that dots inside realms are not supported by privacyIDEA? Or is there any way we can further diagnose the problem? 

# Configuration

* privacyIDEA Version:
2.20

* Installation method:
Ubuntu packages

* OS:
Ubuntu 16.04 

* Webserver:
NGINX

* Tokendatabase:
MySQL

**Comment by cornelinux** [comment]
Hello @justin-p 
thanks for the detailed description.
You are right, *dots* are currently not allowed in privacyIDEA. This is a remnant of linotp, where configuration parameters where deviced by dots - since all configuration was stored in one DB table.

However I assume that this limitation is not necessary anymore. We probably could drop this.

Putting this as a task for next release: **investigate**

**Comment by justin-p** [comment]
Thanks @cornelinux, looking forward to the next release.

**Comment by johnolavselland** [comment]
Hello @cornelinux and @justin-p 
I have an issue that's similar to #808.
What i'm try to do is making multiple Realm's as AD Domains, lets say test1.lab and test2.lab
I make one LDAP resolver per Realm, LDAP1->test1.lab and LDAP2->test2.lab. Both resolvers are set up with sAMAccountName,userPrincipalName as logon attribute.

When I try to login to PrivacyIdea with full UPN, (user1@test1.lab) I get successfully logged on as expected. I can see in the upper right corner that I'm logged on as user1 @test1.lab (user)
After some research it seams to be the sAMAccountName the system is using to authenticate with and if I modify the LDAP resolver to only userPrincipalName, I get wrong credentials.

This happens when I've configured Realm with dots, if I configure both the Realms without dots it's working well. I can authenticate with UPN and the LDAP resolver only have the UPN logon attribute.

I've tried to turn on and off the "Use @ sign to split the username and the realm", but I cannot see any differences in the log file (privacyidea.log)

The log says:
[2018-04-23 23:00:12,853][3429][140431148431104][INFO][privacyidea.lib.user:346] User u'user1' from realm u'test1.lab' tries to authenticate
[2018-04-23 23:00:12,856][3429][140431148431104][ERROR][privacyidea.lib.user:362] The user User(login=u'user1', realm=u'test1.lab', resolver='') exists in NO resolver.

It seams that PrivacyIdea only read userid before @sign, it then make sense that I can logon with sAMAccountName and not userPrincipalName

Did you get it work @justin-p after upgrade?

I'm also using Citrix Netscaler and have to use UPN cross multiple AD domains.

Am I doing something wrong?

**Comment by justin-p** [comment]
Hi @johnolavselland, @cornelinux 

I actually faced the same issue @johnolavselland was describing. For now I ended up using 1 realm since I had the privilege of both customers using the same AD (and the deadline was getting to close).

Using `user1@test1.lab@test1.lab` in combination with a netscaler won't work since it won't pass the username/password check.
![alt text](https://i.imgur.com/ODaRlti.png)
It would simply pass `user1@test1.lab@test1.lab` as the username to AD. Since this isnt a valid UPN/SAM the user/password check will fail.

After some quick googles I did find [this article](https://support.citrix.com/article/CTX231525) describing how to change a UPN to SAM before its being send to a RADIUS server. You would proablly need a recent firmware since this uses the [nFactor authentication framework](https://support.citrix.com/article/CTX222713).
I reckon you could use this prinicple to simply append the domain name to the request. If the REALM in PrivacyIDEA matches the domainname I think that would work. The expression would probally look something like this
`q{http.req.user.name.after_str("@") + http.req.user.name.after_str("@") + http.req.user.name.before_str("@")}`

Can't test this at the moment though, are you able to @johnolavselland ?
