### ISSUE TITLE
Improve debug and support

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#829]
When giving support it is sometimes difficult to 

1. collect all information
2. analyze the problem

We could improve both steps.

# Technical means

We could have the administrator easily create some kind of support information package, which the administrator could send. Thus the administrator does not need to collect all data himself but simply needs to push a button.

In the Subscription file there are contact information of the subscription issuer. From these issuer information we could use 

* a URL to upload such a support tgz to our owncloud upload folder or to any other location. i.e. to the given URL.
* an email address to send an email to the subscription issuer's support email address automatically opening a ticket.

The nice side effect is, that this will only work if a valid subscription file was imported.

## thoughts

Opening a ticket via email would be great. But then the administrator would have to configure a mail server. The size of attachment could be to large for the mailserver.

Sometimes https connections for privacyIDEA systems is blocked. But uploading via https looks like it could be easily possible without additional configuration and we have "no" size limit.

As an alternative the administrator could also download the support file and process it manually

A logged in administrator might not have enough rights to read all necessary information.
Should we put this functionality on the command line? Add a tool that collects all information from the database?

## contents of support tgz

We could have the administrator select the preferred content like:

* realm and resolver configuration
* policy configuration
* event configuration
* audit log dump
* privacyidea log

Also see: ``system->documentation``.

# Additional auditing for better analyzing problems

In certain cases the administrator wonders why the system is behaving in an unexpected way. Often this is due to policies or events not matching as expected.

We could add another column to the audit log containing something like *applied policies* for each request. During the request we could gather all policy definitions, that where applied to this request.
E.g. Thus we would immediately understand, that in this request the user was authenticated with otppin form a user store...

The question is, where we would add these applied policies. It might be necessary that each policy check takes care of this itself. But this in turn would produce a lot of lines of code and would also be prone to errors.
It would be nicer, if we were able to handle this centrally. (A decorator for the policy decorators?)

**Comment by fredreichbier** [comment]
Some thoughts:

**@ support package**

So, this would essentially be a more advanced extension of the "System Documentation" feature, right? I think some command-line "wizard" in which the administrator can select/deselect the contents of the support package sounds great. I agree that the attachment could be too large for an email. What about providing a simple "upload URL" which can be used with, e.g. curl? Like
```
curl -F package=@support-package.tgz https://upload.support.netknights.it/some-customer-specific-key
```
If https connections are disallowed, the administrator could simply download the support package and upload it from some other machine.
Couldn't we also add a public key to the subscription file which can be used to encrypt the support package?

**@ adding activated policies to the audit log**

I think this is also a good idea! If we do not want to change the audit table schema, we could also add a DEBUG logging output that sums up the activated policies for each request in a first step.

On the technical side, I think we have to differentiate between pre- and postpolicies:
* I noticed that the *prepolicies* all return `True` in any case, but the return value doesn't seem to be processed. Couldn't we use the return value to indicate whether the policy was activated? The ``prepolicy`` decorator could then construct a list of activated policies in the request context (e.g. ``g.activated_prepolicies``), i.e. a list of all policy functions that returned ``True``.
* For *postpolicies*, it seems to be a bit harder because they return the new response. Maybe the ``postpolicy`` decorator could check whether the response was modified by the postpolicy? (e.g. ``if new_response != old_response or new_response.data != old_data: ...``).

Or we make this explicit and add a function ``announce_policy_activation()`` or something like that. We would just need to insert calls to that function at the right places.

**Comment by cornelinux** [comment]
* In 2.22 we will add the support package functionality.
* Before creating the support package, check the log level and warn the administrator, that he probably should increase the log level.
* The support package would be pgp encrypted with a key from the subscription file. (cons: the admin can not see, what is in the support file)
* The admin should be able to easily upload the file to our owncloud. The owncloud upload link should be available in privacyIDEA.

**Comment by cornelinux** [comment]
We should start with a simple tool 

    privacyidea-diag.sh

that creates a zip file and either uploads it to our owncloud or asks the admin to upload it manually.

As mentioned above, the zip can contain:

* system config
   * resolvers?
   * events?
   * policies?
* log file
* operating system
* versions
* audit log dump from the last lets say 7 days...
* a few excerpts from the pi.cfg

We should keep it simple and at least gather the information, that are accessable from the root shell.
