### ISSUE TITLE
http proxy settings is confusing

### ISSUE THREAD

**Issue by michalmedvecky** [privacyidea/privacyidea#835]
# What did you try to do?

Send SMS via Twilio https gateway over http proxy.

This is my SMS gw setup:

```
      module: "privacyidea.lib.smsprovider.HttpSMSProvider.HttpSMSProvider"
      description: "Twilio"
      name: "smsgw_01"
      option.CHECK_SSL: "yes"
      option.HTTP_METHOD: "POST"
      option.PROXY: "http://1.2.3.4:3128/"
      option.URL: "https://api.twilio.com/2010-04-01/Accounts/{{ smsgw_user_twilio }}/Messages"
      option.PASSWORD: "{{ smsgw_password_twilio }}"
      option.Body: "OTP: {otp}"
      option.To: "{phone}"
      option.From: "{{ smsgw_from_twilio }}"
      option.USERNAME: "{{ smsgw_user_twilio }}"
```

I would never expect I need to set up sms gw `PROXY` option to `https://1.2.3.4:3128/`, as the specifier itself is not valid (proxy @ 1.2.3.4:3128 talks http only). 

Could you document this better?

Folks are used to `http_proxy` and `https_proxy`. It's a bit confusing also in bash/wget:

```
ubuntu@deployer:~/twilio$ export https_proxy=https://1.2.3.4:3128
ubuntu@deployer:~/twilio$ wget https://github.com
--2017-11-01 12:05:27--  https://github.com/
Connecting to 1.2.3.4:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                                          [  <=>                                                                                                                                                   ]  50.21K   236KB/s    in 0.2s

2017-11-01 12:05:28 (236 KB/s) - ‘index.html’ saved [51410]

ubuntu@deployer:~/twilio$ export http_proxy=https://1.2.3.4:3128
ubuntu@deployer:~/twilio$ wget http://github.com
Error in proxy URL https://1.2.3.4:3128: Must be HTTP.
```

obviously, it must **not**:

```
ubuntu@deployer:~/twilio$ export http_proxy=1.2.3.4:3128
ubuntu@deployer:~/twilio$ wget http://github.com
URL transformed to HTTPS due to an HSTS policy
--2017-11-01 12:06:50--  https://github.com/
Connecting to 1.2.3.4:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1                                                        [  <=>                                                                                                                                                   ]  50.21K   217KB/s    in 0.2s

2017-11-01 12:06:51 (217 KB/s) - ‘index.html.1’ saved [51410]
```

**Comment by cornelinux** [comment]
We use the ``http:<proxy>`` or ``https:<proxy>`` notification to distinguish if this is an http or https proxy. This is passed to the ``requests`` module, which expects a dictionary like

     {"https": "your.proxy.com:3128"}

Can you add a corresponding comment in the file ``sms_gateway_config.rst``?
https://github.com/privacyidea/privacyidea/blob/master/doc/configuration/sms_gateway_config.rst#http-provider

THanks a lot!

**Comment by splashx** [comment]
Regarding the proxy setting, the implementation and understanding is wrong. Just to draw a parallel, Linux systems will support two variables for http/s proxy: `http_proxy` and `https_proxy`. If you set `http_proxy` and try to go to `https://something.com` it wont work. So you must explicitly set `https_proxy`. In summary, if you have this setup:

* `http_proxy=http://10.1.2.3:3128/` - it means: for `http` schema @ destination (e.g. `someting.com`), use clear-text proxy `10.1.2.3:3128`
* `https_proxy=http://10.1.2.3:3128/` - it means: for `https` schema @ destination, use clear-text proxy `10.1.2.3:3128`

Then enters something called "[secure web proxy](http://dev.chromium.org/developers/design-documents/secure-web-proxy)". I know, it's rarely implemented in browsers[[1]](https://curl.haxx.se/mail/lib-2016-09/0119.html) and clients BUT it's a thing. Squid supports it. It has nothing to do with the destination address - it has to do with the fact that *all* connections between client and proxy is encrypted. And that is declared in the schema part of the proxy, like:

* `http_proxy=https://10.1.2.3:3128/` - it means: for `http` schema@destination, use secure-web proxy `10.1.2.3:3128`
* `https_proxy=https://10.1.2.3:3128/` - it means: for `https` schema@destination, use secure-web proxy `10.1.2.3:3128`

Reason why privacyidea must support two settings for `http` and `https` schemas @ destination - and this should not be related to the _proxy_ schema.

So, doing: `https:10.1.2.3:3128` means  _send via unknown-proxy-schema `10.1.2.3:3128` if the destination schema is `https`_ . I'm assuming `requests` defaults to _plain-text proxy_ when the proxy schema is not defined, but even [requests doesn't recommend that](https://github.com/requests/requests/blob/master/docs/api.rst#api-changes-1) and it will throw an exception in `2.x`:

```
The proxy API has changed slightly. The scheme for a proxy URL is now required.

proxies = {
  "http": "10.10.1.10:3128",    # use http://10.10.1.10:3128 instead
}

# In requests 1.x, this was legal, in requests 2.x,
#  this raises requests.exceptions.MissingSchema
requests.get("http://example.org", proxies=proxies)
```

To avoid major UI rework for now I would recommend fixing the proxy schema to `http` (since secure-web-proxies are rare) for both `http` and `https` @  destination.

[1] - https://curl.haxx.se/mail/lib-2016-09/0119.html

**Comment by cornelinux** [comment]
To cope with the difference of https-proxy and secure procy connection, we might add additional SMS Gateway options like ``HTTPS_PROXY`` (which is used in case the ``URL`` has an https scheme) and ``HTTP_PROXY`` (which is used in case the ``URL``  has an http scheme.

The backward compatiblity will be the ``PROXY`` setting, if it exists. It will be marked deprecated and be deactivated/grayed-out in the UI.
