### ISSUE TITLE
OTP counter of offline token is set wrong

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#840]
The otp counter of an offline token is set wrong.
It is set to 1 + offlinecount.

It should be set to currentcount + offlinecount.

**Comment by cornelinux** [comment]
Problem is the strange inc_otp_counter

**Comment by fredreichbier** [comment]
I checked the occurrences and it seems like the interface with ``counter=None`` was only used in tests. Because of that, I renamed the function to ``advance_otp_counter`` and removed the without-parameter case.

I was hesitant to call it ``set_counter`` (1) because there already is a function ``set_otp_counter`` and (2) because I find it counterintuitive, as ``set_counter(count)`` actually sets the token counter to ``count + 1``.  So I went with ``advance_otp_counter``, but of course I am open to suggestions!

Alternatively, we could think about unifying ``set_otp_counter`` and ``advance_otp_counter``.

There is one edge case: ``inc_otp_counter(0)`` used to increment the counter by 1 (because ``0`` is Falsey), but ``advance_otp_counter(0)`` now sets the counter to 1. We should check that this change does not cause unwanted behavior.

And in general, we should check this change for off-by-one errors ... I already caught one :-)

**Comment by cornelinux** [comment]
I know that this counter function is counter-intuitve. 
But honestly, I also think that the name "advance" sounds a bit strange.

I think we probalby need to redo the complete counter setting to something, that is more clear. I think there are a lot of hidden conditions or logics in it.

**Comment by fredreichbier** [comment]
Yes, I agree that "advance" also sounds weird. Maybe it would be better to unify ``set_counter`` and ``advance_otp_counter`` then.

**Comment by cornelinux** [comment]
Just from the naming I propably would expect ``set_counter`` to set a counter:

    def set_counter(counter = None):
          token.counter = counter

and ``inc_counter`` to increase a counter:
    
    def inc_counter(counter = 1)
          token.counter = token.counter + counter


??
