### ISSUE TITLE
Attestation Certification Validation

### ISSUE THREAD

**Issue by mostafahussein** [privacyidea/privacyidea#926]
# What did you try to do?
I am trying to enroll U2F token using [U2FZero](https://github.com/conorpp/u2f-zero) device

I would like to know the reason of having the following [validation](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/u2f.py#L123-L128) as I am trying to understand the need of U2FZero certification, do I need to renew it ? btw I don't have any problems with services like Google regarding the old U2FZero certificate but i do have a problem with adding the device to privacyidea. That's why I am asking about the importance of this validation step and what will happen if I commented these [lines](https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/u2f.py#L123-L128)

# Attestation Certification:
```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 0 (0x0)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer: C=US, ST=VA, L=Blacksburg, O=ConorCo, CN=conorco.com/emailAddress=conorco@conorco.com
        Validity
            Not Before: Feb  2 22:04:24 2017 GMT
            Not After : Mar  4 22:04:24 2017 GMT
        Subject: C=US, ST=VA, L=Blacksburg, O=U2F Zero, CN=u2fzero.com/emailAddress=conorco@conorco.com
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:a1:15:5e:63:72:c3:45:ec:97:c1:2a:c2:ba:84:
                    f8:63:f1:ae:6f:f1:7d:80:04:02:a1:9f:86:06:e4:
                    22:a7:c0:2b:e4:e3:44:61:15:3e:fb:d4:13:24:ec:
                    84:b2:54:ec:58:52:91:0d:55:b1:9b:30:79:f5:88:
                    db:f3:05:83:9a
                ASN1 OID: prime256v1
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:20:5c:9e:1d:0d:57:cc:2f:0b:25:f0:97:1c:bf:
         39:8e:a3:b2:0f:9c:97:71:fb:fe:88:f4:f9:a1:03:13:4c:b6:
         02:20:26:ee:da:ae:d8:bf:7c:93:70:0f:cd:1a:26:4c:52:fa:
         e3:86:29:33:50:b1:7a:21:11:2c:03:39:8d:fd:e2:56
-----BEGIN CERTIFICATE-----
MIIB3jCCAYUCAQAwCgYIKoZIzj0EAwIwezELMAkGA1UEBhMCVVMxCzAJBgNVBAgM
AlZBMRMwEQYDVQQHDApCbGFja3NidXJnMRAwDgYDVQQKDAdDb25vckNvMRQwEgYD
VQQDDAtjb25vcmNvLmNvbTEiMCAGCSqGSIb3DQEJARYTY29ub3Jjb0Bjb25vcmNv
LmNvbTAeFw0xNzAyMDIyMjA0MjRaFw0xNzAzMDQyMjA0MjRaMHwxCzAJBgNVBAYT
AlVTMQswCQYDVQQIDAJWQTETMBEGA1UEBwwKQmxhY2tzYnVyZzERMA8GA1UECgwI
VTJGIFplcm8xFDASBgNVBAMMC3UyZnplcm8uY29tMSIwIAYJKoZIhvcNAQkBFhNj
b25vcmNvQGNvbm9yY28uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoRVe
Y3LDReyXwSrCuoT4Y/Gub/F9gAQCoZ+GBuQip8Ar5ONEYRU++9QTJOyEslTsWFKR
DVWxmzB59Yjb8wWDmjAKBggqhkjOPQQDAgNHADBEAiAgXJ4dDVfMLwsl8JccvzmO
o7IPnJdx+/6I9PmhAxNMtgIgJu7arti/fJNwD80aJkxS+uOGKTNQsXohESwDOY39
4lY=
-----END CERTIFICATE-----
```

# Configuration

* privacyIDEA Version:
Latest

* Installation method:
Github

**Comment by cornelinux** [comment]
Probably nothing would happen. The question is, if you would trust the issuer anyways.
This is one of many points, where U2F fails some clarity.

It would be great if you would provide a pull request, that adds a policy like "ignore validity of attestiion certificate" in the u2f enrollment policies:
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/lib/tokens/u2ftoken.py#L254

Why and how would an attestation certificate be used?

The service where a U2F device is registered would use the attestation certificate to trust that there is a valid hardware device by verifying the signature. A "rogue user" could make an attestation certificate or forge a signature and use a piece of software and claim to the registering service that he is using a hardware device.

Why would a hardware vendor choose a short living attestation certificate? Maybe because he does not trust his device either. (Or the concept of x509 certifficiates ;-)

I have not check the attestation certificates of my U2Fzeros, yet. It could however be, that Conor thought this would be demo devices and thus chose such a short validity period.

**Comment by cornelinux** [comment]
@mostafahussein I can confirm that my U2Fzero also has an attestation certificate with a not valid time!

**Comment by mostafahussein** [comment]
@cornelinux Thanks for your explanation, Sorry I was not able to send a PR that solves the issue.
Thanks again
