### ISSUE TITLE
Limit the number of Challenge/Response sent, to avoid being spammed

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea#933]
The SMS could be limited to a certain number of SMS sent per time interval.

## Background info

SMS needs to be triggered by the user's password or by an administrator. In certain cases SMS could be triggered without any proof, i.e. anyone could trigger SMS simply by knowing the username.
The user would be spammed with SMS.

So we could limit the sending of SMS like ``5sms/5minutes``.

### Downside 

An attacker could prevent the user from being able to login. The attacker would "use" all 5 SMS per 5 minutes, and the user would not be able to login for 5 minutes. And again for 5 minutes. And again...

**Comment by cornelinux** [comment]
This is similar to #3078 

We could add additional information to the audtit log:

* [ ] All serial numbers (types) of tokens that received challenge response
* [ ] The information, if an auth request was ACCEPT, REJECT or CHALLENGE (contained in `result->authentication`). This way we can find challenge requests in /validate/check, in /auth and in /validate/triggerchallenge.

This could then be used, to parse and identify what happened in the mean time and take according action.

**Comment by cornelinux** [comment]
Further thoughs:

* How should we know the information how many sms where sent? 
   * It could be saved in the tokeninfo. 
   * It could be read from the audit log
* Record successfull authentication or also failed authentication (for which also an SMS was sent)

I think the initial intent was not to avoid a user authenticating wiht SMS to often, but to avoid being a user spammed with an attacker triggering sms.
But then this would be also relevant for Push tokens. Compare to #3078

**Comment by cornelinux** [comment]
A simple setup could be to increase the fail counter when the challenge was sent. (This could be configurable)

**Comment by NNLemling** [comment]
So that the considerations are also recorded in writing, here are considerations for 3 different options on how to implement this change.

### **Read from Auditlog**

- Is already implemented in a similar form
- minor adjustments would be necessary
- intermediate status of trigerchallenge should be readable from the audit log
- would also work for email/push at the same time.

### **Failcounter**

- The idea is to raise the failcounter when an SMS is triggered and to reset it after the successful login.
- To do this, the fail counter would also have to be increased when the password was entered successfully.
- The fail counter protects against phishing attacks, it may feel unnatural if this is increased even if the password is correct.


### **Challenge table**

- Take the required information from the challenge table.
- relatively complex change, since the time until deletion has to be changed and there are some exceptions when counting the entries.
- several policies would have to be created for the different token types.


### **Considerations**

- In general, it should be considered whether it makes sense to limit the number of authentications. So you could limit SMS/EMAIL/PUSH at the same time with little effort.
- 
- OR
- 
- Whether you want to limit the exact number of, for example, "sent SMS" for each token type.

**Comment by cornelinux** [comment]
We discussed the following:

add a policy in scope `authentication` or `authorization`?

action: increase_failcounter_challenge_response (or shorter naming)

Please check, that this does not collide with *increase failcounter on false pin**.

This would mean, that the failcounter for a challenge response is increased, even if the correct password was used. This would work for all tokens like SMS, email, push and other C/R
