### ISSUE TITLE
count_auth didn't increase at "Test OTP Only"

### ISSUE THREAD

**Issue by maxbeth** [privacyidea/privacyidea#969]
Hello,
i use a (smartcard) TOTP with the privacy version  2.19.1 
If i test a code with "Test token" the fields count_auth/count__auth_sucess/last_auth are updated.
And if i take the same OTP, it failed (correct)

If i test with "Test OTP only" the fields are all unchanged and the same OTP again  also failed.
In the table "tokeninfo" and "token" are all fields unchanged.
Why update "Test OTP only" no databasefields, but block the next attempt?
Regards

**Comment by cornelinux** [comment]
This actually works as designed.

The next attempt must always be blocked, otherwise a replay attack could be performed.
Technically speaking the token counter is increased on a very low level in the token class itself and will "always" happen.

If ``otp_only`` is tested (note: this was added later for convenience and is not ment for authentication process!) a mid-level library-call is called. Some decorators do not apply with ``check_otp``.
https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L345

Whereas the higher level library call ``check_serial_pass`` (see https://github.com/privacyidea/privacyidea/blob/master/privacyidea/api/validate.py#L343) already takes into account certain policies and interact with the tokeninfo.
